### ISSUE TITLE
Falling through stairs/buildings when leaving places

### ISSUE THREAD

**Issue by Hellmasker10** [Interkarma/daggerfall-unity#1372]
Whenever I leave a building, be it the Dark Brotherhood Place in Daggerfall City (the top entrances) or a random graveyard with steps in front of it, I fall through said steps (or the building). It was working in the last version, tho.

In any case: thanks for your work! :)

**Comment by Interkarma** [comment]
Thanks for report. @petchema do you think this might be related to recent change in player positioning? I won't have a chance to look closer until tomorrow.

**Comment by ajrb** [comment]
I didn't realise there had been a change made to player positioning. I did notice that walking down stairs seemed really jerky now like the capsule was stuck to the stairs - no idea if that may be related or not but thought I may as well mention it.

**Comment by petchema** [comment]
Yes, reverting af9d9e2d5e0d9d02436b6c20e215e182ba7bf93d fixes that issue.
The problem with always spawning at ground level is... when you're supposed to spawn on top of a location. We found the use case for that `position.y > targetPosition.y` test, it's clear for me now...

If the bad case with that test is fast traveling to some towns with Mountains and Hills mod, maybe that test could be only disabled when fast traveling to towns? Either that or say that terrain generators must ensure spawn points stay at height 0.

By the way I'm not sure this logic was very robust before. I checked that with 0.8.6, if you load a game inside a location and exit thru a door above ground level, you exit at ground level, usually inside the 3d model. It's only If you load a game outside of the location, enter, then exit by the door above ground, that everything works correctly.
(save inside some town walls, if front of a tower door)
[SAVE328.zip](https://github.com/Interkarma/daggerfall-unity/files/3449250/SAVE328.zip)

**Comment by Interkarma** [comment]
Thanks for looking at this one @petchema! Sounds like both a bug fix and some refinement needed. I'll take a look when I can unless it's something you want to work on some more. I don't mind either way. :)

**Comment by Interkarma** [comment]
I reverted #1359 to fix the more immediate issue. Will leave this open as a reminder for:
>I checked that with 0.8.6, if you load a game inside a location and exit thru a door above ground level, you find yourself at ground level, usually inside the 3d model. It's only If you load a game outside of the location, enter, then exit by the door above ground, that everything works correctly.

**Comment by Interkarma** [comment]
Actually, I will close this one and open a new bug that better reflects the other issue.
