### ISSUE TITLE
Lockpicking Regression

### ISSUE THREAD

**Issue by Interkarma** [Interkarma/daggerfall-unity#1373]
**Describe the bug**
Lockpicking should only allow a single failed attempt, then player must level up skill before they can try again. This is how skill was implemented, but broken in 0.10.2.

**To Reproduce**
Attempt to pick a shop's lock outside of normal hours. It's possible to spam the lock until a successful attempt is reached.

**Comment by petchema** [comment]
Bisection points at commit 2b219142ec822904d0c94736c96a49f6a1e0095c

**Comment by Interkarma** [comment]
Thank you @petchema. I didn't consider this implication of change. Will see if I can rework logic to fix.
