### ISSUE TITLE
Hircine can be summoned at any time

### ISSUE THREAD

**Issue by Interkarma** [Interkarma/daggerfall-unity#1375]
Quicky question for @ajrb. The summoning logic for Hircine doesn't check summoning date, only that player is at the Glemoril coven:

https://github.com/Interkarma/daggerfall-unity/blob/ed0bdb56ae453fcc6cd654fba001d26fbc3f76ae/Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestPopupWindow.cs#L180

But a summoning date is configured in the Hircine data:

https://github.com/Interkarma/daggerfall-unity/blob/ed0bdb56ae453fcc6cd654fba001d26fbc3f76ae/Assets/Scripts/Game/UserInterfaceWindows/DaggerfallQuestPopupWindow.cs#L53

Just checking if this one was intentional. I can't recall if Hircine can actually be summoned at any time in classic. UESP lists his summoning date as 5th of Mid Year.

https://en.uesp.net/wiki/Daggerfall:Daedra_Summoning#Summoning_Days

**Comment by Hellmasker10** [comment]
Hircine was always a bit special, even in the original... to quite from the UESP: "The only exception is Hircine, who can be summoned every day at the Glenmorial Coven and its followers in cities. He cannot be summoned by other Daedra Summoners, even on his Summoning Day."

So while it might be a bug, it's one that was present before :)

(I hope you don't mind me answering here...)

**Comment by ajrb** [comment]
Nope quite happy for you to reply there Hellmasker.

I implemented things as documented on UESP except that Hircine can be summoned on his day as well as at any time with Glemoril Witches as that seemed like a bug in classic to me.

If you follow the logic it's deciding which Daedra can be summoned depending on the summoner faction and then the day. If the UESP is incorrect about the Glenmoril Coven being able to summon him any day, then I will change it accordingly. I no longer recall what testing I did in classic myself to verify UESP info.

**Comment by df-ferital** [comment]
For information, the supposed Glenmoril Coven followers in cities are there due to a game data bug. The same wrong faction ID assignment that let you saw many Thaik, The Crow, Br'itsa and so on in houses. There are also many other wrong faction assigned to these NPCs that are not so apparent because they don't change anything visible, except when you get a quest from these NPCs, the wrong faction would then be used for reputation gain/loss.

I have a plan to patch all of these ones at runtime in the future.

**Comment by Interkarma** [comment]
Consensus seems to be that Hircine can be summoned on any day. Thank you all. :)
