### ISSUE TITLE
Quests completing instantly

### ISSUE THREAD

**Issue by Interkarma** [Interkarma/daggerfall-unity#1385]
**Describe the bug**
Forum user reports quests are completing instantly on accepting them. Forum topic with more information below.

https://forums.dfworkshop.net/viewtopic.php?f=5&t=2412

**Comment by JayH2971** [comment]
Quests entirely bypass the debugger. There's not even a tombstoned or ended version. They simply don't exist. Thankfully, it's specific to that save game.
