### ISSUE TITLE
Generic work delivery quest npc didn't spawn.

### ISSUE THREAD

**Issue by Tk420634** [Interkarma/daggerfall-unity#1387]
Started a new character and went to do some silly delivery work quests.  I took two quests and the first ones npc didn't spawn properly.  The other did.  I'm not entirely certain it didn't have to do with the type of building they spawned into?

https://i.gyazo.com/4ed861b907a81e2074b24cac8dc5b41b.png

The northern buildings delivery npc didn't spawn, but the southern ones did.  

Either way I'll probably keep trying a few of these delivery quests and see if I can get it to repeat itself.

**Comment by JayH2971** [comment]
We need a looot more info than this to get started. The quest name, a save game, and so on so we can get in and see what's going on and who spawned where.

**Comment by Tk420634** [comment]
Sure thing, I'll pass it along tomorrow.  At work right now. Sorry about
the lack of info.
