### ISSUE TITLE
Dungeon map markers are physical

### ISSUE THREAD

**Issue by Interkarma** [Interkarma/daggerfall-unity#1398]
**Describe the bug**
After placing a map marker on dungeon, player and enemies are able to climb over them in game after loading game. Collision is cleared again after opening and closing map UI.

**To Reproduce**
More details in below forum topic.
https://forums.dfworkshop.net/viewtopic.php?f=5&t=2468

Steps provided by Pango:

* place a note on the map, somewhere near you
* walk around, everything's fine
* save, quit the game, reload
* walk around, the map note is now an invisible obstacle on the ground
* open the 3d map, close itt
* everything's fine again

**Comment by Nystul-the-Magician** [comment]
ah ok oversight on my side - should be an relatively easy fix, you can assign me ;)

**Comment by ajrb** [comment]
This is one of the funniest bugs yet I think... hehe. I think it was really freaking ppl out for a while.

**Comment by Interkarma** [comment]
Thanks for fix!
