### ISSUE TITLE
%loc[nullMCP] value

### ISSUE THREAD

**Issue by xdeadmonkx** [Interkarma/daggerfall-unity#1399]
tried to get location of Lady Bridwell from King Gothryd
got unlocalized location

![nullmcp](https://user-images.githubusercontent.com/4668980/62764381-6e4e5980-ba96-11e9-8bba-124c84ca4bd9.jpg)

**Comment by Interkarma** [comment]
Resolved in https://github.com/Interkarma/daggerfall-unity/pull/1382
