### ISSUE TITLE
Vampirsim and Lycanthropy Disease applied wrong?

### ISSUE THREAD

**Issue by EPNW** [Interkarma/daggerfall-unity#1400]
In ´FormulaHelper.cs´ in ´OnMonsterHit´ is called with the ´attacker´, the ´damage´ and a ´target´.
Is it guaranteed for ´target´ to be the player (I dont think so)?

If not, where is the check if ´target´ is actually the player before infecting the player with Lycanthropy or Vamprisim? As I read the code, it does not matter who the target is, there is a chance that the player gets infected. All other diseases seem to be inflicted using ´InflictDisease´ to ´target´, and there is an explicite check if ´target´ is actually the player.

BTW: Can we add an override formula delegate to ´OnMonsterHit´ too so that mods can intercept this call?
Edit: What I actually want to do is to create a mod allowing the user to adjust the infliction rate for Lycanthropy or Vamprisim. Maybe we could just move the hardcoded values of ´0.6f´ to a static field which can be changed later using a mod?

**Comment by Interkarma** [comment]
See base DiseaseEffect.Start() for check. Diseases can only be applied to player entity level 2 or greater. As effects an be added/replaced from mods, it's not generally possible for framework to decide which effects are valid for which entities. Rather, effects are responsible for deciding their own operating conditions.

>Maybe we could just move the hardcoded values of ´0.6f´ to a static field which can be changed later using a mod?

Sounds reasonable. Have added this static field now. :)

**Comment by EPNW** [comment]
Thanks for adding the field :)
But can you please say something about my concerns in the first part of the question?
Let me give an concrete example: I was in a dungeon with a werewolfe and a centaur. The werewolfe attacked the centaur. Lets assume an attack made 5 damage. Then, from my understanding the following is called:
`OnMonsterHit(werewolf,centaur,5)`
This will lead that the following is triggered:
` switch (attacker.CareerIndex)
            {
                case (int)MonsterCareers.Werewolf:
                    random = UnityEngine.Random.Range(0f, 100f);
                    if (random <= 0.6f) //HERE IS THE PROBLEM
                    {
                        // Werewolf
                        EntityEffectBundle bundle = GameManager.Instance.PlayerEffectManager.CreateLycanthropyDisease(LycanthropyTypes.Werewolf);
                        GameManager.Instance.PlayerEffectManager.AssignBundle(bundle, AssignBundleFlags.SpecialInfection);
                        Debug.Log("Player infected by werewolf.");
                    }
                    break;
`

Now, if random is over the threshold, the player will be infected with lycanthropy, even if he was not hit by the werewolf.  There, were I wrote HERE IS THE PROBLEM should be something like  ` if (random <= 0.6f && target is player) `

**Comment by Interkarma** [comment]
Ah, I understand what you're saying now. Apologies, I should be processing this when a bit more awake. What you're saying is rather clear now. :)

I'll reopen issue and fix this one in morning. Thanks again!

**Comment by EPNW** [comment]
No problem, forgot that you are over in Australia ;) Have some good sleep!

**Comment by Interkarma** [comment]
Thank you again! This oversight actually applied to all diseases and poisons. Fixed now.
