### ISSUE TITLE
Support for virtual mods

### ISSUE THREAD

**Issue by TheLacus** [Interkarma/daggerfall-unity#1404]
Some time ago @Nystul-the-Magician [raised the need](https://forums.dfworkshop.net/viewtopic.php?p=4377#p4377) to simplify mod testing and use debuggers during mod development and came up with this solution:

```cs
/*  
*   used for debugging
*   howto debug:
*       -) add a dummy GameObject to DaggerfallUnityGame scene
*       -) attach this script (_startupMod) as component
*       -) deactivate mod in mod list (since dummy gameobject will start up mod)
*       -) attach debugger and set breakpoint to one of the mod's cs files and debug
*/
void Awake()
{
     initMod();
}
```

The issue is that mod functionalities like settings, loading resources or localization are not functional during debug. So i decided to further develop the idea with a concept of "virtual mod", which relies on a folder inside `Assets/Game/Mods` instead of an assetbundle when running inside the Editor. This is a pratical example:

```cs
public class Test : MonoBehaviour
{
    static Mod mod;

    [Invoke(StateManager.StateTypes.Start)]
    private void Init(InitParams initParams)
    {
        mod = initParams.Mod;
        var go = new GameObject(mod.Title);
        go.AddComponent<Test>();
    }

    private void Awake()
    {
#if UNITY_EDITOR
        if (mod == null)
            mod = new Mod("Test/Test.dfmod.json");
#endif

        mod.IsReady = true;
    }

    private void Start()
    {
        var settings = mod.GetSettings();
        int number = settings.GetValue<int>("Configuration", "Number");

        var texture = mod.GetAsset<Texture2D>("Example_Tex");
        var shader = mod.GetAsset<Shader>("NewUnlitShader");
        var material = mod.GetAsset<Material>("Example_Material");
    }
}
```

All the code is shared for both testing and releases because the Mod class instance handles loading assets from assetbundle, if running from a released mod, or `Assets/Game/Mods/Test/Resources/` if running from a virtual debug mod environment. Ideally, this means you can write and test a mod with the same comfort of writing core code, and only build an assetbundle for release.

I published this to a separate branch for testing and get some opinions :)

**Comment by ajrb** [comment]
I've been using Nystul's technique, and I have two forks of the codebase - 1 for debugging with loose assets and another for testing the dfmod when ready. Will this remove the need for that? I don't quite get what this does. (sorry for being slow)

**Comment by TheLacus** [comment]
Take this call for example:
`var texture = mod.GetAsset<Texture2D>("Example_Tex");`

If you run it in Editor, the asset is loaded from Assets folder, otherwise is loaded from AssetBundle.
This means you can test mod with individual files in editor and only build AssetBundle to make a release.

**Comment by TheLacus** [comment]
I improved it so that virtual mods are loaded automatically like mods from StreamingAssets.
You need to add the `.dfmod.json` manifest file to the list of `Virtual Mods` on the Mod Manager gameobject, without making any change to mod scripts.

![VirtualMods](https://user-images.githubusercontent.com/24359151/62836023-16af1a00-bc5f-11e9-857a-07f2de953e50.png)

The usual Init() functions are invoked at the specified StateType rather than always at startup. Now debugging a mod is as simple as playing from the Startup scene, no need to have different intro points for editor and assetbundle.

**Comment by Nystul-the-Magician** [comment]
will have to test this out the next time I touch my mods ;)

**Comment by TheLacus** [comment]
I think i tested it enough, merged to master now.

**Comment by AsesinoBlade** [comment]
Hi, I have the latest build, but i do not see the virtual mod section in modManager.  I see a drop down for mods array, and a toggle for Virtual mods but no array for virtual mods in the script area in inspector.  Do I need to replace default mod Manager script with a different one?
Sorry for the dumb questions.
thanks
a

**Comment by ajrb** [comment]
It was removed as far as I can see and they are picked up automatically. Follow the instructions on the mod doc pages of the workshop.

**Comment by TheLacus** [comment]
I confirm this has changed after i wrote that post, now mods are picked automatically if placed inside _Mods_ folder. You can toggle virtual mods directly from the mods window in game instead.

**Comment by AsesinoBlade** [comment]
thank you very much
i appreciate the quick response!

thanks
A

**Comment by AsesinoBlade** [comment]
hi all, I finally got around to testing how this works, and can confirm that I have it working now.  It is quite slick, just drop the mod builder dfmod.json file into assets\game\mods and the mod shows up in mods.  Nicely Done!!  I can now debug my mod scripts!

thanks again for the very fast responses.
A
