### ISSUE TITLE
Enchanting gear while equipped leaves permanent armor rating on the player

### ISSUE THREAD

**Issue by yoboseo** [Interkarma/daggerfall-unity#1409]
**Describe the bug**
Enchanting gear while it is equipped will have it be unequipped upon enchanting, but the armor rating of said gear is not removed from the player. This leaves a permanent armor rating on the character which can then stack in weird ways when another piece of armor is equipped. Doing this multiple times can result in negative armor ratings.

**To Reproduce**
1. Equip a piece of gear, say a Daedric helmet with 21 armor rating
2. Enchant it with anything
3. The helmet is removed and put in the inventory but the 21 armor rating is preserved on the player
4. Equipped gear will stack with this permanent armor rating

**Expected behavior**
The armor rating should be removed from the player when the gear is removed during the enchanting process.

**Comment by Interkarma** [comment]
Thank you! Have fixed this now.
