### ISSUE TITLE
Turning into vampire has issues

### ISSUE THREAD

**Issue by ajrb** [Interkarma/daggerfall-unity#1411]
**Describe the bug**
I encountered a few problems with turning into a vampire. It seems things were firing twice, maybe I was infected twice or something but save data only has a single entry so seems not.

The dream video played twice, two lots of vamp abilities added to spells, died and woke up in crypt twice. Log shows that $CURVAM quest failed to parse:

Parsing quest $CUREVAM FAILED!
Search failed to locate matching remote site for Place _wrongdung_ in region Glenpoint. Resource source: 'Place _wrongdung_ remote dungeon5'

Attached zip file with following saves:

96: Sick - Got the vamp infection and have travel message
97: vampirism - Dream video played (twice in a row) and have rested for 2 days. 1 more day and will die and re-spawn in crypt.
98: twoCopiesVampSpells - Woke in crypt 1st time with 2 lots of spells. Travelling caused death and re-spawn in different crypt (once) or black screen and locked up game (intermittent).

**To Reproduce**
Loading 97 and resting worked when I tried to reproduce again.
Loading 98 broke twice and then worked.

Not really sure what was/is going on.

**Expected behavior**
Have things happen once and not crash the game.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 0.10.4
[vampSaves.zip](https://github.com/Interkarma/daggerfall-unity/files/3489867/vampSaves.zip)

**Comment by Interkarma** [comment]
I've had a similar report for lycanthropy deployment recently. Have an idea of the issue, will dive into it when I can. Thank you for the saves and detailed information. Very helpful!

**Comment by ajrb** [comment]
I hope so, it's either intermittent or cured by restarting game and reloading. Hopefully you can find the problem.

**Comment by EPNW** [comment]
I got the same effect after infecting my character multiple times with vampirsim using the console.

**Comment by Interkarma** [comment]
I have pushed some lifecycle fixes now that should resolve all cases of duplicate symptoms (e.g. multiple dreams/duplicate spells) resulting from secondary non-incumbent vampire/lycanthropy infections waiting to expire. These infections were not marking themselves completed properly before.

I wasn't able to reproduce the game lock you mentioned, but I _suspect_ it has to do with End() of non-incumbent instances not checking for incumbent status before unsubscribing events that are only subscribed if incumbent. Hopefully that fixes it. I've heard of locks around vampirism before after fast travel, but haven't been able to reproduce myself. Hopefully this does the job.

Please let me know if any further issues after recent change. I'll keep testing and close this issue once everyone seems happy.

**Comment by Interkarma** [comment]
This appears to have been resolved. Closing.

**Comment by Interkarma** [comment]
Some issues seem to remain with lifecycle. Reopening this issue to take another look when I can.
https://forums.dfworkshop.net/viewtopic.php?f=5&t=2744
