### ISSUE TITLE
%fnpc[nullMCP] on NPC

### ISSUE THREAD

**Issue by ShortBeard** [Interkarma/daggerfall-unity#1413]
**Describe the bug**
Guard "Bauctun" in Sentinel Castle (The main castle in the Sentinel City) seemingly tries to retrieve his own faction with %fnpc, but he doesn't have one or it's not retrieving it properly. This is happening as of version 0.10.4. Not sure if he is the only NPC with this issue.

**Save file in front of the Bauctun here. Note this save file uploaded is the character in the Dragon Knights:**
https://www.dropbox.com/s/bguwslgo1fq0tnx/SAVE8.rar?dl=0

**Also the same position, but another character that is in Julianos**
https://www.dropbox.com/s/bmkituo35dawonn/dfu_sentinel_guard_bug.7z?dl=0

This is what happens if the player character is in the **Dragon Knights**
![Bug_1](https://user-images.githubusercontent.com/8405659/62833932-5b4fab00-bc89-11e9-8ada-622d0b0f0bd8.PNG)

This is the NPC dialogue when the player character is in **Julianos**
![bug_2](https://user-images.githubusercontent.com/8405659/62833940-77534c80-bc89-11e9-8c77-d5b94761024b.png)

**Comment by ajrb** [comment]
Saves please. Don't make us have to replicate it ourselves. Ta.

**Comment by ShortBeard** [comment]
> Saves please. Don't make us have to replicate it ourselves. Ta.

Added it, sorry about that!

**Comment by ajrb** [comment]
Seems the guard in sentinel uses a different billboard, although the look identical to me. Have added this to the check that suppresses the normal talking which should not be initiated, hence the null MCP.

**Comment by Interkarma** [comment]
Fix merged. Thank you!

**Comment by df-ferital** [comment]
I provided a better fix in #1473
