### ISSUE TITLE
AllowMagicRepairs not working.

### ISSUE THREAD

**Issue by renic** [Interkarma/daggerfall-unity#1417]
"AllowMagicRepairs = True" doesn't seem to be working.  The checkbox saves the setting to the ini file correctly, but attempting to have a smith repair a broken magical item results in the message: "You cannot repair magic items."

 - OS: Windows 7
 - Initialized engine version: 2018.2.21f1 (a122f5dc316d)

**Comment by petchema** [comment]
For me it works since commit 84450787e7d0bb6ad8f683b0ccb1961e638c1346 from yesterday.
So check with a newer version, I think this has already been fixed.

**Comment by renic** [comment]
Commit looks like it would fix it... retested with this release:
DaggerfallUnity_Windows_x64 #96
Size: 35.6 MB
Aug 10, 2019 4:33:20 PM

Wasn't fixed... will test again with next release (since there are no tags or release markers... not really sure how to test without having to compile).  Thank you.
