### ISSUE TITLE
Texture replacement for first person axe is drawn at incorrect position

### ISSUE THREAD

**Issue by TheLacus** [Interkarma/daggerfall-unity#1419]
**Describe the bug**
First person Axe (WEAPO108.CIF ) is drawn with an incorrect position on screen.

**Additional context**
Reported at https://forums.dfworkshop.net/viewtopic.php?f=5&t=2507

**Comment by Interkarma** [comment]
I added some info on this one to that forum topic. Hopefully will be helpful.

**Comment by TheLacus** [comment]
Apparently this was due to user-error from mod author. I'm closing for now; can reopen if new informations arise.
