### ISSUE TITLE
Weather effect animations reset when walking to a new zone in the overworld

### ISSUE THREAD

**Issue by BlueBolt70** [Interkarma/daggerfall-unity#1420]
**Describe the bug**
When moving on foot/on a horse/cart to a new zone in the overworld (ex. moving from one pixel on the world map to the next), weather effects such as rain and snow reset and play independently from the previous zone. Moving back and forth between the previous and next zone will show that the snow falling effects doesn't match with eachother.

**To Reproduce**
Just run into a direction in the overworld while it's raining/snowing (it's easier to notice when it's snowing.)

**Expected behavior**
The snow/rain will briefly disappear and start falling down all over again.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64-bit
 - Version Alpha 0.10.4

**Comment by petchema** [comment]
Yes, I noticed the issue a while back:
https://forums.dfworkshop.net/viewtopic.php?f=5&t=1916&start=10#p23383

**Comment by petchema** [comment]
This should be fixed as of 0.10.22
