### ISSUE TITLE
Enhanced Mod Support for FormulaHelper

### ISSUE THREAD

**Issue by EPNW** [Interkarma/daggerfall-unity#1422]
The FormulaHelper is a central place where all kind of things are calculated.
Most methods offer the possibility to be overridden by a mod using formula delegates.
I think this is a very good design pattern, but I'd like to take things two steps further:

1) As last parameter of each formula delegate add an `out bool apply` parameter.
If the value of this bool is `false` after the formula delegate returns, don't use the value the delegate provided, but go on with calculations.
This way I can for example override "DeadraSummoningCosts" only if the faction is "Glenmoril Witches" or stick to normal behaviour otherwise.

2) Change the Formula Dictionaries to take a SortedList as value instead of the formula delegate directly.
E.g. `Dictionary<string, Formula_1i>` to `Dictionary<string, SortedList<int,Formula_1i>>`.
Mods should register their formulas in the sorted list, with their mod load order as key.
Then, if we also implement 1) we can iterate through all registered formulas, and return the first where the `apply` parameter is true.

Changing this would break some of the current mods, but will provide a much more flexible solution for the future. I'd like to discuss this ideas before making a PR.

**Comment by ajrb** [comment]
I will take a look at these suggestions when I'm back from holiday. They seem like a good idea to me, but I will want to check the code and think more about it. Originally I thought that only one mod could effectively override a formula, but this is a nice idea to allow more complex behaviour. Main concern is that this complex behaviour dependent on mod order may provide a lot of end use confusion and/or issues.

**Comment by JorisVanEijden** [comment]
Here's an approach for allowing multiple mods not only to replace formulas but also to act on existing values: https://gist.github.com/JorisVanEijden/0e9c18bc35709e4eecd2b3b9719f3e80

Example usage by mod:
```
DaggerfallWorkshop.Game.Formulas.FormulaHelper.RegisterFormulaAlter("DamageModifier", AlterDamageModifier, 100);

public int AlterDamageModifier(ref currentValue, int strength) {
  currentValue -= strength / 2;
}
```

Just as food for thought.
You could even make it backwards compatible by adding
```
Formula_1i del;
if (formula_1i.TryGetValue(name, out del))
  result = del(input);
```
To the `ApplyAlterations1I()` method.

**Comment by TheLacus** [comment]
Note that mod load order is supposed to be like Skyrim, where mods at lower positions override what comes before them. 

I'm also not sure mods should pass their own position, it may be better to have a Mod parameter instead, but i don't have a strong opinion on this.

 ```cs
public static void RegisterFormulaAlter(string formula, Formula1I callback, Mod provider)
 ```

> ```cs
> alterations = alterations.OrderBy(o => o.Weight).ToList();
> ```

I would use `Sort()` instead, to avoid additional allocation.

**Comment by JorisVanEijden** [comment]
The case for mods supplying "weights" themselves is so that they can decide to be early on one formula and late on another.

Yes, good call on the sorting.

**Comment by petchema** [comment]
can this issue be closed now?

**Comment by ajrb** [comment]
I think it should be closed, while the OP's suggestion has not been implemented the overriding ordering has been improved by TheLacus and there's no demand for audo mixing mod functionality by having a system like this. I suspect the complexity and unintended consequences is not worth it, and if 2 mod authors wish to collaborate there are other ways to explicitly handle mixing of function.
