### ISSUE TITLE
MOB30Y08 quest problem

### ISSUE THREAD

**Issue by ajrb** [Interkarma/daggerfall-unity#1423]
**Describe the bug**
Accepted quest MOB30Y08 from FG. By context it should be a house but instead the towns' Temple of Kynareth was assigned. The _S.04_ task is not triggered when entering the temple so the zombie never spawns.

**To Reproduce**
1. load attached save
2. exit & enter temple and see that task status doesn't change

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 0.10.4

**Additional context**
Not sure whether the issue is that the target building needs to be a house or if the quest is just broken regardless.

**Comment by JayH2971** [comment]
The save file doesn't have M0B30Y08 activated. It's called "houseFilled" and talks about returning a blonde priest to the Temple of Kynareth.

**Comment by ajrb** [comment]
[SAVE105.zip](https://github.com/Interkarma/daggerfall-unity/files/3498419/SAVE105.zip)
Sorry, uploaded the wrong save. Sorry Jay.

**Comment by JayH2971** [comment]
You're in Wildertown but you need the temple of Wilderfort ;) (before you feel dumb, we have all made that mistake.)
I just killed the zombie and completed the quest. It's very odd that the quest debugger put a marker on the local Temple of Kynareth but it actually wasn't present when I returned to turn in the quest.

**Comment by ajrb** [comment]
Doh. I read those names as the same and then took the marker from the quest debugger as confirmation of the bug. Thanks for setting me straight Jay.
