### ISSUE TITLE
Dungeon AutoMap marker disappearing after save

### ISSUE THREAD

**Issue by deepfighter** [Interkarma/daggerfall-unity#1431]
**Describe the bug**
Reported by DiaBomb (https://forums.dfworkshop.net/viewtopic.php?f=5&t=2517)

After saving (Quick save or through the pause menu), any markers created on the dungeon AutoMap disappear. The Markers do stay after re-entering the dungeon without saving in between. I only have a few graphics mods installed. Disabling them did not fix the issue.

**To Reproduce**
See screenshot

**Expected behavior**
Marker should stay like they are before saving

**Screenshots**
https://i.imgur.com/vpind6H.gifv

**Desktop**
 - OS: Windows 7 64Bit
 - Version 0.10.3 and 0.10.4

**Comment by Nystul-the-Magician** [comment]
Will take a look

**Comment by Kiel97** [comment]
I have the same issue. I play Daggerfall Unity without any mods.
