### ISSUE TITLE
N0B10Y03 bugged out at the time was maybe completing as failure every tick

### ISSUE THREAD

**Issue by concarne000** [Interkarma/daggerfall-unity#1439]
**Describe the bug**
The quest to protect the mages guild didn't seem to end right at the time for me. After staying there a night and attacking the thieves I could not talk to quest giver (no popup.)

My reputation kept dropping to -100 for all mages factions and recently randomly for the region I was in. Looked at my notes and saw a repeating note going for eternity -

        [
            "D:Quest ended at 15:19:34 02 Midyear 3E405:",
            "Sundas the 1st of Midyear: I agreed",
            " to guard a magic Formal cloak",
            " at the Mages Guild of",
            " Newtale. I have",
            " to be there between midnight",
            " and three.",
            ""
        ],

My NotebookData.txt is 1488907 lines long.

I resolved the problem by completing the quest by editing the QuestData.txt

**To Reproduce**
This was a long time ago so I don't have a save sorry. I stayed in the mages guild and kept loitering to get the thieves to appear. I may have rested to heal I cannot remember, I am pretty sure I saved in the middle of the quest after fighting some thieves.

 - OS: Windows 10
 - Daggerfall Unity 0.10.3

**Comment by Interkarma** [comment]
>This was a long time ago so I don't have a save sorry

Can you recall how long ago? Are you able to reproduce using 0.10.4? Cheers. :)

**Comment by concarne000** [comment]
Reproduce the original bug during the quest? Or the repeating failure? I just downloaded 0.10.4 and the repeating failure still persists. Here is a save that shows the quest ending every second in the notes log


https://drive.google.com/file/d/1FuhKF_H7WpoKOhvNkjiDqBhw_4WJrKbh


As far as the guild quest bug, is there a way to initiate the quest without brute force requesting quests from the guild master?

**Comment by JayH2971** [comment]
To get the quest from the guild, go into /DaggerfallUnity_Data/StreamingAssets/Tables/QuestList-Classic.txt and go to the Mages Guild section. Wipe out every line except for N0B10Y03. (Back up your QuestList before doing so). Then it'll offer each time.

**Comment by Interkarma** [comment]
Another method is to click quest giver and close prompt, then use console:

    startquest N0B10Y03

The reason you click the NPC first is that "startquest" will use the last NPC you clicked as the questor.

**Comment by concarne000** [comment]
Ok the quest works fine now. I looked back and I had a couple of saves either side of the quest and have tried to reproduce the bug with all the versions saved to my computer but unfortunately nothing seem to reproduce it.

So going through the QuestData.txt I see you parse the quest and then save it to the save at the time you receive it, so that is almost certainly a bug from a past version, right? I apologise - I assumed the quests were parsed on the fly from the game data.

**Comment by Interkarma** [comment]
Thanks for getting back to me! Happy to hear this is resolved once you re-instantiated the quest.
