### ISSUE TITLE
Blank book with no value

### ISSUE THREAD

**Issue by BlueBolt70** [Interkarma/daggerfall-unity#1445]
**Describe the bug**
While exploring a dungeon, I found a blank book on a enemy humanoid NPC's corpse with no value. When attempting to read it, it says "The book is ruined and is unreadable."

**Screenshots**
![image](https://user-images.githubusercontent.com/39875720/63308857-78582f80-c2c2-11e9-8537-4eb35fc8a6e8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64-bit
 - Version 0.10.4

**Comment by Interkarma** [comment]
Hi, can you please provide a save with item in question?

Possibly book didn't randomise properly and you can simply dispose of item.

**Comment by BlueBolt70** [comment]
Sure thing.
[SAVE6.zip](https://github.com/Interkarma/daggerfall-unity/files/3518251/SAVE6.zip)

**Comment by Interkarma** [comment]
Thank you! I'll see if I can find an issue with book generation when dropped as loot.

**Comment by JorisVanEijden** [comment]
This book has message/id 10000. Which translates to BOK00016.TXT which does not exist.

@TheLacus has made some exceptions in the code for the id 10000 to be considered a daggerfall classic book. But I can't find out why.
In \Assets\Resources\books.txt it is listed as "Ark`ay The God" but that is book id 5.

I think the easiest thing here would be to only fix the %ba book author display.
I created #1451 for that.

**Comment by TheLacus** [comment]
If you enable setting `CustomBooksImport`, which is disabled by default, names are resolved to standard `BOK*.TXT` form if they are defined as classic books (which i considered as <= 1121 or equal to 10000), otherwise they are resolved with informations provided by mods. If disabled, everything is resolved with classic form.

I don't know why Ark`ay The God is also assigned to 10000, classic book mapping file was made by another contributor.

**Comment by Interkarma** [comment]
I can't recall the reason that 10000 mapping was added. All that happened over 3 years ago now. It was likely to support importing a book from classic with a weird ID.

I'd honestly be happy to remove the kludge mapping and have DFU only offer known-good mappings. If this means we get a bad book import from classic saves occasionally, then so be it.

Alternatively, we can keep the mapping and exceptions and just change random loot to never use ID 10000 for generated books. Then the bad item should never drop.

I think @JorisVanEijden's recent PR is a good idea in any case to cover any bad books in existing saves wherever they originated from.
