### ISSUE TITLE
Advanced Climbing System - Clipping issue when climbing down a wall that's not connected to the ground

### ISSUE THREAD

**Issue by BlueBolt70** [Interkarma/daggerfall-unity#1446]
**Describe the bug**
When climbing down a wall that isn't directly connected to the ground (For example, a pit used for an elevator platform), when trying to climb down and around to hang from the ceiling underneath, the game instead clips you into the wall, unable to move. I recommend watching the video depicting the bug down below.

**To Reproduce**
1. Go to a dungeon area where a wall segment is connected to the ceiling of a corridor.
2. Using the advanced climbing system, climb down towards the ceiling of that corridor by holding the Reverse/Walk backwards key (S).
3. Keep climbing down once you get to the corner of that wall and eventually you'll get stuck inside it as the game goes into rappel mode/hanging mode.

**Expected behavior**
Upon getting stuck inside the wall, you are unable to escape through normal means. Either reload a save or use the teleport console command to get out.

**Screenshots**
https://gfycat.com/untrieddismalfruitfly

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64-bit
 - Version: Alpha 0.10.4

**Comment by Interkarma** [comment]
I understand that hanging mode is going to be discontinued completely. That will at least prevent this bug from occurring.

**Comment by Interkarma** [comment]
Hanging mode has now been disabled from next builds.
