### ISSUE TITLE
Immunity to Poison seems not working

### ISSUE THREAD

**Issue by Yagiza** [Interkarma/daggerfall-unity#1452]
During character generation, I made my character immune to Poison. But when Giant Spider attacked me with its Poisonous paralyzing effect, I got paralyzed. In original Daggerfall from Bethesda Softworks, I'm unaffected by that effect in such case.

**Comment by JorisVanEijden** [comment]
In Daggerfall Poison and Paralyze are two different effects.

The attack from spiders uses Paralyze and is countered by immunity to paralysis. See: https://en.uesp.net/wiki/Daggerfall:Spider

Poison refers to an effect from poisoned weapons and can be countered by immunity to poison. See: https://en.uesp.net/wiki/Daggerfall:Poison

**Comment by Yagiza** [comment]
In original Daggerfall Poison is not an effect, but an elemant (like Fire, Frost, Shock or Magic). So, Immunity to Poison gives immunity to all the effects of attacks, which has that element (just like immunity to other four elements).
So, if you have crytical weakness to Paralysis, but immunity to Poison, and being attacked Poisonous attack with Paralysis effect, you'll never be paralyzed.
I can provide a video with original Daggerfall, if you need any proofs. Or you can check it yourself.

**Comment by Interkarma** [comment]
Immunity to Poison trait will give you full resistance to both the Poison element from spells and physical poisoning from enemy weapons.

This is not what spiders and scorpions use however. They cast spell STD # 66 "Spider Touch", a Paralysis spell carried by Magic/Arcane element. Their paralysis is not related to poison and never has been. :)

If you want to shrug off paralysis from spiders and scorpions, you will need Immunity to Paralysis. This functions identically in classic Daggerfall and Daggerfall Unity.

https://en.uesp.net/wiki/Daggerfall:Spider

https://elderscrolls.fandom.com/wiki/Spider_(Daggerfall)

https://en.uesp.net/wiki/Daggerfall:SPELLS.STD_indices

**Comment by Yagiza** [comment]
So, I was wrong about Poison. But my character also has resistance to Magic. So, he must not be paralyzed by Spider touch anyway.

**Comment by petchema** [comment]
> So, I was wrong about Poison. But my character also has resistance to Magic. So, he must not be paralyzed by Spider Touch anyway.

This is not handled the same way in Daggerfall Unity and in classic Daggerfall, see
https://www.reddit.com/r/daggerfallunity/comments/b44wi0/immunity_to_magic/ej49y1c/

**Comment by Yagiza** [comment]
So, that's not a bug, but feature.
I see the problem, authors tried to solve, but I beleive, solution is not perfect. Maybe we need to discuss it on the DFU forum?
