### ISSUE TITLE
Black Sky after Leaving Building During Foggy Mid-Day

### ISSUE THREAD

**Issue by Burin077** [Interkarma/daggerfall-unity#1454]
**Describe the bug**
When exiting buildings while in town or the overworld during a day when it is daytime and foggy, there is a strange delay where the sky is black; it is not treated as being nightfall, but the lighting from both the fog and sky seems to take a while to return. It's not a permanent issue, but one that seems to happen frequently when I enter/leave buildings in town.

**To Reproduce**
1: Enter any town during the day (Between 6:00 and 16:00, when the sun is out. (It must be foggy outside.)
2: Enter a store or building in the town. (I used a Pawn Shop and General Store.)
3: After doing business, leave the building. (When you step outside, the sky will be black.)

**Expected behavior**
For the foggy, slightly dimmed light sky to be retained from the first time I entered town.

**Screenshots**

![DagUnityBug2](https://user-images.githubusercontent.com/54295726/63461975-6f30a500-c41f-11e9-848d-32545989b913.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Edition
 - Version: 10.0.17763, Build 17763

**Additional context**
This issue does not happen with other forms of precipitation from what I have seen, only fog.

**Comment by JayH2971** [comment]
Forum topic: https://forums.dfworkshop.net/viewtopic.php?f=5&t=2395

**Comment by Interkarma** [comment]
Resolved by https://github.com/Interkarma/daggerfall-unity/commit/59926599524d9bf835165cb55de439db3d54b639.
