### ISSUE TITLE
Info mode on Sheogorath gives out a commoners name

### ISSUE THREAD

**Issue by deepfighter** [Interkarma/daggerfall-unity#1456]
Couldn't find this in the commits to be already fixed, so here we go - Bug reported by pango [here](https://forums.dfworkshop.net/viewtopic.php?f=24&t=2068).

**Describe the bug**
By clicking via Info mode on Sheogorath he gets a random(?) name and is handled as a normal NPC in this matter

**To Reproduce**
1. Go to Sheogorath
2. Click via Info mode on Sheogorath
3. A name appears above the screen.

**Expected behavior**
According to Jay: "It turns out Sheogorath has no name. If you click on him in any way, including F3, he'll give his speech. If you're out of speech range, nothing will show up; it'll just say, "You're too far away."

**Screenshots/Save**
See first post in thread above.

**Desktop 
 - OS: Windows, Linux Universal

**Comment by ajrb** [comment]
How do you "Go to Sheogorath"? Any chance of a time saving savefile? Also, could you say if this is part of the main quest, as if so I will leave the fix to another dev.

**Comment by deepfighter** [comment]
Save file by pango [here](https://forums.dfworkshop.net/download/file.php?id=3525) (as mentioned also first post of the thread :-) ).

You meet Sheo in the course of the MQ ([at the very end](https://en.uesp.net/wiki/Daggerfall:Journey_to_Aetherius#The_Blind_God_.28The_Room_of_Fire.29))
