### ISSUE TITLE
Potion Maker - Resources Used Endlessly (No Gold Cost Either)

### ISSUE THREAD

**Issue by Burin077** [Interkarma/daggerfall-unity#1467]
**Describe the bug**
When using the Potion Maker (I'm using the one at the Order of Arkay for example), as long as you have one copy of the ingredient in your inventory, you can endlessly make a potion related to it. The ingredient will pop up again in the Mixing Cauldron even when you don't possess any more of the ingredient (It will have no number remaining next to it, treating it as if a single object again.) When I go back to my Inventory or Wagon. I haven't been able to identify all the ingredients this happens with, however the one I tested, Fig, seems to do this endlessly.

**To Reproduce**
1: Go to any Potion Maker.
2: Select a Recipe from your Recipe list, make sure you have the ingredients you actually need for the potion. (I was doing Potions of Purification for example.) Also, make sure one of the ingredients in your inventory only has an amount of 1.
3: After the objects are put into the Mixing Cauldron for the potion, hit "Mix." The potion will be mixed, and put into your inventory.
4: Attempt to mix the same potion again. (The ingredient you already used will pop back up.)
5: Check your inventory. (You may notice the object still in your inventory or wagon, wherever you left it.)

**Expected behavior**
When you create a potion, the ingredients used for it should be consumed; the items used should be removed from your Wagon or Inventory.

**Screenshots**

![DagUnityBug3](https://user-images.githubusercontent.com/54295726/63740082-46604380-c855-11e9-8bb2-fb9462703447.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 10.0.17763, build 17763.

**Additional context**
(Note: If the object is not visible when you check your inventory, and go back to the Potion Maker, the recipe will not be able to be crafted; this is what should be happening in the menu already.)
(Additional Note: Gold is not charged for Potion Making; was this intended?)

**Comment by ajrb** [comment]
This is already fixed and is just waiting for a build.

Thanks for the very good and detailed report.. but I found this myself shortly after fixing the wagon access code for the last build, but the fix missed that one.
