### ISSUE TITLE
Inclusion of BIOGFix patch

### ISSUE THREAD

**Issue by deepfighter** [Interkarma/daggerfall-unity#1468]
It's not a typically bug report, but more a question/discussion if my fix for the BIOG files are already included in DFUnity and if not if these changes should make it into the basic game or should be added as a modification. [I gathered the changes and other inconcistencies of these files in a sheet](https://docs.google.com/spreadsheets/d/1MyDLmIMQ1G20QWbkGWQg7Pxl07TAJGM_VsLN-b025_o/edit#gid=1255506648). Of course not everything has to be included (like the over 200 Gold questions), but some changes seems reasonably, and in the [forum](https://forums.dfworkshop.net/viewtopic.php?f=12&t=121&p=934#p934) nothing else was found back then.

Sadly, I don't really understand how the code works, I tried to find where the values are stored and to check for myself (to save you work), but wasn't successful. I just found some commits, which haven't changed - for my eyes - anything/much from the BIOG file errors:

- Changing social group adjustements #1039
- Biography quiz for new characters #886 

So I was wondering how to handle these mistakes in the BIOG files. Keep them, and fixing them as a additional patch or changing already some obvious mistakes in DFUnity itself? Or was that done already?

I copy @numidium; @Allofich because they know probably the best about it. :)

**Comment by Interkarma** [comment]
DFU uses BIOG files data on the end user's PC, these files aren't part of DFU itself.

If your patches were installed into the end user's Daggerfall game data, then DFU would use them. But that would require everyone to patch their game data the same way.

That's been one of the more frustrating elements of this project - we can't control the data quality on the user's side because we don't own the game property itself. Any other game would just be able to patch these files and distribute patch using whatever store they're on.

**Comment by Interkarma** [comment]
Frank, I'd love to integrate your fixes into the core. I'm thinking we could include the patched versions of the BIOG file in StreamingAssets in the way we do the decompiled quests. DFU can then use the updated BIOG data instead.

If you can get me a zip of the patched BIOG files, I'll merge these into core so everyone gets them. I can't see any other good way to do this other than asking everyone to patch their local game data.

**Comment by deepfighter** [comment]
First of thanks for you confirmation and your idea in implemeting these fixes.

I have also thought about it a bit further. If we are going with your project goal, I am a bit hesitant to fix them, instead offering it as a modification like in Classic. I know DFUnity has already some Classic fixes (foremost in the quest files) which make absolutely sense, as the quests itself were intended like that. So there is kind of a "black" and "white". It's different with these BIOG files. Besides the obvious mistakes like in BIOG00T0.TXT (and mostly all other standard magic classes) where selecting "practicing acrobatics" in question #3 mistakenly improves the character's Orcish rather than Jumping, I have changed some things, which seem to be more logical, but were maybe intended by the devs. I tried to strike a balance between changing not to much, but to make it more logical, also preventing massive balance changes. For example:

# BIOG07T0.TXT {Burglar}

* 7 a) The question "Where is your expertise in combat?" has the answer "Short-bladed weapons" which gives you 'Iron Gauntlets' instead of a short-bladed weapon.
**Changed the outcome to 'Iron Short Sword'.

* 7 b) The question "Where is your expertise in combat?" has the answer "Hand-to-hand combat" which gives you 'Iron Cuirass' instead of help for Hand-to-hand combat.
**Changed the outcome to 'Iron Gauntlets'.

Maybe those were intended ( or just oversights, no idea. Probably the latter, but I just want that we are really sure to fix those things. While most people will play with these fixes in Classic anyway, because they are just installing Daggerfall Setup with all the fixes instead of thinking further about it, here we decide what's to be further implemented in opposite to Classic, which is a huge responsibility for this great game with all his history (at least for me). But as I have for every change a reasons and can explain why this or that should be changed I feel confident and comfortable that this will not break the game and instead really fixes obvious mistakes. Just wanted to share my thoughts.

Another pro argument for handling BIOG files directly by DFUnity is with translation support in mind. As there are some text to be translated, even though a standard text-editor is enough for editing, it makes things (probably) easier for most if these files are also directly handled by DFUnity.

As for that, you actually just need the [English folder of the fix](https://drive.google.com/file/d/0B5d8Cfi4rIADR1NHc3hhUlpTbDQ/view). For transparency reasons the changelog is in the readme. I don't know if these changes from classic should be commented on in the code. I could do that myself in a later stage to save you at least some work, but it's up-to-you.

Thank you like always and if there is something I can help out with, don't hesitate to ask.

**Comment by DSeyka** [comment]
Honestly, all of these look like straight up bugfixes to me, and since quest fixes are already bundled with DFU, I don't see why these shouldn't be as well.

You could also try asking Ted Peterson (@CharlesPeterson) on Twitter, maybe he knows if any of those were intentional, but I strongly doubt it. After all, he himself said the development of Daggerfall was pretty rushed.

**Comment by deepfighter** [comment]
For not delaying this any further, I would like to provide the [ZIP file here](https://drive.google.com/file/d/1Llqm_Y8FvP7eGpFSq2j9CaZuagygInkc/view) of my updated fix. I was thinking, if we find further changes, we could always change them in the future if necessary. 

For everyone reading this issue - this will fix issues in Classic. All changes made are included in the corresponding ReadMe. A visualisation of these changes and all the questions with their respectful answer are also gathered in this [Sheet](https://docs.google.com/spreadsheets/d/1MyDLmIMQ1G20QWbkGWQg7Pxl07TAJGM_VsLN-b025_o/edit?usp=sharing). If you have comments or see other mistakes, please don't hesitate to comment there. In one of these tables I also listed some other possible changes, inconsistencies or ideas. Always open for discussion! :)

**Comment by Interkarma** [comment]
Hi Deepfighter! Just trying to download zip file and share appears to restricted. Are you able to host that publicly or email me zip to interkarma@dfworkshop.net and I'll look into integrating with base DFU. Thank you.

**Comment by XJDHDR** [comment]
@Interkarma I'm not sure if you noticed but @deepfighter modified his last comment to change the link to his updated fix. I'm able to download the fixes from the new location.
