### ISSUE TITLE
Travelling to the larger ship spawns you in the water.

### ISSUE THREAD

**Issue by zeldafan1593** [Interkarma/daggerfall-unity#1471]
**Describe the bug**
I purchased the large ship to make travelling easier. Unfortunately, I noticed that whenever I go onto the ship itself (I used it a lot to allow myself to sleep in towns without finding a tavern), I was spawned inside of the ship down at the ground, which forces me to either use a levitate spell or use the levitate on command so I may get onto the ship itself. 

**To Reproduce**
1. Buy large ship
2. Change travel method to ship
3. Go for a swim, I guess.

**Expected behavior**
Probably spawn somewhere on the ship.

**Screenshots**
https://imgur.com/xnjtkYs

**Additional context**
Here's my save file which has the ship in question: https://drive.google.com/open?id=1iNx9nH3uw08c76Oen8r_-n1grZB0NEPA

**Comment by petchema** [comment]
This is already fixed in dev version
https://forums.dfworkshop.net/viewtopic.php?f=28&t=2521
