### ISSUE TITLE
Cannot Nagigate to Game Files Directory on Linux

### ISSUE THREAD

**Issue by BlackJar72** [Interkarma/daggerfall-unity#1507]
**Describe the bug**
When the game is launched in Linux the screen for navigating to the game files folder does not allow navigation to sub-folders, nor does it allow for text to by typed (or pasted) into the path field.  As a result, it is not possible to access the folder, making it impossible to actually start the game.

Bonus:  The arrow must be lower than the file/folder even for those default that are offered in the left-hand bar.

**To Reproduce**
1. place the game files folder inside the Daggerfall game folder, and place these in a reasonable place.  (I did this on Linux Mint 17.1 with KDE.)
2. Navigate to the game folder and click on DaggerfallUnity.x86_64 or DaggerfallUnity.x86
3. Try to navigate to the game files folder (for me this was _/home/jared/bin/Games/daggerfall/DaggerfallGameFiles_).
4. You will not be able to navigate to sub-folders below the few it guesses badly.

**Expected behavior**
I expect to be able to navigate to sub-folders until I reach the game files folder.

**Screenshots**

**Desktop (please complete the following information):**
Linux Mint 17.1; kernel 3.13.0-144-generic
KDE 4.13.2 desktop
Intel 3770K processor

**Additional context**

**Comment by petchema** [comment]
I navigate subfolders by double-clicking on names in the right panel just fine

**Comment by BlackJar72** [comment]
OK, that works -- what I'd expect (differs between parts of the same gui, and from the desktop), but it does work.  Thanks.
