### ISSUE TITLE
Store CurrentLevelUpSkillSum inside save data

### ISSUE THREAD

**Issue by TheLacus** [Interkarma/daggerfall-unity#1511]
`PlayerEntity.CurrentLevelUpSkillSum` is calculated with `PlayerEntity.SetCurrentLevelUpSkillSum()` in the following occasions:

- Save is loaded
- A new character is created
- From `PlayerEntity.RaiseSkills()`
- If a classic save is loaded

I'd like to ask if we can avoid the first point (when save is loaded) by storing the value directly with the save data, much like is already happening with `PlayerEntity.StartingLevelUpSkillSum` (`PlayerData_v1.playerEntity.startingLevelUpSkillSum`).

The main reason for this request is that i have a level bar in the loading screen mod but it only works correctly in game (ie. a fast travel) and not when the save is first loaded. I could fix it by accessing current and starting skill sums from save data but i only have the latter right now.

**Comment by Interkarma** [comment]
I'm happy for this change to be madr, and can't think of any issues that might be caused by this.

**Comment by TheLacus** [comment]
Thanks! I'll push a commit then.
