### ISSUE TITLE
Quest - The Emperor's Courier - Assassins Trigger Regardless

### ISSUE THREAD

**Issue by Burin077** [Interkarma/daggerfall-unity#1527]
**Describe the bug**
When accepting the quest "The Emperor's Courier" which can trigger Nightblades to attack you periodically if you talk to Abuk-i afterwards, the Nightblades trigger regardless if you have talked to Abuk-i after getting the quest or not. 

**To Reproduce**
1: Go to Mynisera in Castle Daggerfall, and accept her quest. (You must be level 5 to accept this quest, and must have completed Cyndassa's quest beforehand. Further, you will trigger the guards to attack you in Castle Daggerfall; this for some reason can not be helped, but has been this way since Classic Daggerfall.) (Do not speak with Abuk-i to trigger the Assassination attempts.)
2: Travel to the target of the quest (It is randomly generated) to meet the next contact of the quest. (Before you meet or after you meet the next contact, allow some time to pass by Loitering or staying in a Tavern.)
3: In time, you will end up having "Enemies Nearby..." even in Town or a Tavern, which will be a Nightblade sent by Abuk-i, complete with a letter requesting your murder. The Nightblades will spawn periodically until the quest is completed.

**Expected behavior**
The Nightblades should only be spawning on you if you talked with Abuk-i to confirm that you are looking into the letter. If you have not spoken with Abuk-i in regards to this quest, Abuk-i shouldn't even know of your meddling in the letter beyond what was told to you already.

**Screenshots**
(I can't really generate a screenshot of the issue at hand, but here's the letter on each of the Assassins/Nightblades for reference.)
![DagUnityBug4](https://user-images.githubusercontent.com/54295726/65561007-8541f180-df06-11e9-8e00-d9e13682c744.PNG)

**Desktop (please complete the following information):**
OS: Windows 10 Home Edition
Version/Build: 10.0.17763

**Additional context**
I suspect talking and finishing Abuk-i's quests beforehand might have triggered this, but I am not sure how the order of operations beyond that would have had Nightblades targeting my character when I hadn't even talked to her.

**Comment by JayH2971** [comment]
Yes, I can see how this could happen. I'll change the quest code to prevent that until you've accepted Mynisera's order.
