### ISSUE TITLE
error CS1061: Type `TMPro.TMP_FontAsset' does not contain a definition for

### ISSUE THREAD

**Issue by MarcWainwright** [Interkarma/daggerfall-unity#1529]
I downloaded the Unity 2018 version to run the package, but before i can even hit play, i come across, this error:
Assets/Scripts/Game/UserInterface/DaggerfallFont.cs(479,41): error CS1061: Type `TMPro.TMP_FontAsset' does not contain a definition for `characterDictionary' and no extension method `characterDictionary' of type `TMPro.TMP_FontAsset' could be found. Are you missing an assembly reference?

**Comment by JayH2971** [comment]
Are you using 2018.2.21? Other versions won't work.

**Comment by Interkarma** [comment]
As Jay says, you'll need to be using Unity 2018.2.21f1 specifically.

TextMeshPro is part of Unity itself, not DFU. Use your Package Manager to install it, and check that you have version 1.3 selected (latest as of Unity 2018.2.21f1.

Good luck! :)
