### ISSUE TITLE
Add support for macros in TEMPLATE

### ISSUE THREAD

**Issue by TheLacus** [Interkarma/daggerfall-unity#1531]
The original compiler written by Tipton documented the support for text replacement macros inside quest files. This is currently not implemented in Daggerfall Unity so i'd like to discuss about it and work on this feature. The reasons to use macros are to reuse code, split quests in modular pieces and create and abstraction over a long and intimidating list of tasks.

In my opinion the following are a few points that we should follow:

- Use the original syntax if possible, or at least be consistent with TEMPLATE.
- Text replacement only: macros don't exist anymore after a quest is parsed. This should allow a simple implementation and very low chance of regressions.
- A macro should be usable multiple times in a single quest.

As an example, the following snippet is copy pasted in almost every quest where you have to complete an action and then return to quest giver.

```txt
_qgclicked_ task:
    clicked npc _qgiver_

_clearclick_ task:
    when _qgclicked_ and not _slain_
    clear _qgclicked_ _clearclick_

_pcreward_ task:
    when _qgclicked_ and _slain_
    give pc nothing
    end quest
```

This pattern could be simplified with a new action (i.e. `clicked npc _person_ when _task_`) but here i want to show how the same behaviour can be achieved with a macro without any addition to quest engine (beside macro support itself):

```txt
macro ClickedNpc &person when &condition

    variable _$_

    _$.clicked_ task:
        clicked npc &person

    _$.clearclick_ task:
        when _$.clicked_ and not &condition
        clear _$.clicked_ _$.clearclick_

    _$.end_ task:
        when _$.clicked_ and &condition
        setvar _$_

end macro
```

The macro can be imported and used with `macro $: ClickedNpc &person when &condition`. The identifier `$` is important because it allows to insert a macro multiple times inside a quest using different prefixes for macro's tasks.

```txt
macro qgiverSatisfied: ClickedNpc _qgiver_ when _slain_

_pcreward_ task:
    when _qgiverSatisfied_
    give pc nothing
    end quest
```

Another example from one of Jay's quests where a "private" macro could be useful:

```txt
_begin_ task:
    pick one of _g01_ _go2_ _go3_

_check1_ task:
    when skill Etiquette is at least 20

_check2_ task:
    when skill Etiquette is at least 25

_check3_ task:
    when skill Etiquette is at least 30

variable _go1_
variable _go2_
variable _go3_
_c1_ task:
    when _check1_ and _go1_
    start task _victory_

_c2_ task:
    when _check2_ and _go2_
    start task _victory_

_c3_ task:
    when _check3_ and _go3_
    start task _victory_
```

```txt
-- If inserted variable is running, sets the task _victory_ when the given etiquette value is satisfied.
-- param skillValue - The required amount of Etiquette skill.
macro NeedEtiquette &skillValue
    variable _$_

    _$.check_ task:
        when skill Etiquette is at least &skillValue

    _$.victory_ task:
        when _$.check_ and _$_
        start task _victory_
end macro

macro checkLowEtiquette: NeedEtiquette 20
macro checkMediumEtiquette: NeedEtiquette 25
macro checkHighEtiquette: NeedEtiquette 30

_begin_ task:
    pick one of _checkLowEtiquette_ _checkMediumEtiquette_ _checkHighEtiquette_

```

**Comment by ajrb** [comment]
This would definitely be very nice to have, but I'm guessing a fair amount of work would be involved.

**Comment by TheLacus** [comment]
I started working on a prototype [in a branch](https://github.com/TheLacus/daggerfall-unity/tree/macro) a few weeks ago. It doesn't have a high priority but is shaping up :)

**Comment by TheLacus** [comment]
> The reasons to use macros are to reuse code, split quests in modular pieces and create and abstraction over a long and intimidating list of tasks.

I'm closing this, at least for now. I'm investigating different ideas on this topic.
