### ISSUE TITLE
Action doors can't be injected by mods

### ISSUE THREAD

**Issue by TheLacus** [Interkarma/daggerfall-unity#1534]
It is currently not possible to inject custom models for action doors used inside buildings and dungeons. See [DaggerfallInterior.AddActionDoors()](https://github.com/Interkarma/daggerfall-unity/blob/55359903586968b0aa0f1cc438baf53b4b2c5263/Assets/Scripts/Internal/DaggerfallInterior.cs#L935) and [RDBLayout.AddActionDoor()](https://github.com/Interkarma/daggerfall-unity/blob/1fbd1d43e3fd68bd0995b6c7ed6da2608b8dc8f8/Assets/Scripts/Utility/RDBLayout.cs#L1108).

**Comment by ajrb** [comment]
Possibly related is the fact that new dungeon models cannot be used for the entrance/exit as there's no way to define a static door for them.

**Comment by TheLacus** [comment]
> Possibly related is the fact that new dungeon models cannot be used for the entrance/exit as there's no way to define a static door for them.

It's possible to replace original models, i'm doing it [hee](https://forums.dfworkshop.net/viewtopic.php?p=33185#p33185) (although Kow has some issue making new mods for some reason).

New doors for buildings can use [CustomDoor.cs](https://github.com/Interkarma/daggerfall-unity/blob/master/Assets/Scripts/Utility/AssetInjection/Components/CustomDoor.cs), it should be possible to allow them to be used for dungeons too.

**Comment by ajrb** [comment]
Okay, thanks - I was not aware of that class. I'll change my documentation accordingly.
