### ISSUE TITLE
Console command to add all inventory items

### ISSUE THREAD

**Issue by TheLacus** [Interkarma/daggerfall-unity#1543]
Mod authors have requested the ability to add all weapons and paperdoll items to inventory for testing. This feature request is open to everyone, including new contributors.

Console commands are defined at https://github.com/Interkarma/daggerfall-unity/blob/master/Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs. See `AddWeapon` for an example of how to add items to inventory.

If nobody is interested I'll eventually do it myself.

**Comment by ajrb** [comment]
This is done and released in 0.10.8
