### ISSUE TITLE
Fire Daedra and Fire Atronach don't emit light around them

### ISSUE THREAD

**Issue by HybOj** [Interkarma/daggerfall-unity#1544]
After I enquired this feature to be added on the forums, I was told that this is actually a feature of vanilla Daggerfall which is missing the the DFU.  It would be really great to have these mobs emit light around them in DFU as well. 

Im not sure if any other mobs should have this property, maybe frost daedra as well?

Ive made these mobs emissive in the DREAM mod, but thats not really it.

![fire](https://user-images.githubusercontent.com/23343253/66001700-57c6ec00-e4a2-11e9-9fb5-f68d93a8b2a6.jpg)

**Comment by HybOj** [comment]
I checked some old daggerfall videos and the rumor of this being a feature in the original Daggerfall seems to be false. If someone with working Daggerfall can test it it would be great. Sorry.

**Comment by JayH2971** [comment]
No rumor at all: https://imgur.com/a/d5UjZMc

Fire Daedra emit a stronger light than Frost Daedra, I think. Daggerfall has a hard time displaying light on textures. The question is whether it applies to Fire Atronachs, which I doubt.

**Comment by HybOj** [comment]
Thanks for proof JayH. So the case stays valid. And it should be extended to Fire Atronach as well IMO.

**Comment by petchema** [comment]
Fire Atronach could glow orange or reddish from lava, and Fire Daedra brighter yellow since they'er actually in flames...

**Comment by petchema** [comment]
I gave it a try, but I don't know enough about Unity3D to make it work perfectly...
For one I assume I should have used prefabs
![fire-daedra-light-attempt](https://user-images.githubusercontent.com/1211431/66275112-b6ff7480-e885-11e9-8df8-258f8c0edd0e.jpg)
https://github.com/Interkarma/daggerfall-unity/compare/master...petchema:enemies-light-effects

**Comment by HybOj** [comment]
Agreed on the distinct colors of Atronach and Fire Daedra. If this will be working, I think slight dark blue glow of Frost Daedra will not hurt anything. No idea why the light is so strong on the image, but its getting there :)

**Comment by petchema** [comment]
Didn't manage to modify the light intensity. Just goes to show I don't know what I'm doing :D

**Comment by petchema** [comment]
Getting better...
I don't get lighting effects when using "cm" command, I wonder if that means I'm adding effects in the wrong place
![better enemies lighting](https://user-images.githubusercontent.com/1211431/66524237-28dbf600-eaf2-11e9-9a82-a22cb4bbe332.jpg)

**Comment by HybOj** [comment]
This will be epic, Im sorry I cant help with implementation, but I believe in You and the team :)
