### ISSUE TITLE
Enhance request. Inventory filter

### ISSUE THREAD

**Issue by AsesinoBlade** [Interkarma/daggerfall-unity#1546]
Hi all, in a forked copy, I created a filter for the inventory window.  The advantage is that you can filter down your list without needing to create extra tabs.  You can type steel armor and only see armor made of steel, or ebony dagger to find that dagger.  
After using it for a few days, I must say, it is very useful.
My code is at [https://github.com/AsesinoBlade/daggerfall-unity](url).  I only changed inventory and trade window scripts.  Please take a look and let me know if it is something that you would consider an addition to core.

I created a discussion thread at [https://forums.dfworkshop.net/viewtopic.php?f=23&t=2796](url), where you can see a screenshot; it also provides more details of the functionality of the filter. 

Thanks all
A

**Comment by df-ferital** [comment]
I think the best to let us review your code changes would be to submit a PR. Then we could clearly see the purpose of your enhacement and quickly give you some feedback.

**Comment by AsesinoBlade** [comment]
submitting a pull request now.  thank you for your time!
a

**Comment by AsesinoBlade** [comment]
Created pull request #1547.  Thank you for your help.
I will close this thread.
thanks
a
