### ISSUE TITLE
MOD - "Im At" - Map regions red overlay replacement not working

### ISSUE THREAD

**Issue by HybOj** [Interkarma/daggerfall-unity#1552]
Ive created a test Daggerfall map overlay which shows when you click "IM AT" at the region map. 

But it does not work. I placed it in the IMG folder under streaming assets/textures. It still displays the old red 320x200 blinking overlay...

Here is the file so you can try it as well.

Thank you!

https://ufile.io/kdsnrkv3

Expected behavior:
When you click on the "Im at" at the main regional map, the region you are at should highlight with HD overlay instead of the old 320x200 red one.

**Comment by TheLacus** [comment]
I assume this is on version 0.10.7.

When you click on **New Issue** a template named  _Bug report Create a report to help us improve_ is prompted. Please follow it next time so all bug reports follow a standard pattern :)

**Comment by HybOj** [comment]
Hi, yes this is the latest released version 0.10.7
Sry I will try better next time :)

**Comment by TheLacus** [comment]
I confirm this is a regression due to recent improvements to travel window.

In any case, please note that overlays must be based on image TRAV0I00.IMG; the texture you provided is arbitrary cut around the Daggerfall region, which means it would fill the entire screen.

**Comment by HybOj** [comment]
Got it, thanks for info. I hope we can solve the issues with paperdoll systems as well, is there anything I can do?

**Comment by Interkarma** [comment]
Working on fixes for this now so it works as intended.

Each replacement region overlay is based on the 320x160 interior part of TRAV0I00.IMG (so must exclude top and bottom bars). Here's an example and good starting point.

![320x160-interior](https://user-images.githubusercontent.com/10426244/115944725-ca6f4080-a4fa-11eb-8248-c96a3e2df9db.png)

You can upscale this to higher resolutions - e.g. 1600x800 is a nice 5x integer scale. Then paint the region overlay in another layer and save it out. Here's an example for Daggerfall region that I painted quickly.

![TRAV0I00 IMG-Daggerfall](https://user-images.githubusercontent.com/10426244/115944745-00142980-a4fb-11eb-9ef1-034f82dc5f6a.png)

I saved this file into StreamingAssets/Textures/Img as "TRAV0I00.IMG-Daggerfall.png". With the upcoming fixes, this now displays properly in travel map.

![image](https://user-images.githubusercontent.com/10426244/115944788-56816800-a4fb-11eb-82a7-484987bee3fa.png)

The replacement image doesn't have to be red either. You can paint it however you like, and even use transparency. Super quick example with a rough purple outline. My drawing isn't the greatest, but you get the idea. :)

![image](https://user-images.githubusercontent.com/10426244/115944953-71a0a780-a4fc-11eb-815e-887b979dad01.png)

I'll post fixes for this shortly and close issue.
