### ISSUE TITLE
MOD - Some faces are not being replaced in the paperdoll

### ISSUE THREAD

**Issue by HybOj** [Interkarma/daggerfall-unity#1564]
**Describe the bug**
Some faces are not being replaced in the paperdoll. For example the face FACE012I0.CIF_2-0
but I think there might be more?

**To Reproduce** - this is the same save and face files as in previous report
Load the included save https://ufile.io/xa9jk9yl
Add the faces files (2mb) to textures/CifRci https://ufile.io/8wab7vz2
Open the inventory

**Expected behavior**
Face gets replaced with the provided HD file

**Screenshots**
![face inv](https://user-images.githubusercontent.com/23343253/66520766-1958af00-eaea-11e9-9275-b3a869d9f7b4.jpg)

**Desktop (please complete the following information):**
Windows 10 x64, DFU 0.10.7

**Comment by TheLacus** [comment]
Texture used in the save provided is `FACE12I0.CIF_2-0.png`, which is missing. There is a texture named `FACE012I0.CIF_2-0.png` instead.
