### ISSUE TITLE
Can't exit Daggerfall Castle after teleporting inside

### ISSUE THREAD

**Issue by df-ferital** [Interkarma/daggerfall-unity#1584]
**Describe the bug**
This is a blocking issue: when teleporting inside Daggerfall Castle using a Teleport spell (either Recall or a custom made one), throne room entrance doors remain closed, so it is impossible to exit the castle. In classic, they open immediately, like after saying yes to the question from the guard at the entrance.

**To Reproduce**
1. Go to Daggerfall Castle and enter the throne room
2. Set an anchor using the Teleport spell
3. Exit the castle
4. Teleport to the throne room

**Expected behavior**
The doors should open, but they remain closed and can't be bashed as the lock is magically held.

**Comment by petchema** [comment]
You can talk to the guard thru a crack of the door... ;)
But yes, that's not very satisfactory

**Comment by ajrb** [comment]
How is this handled in classic?

**Comment by df-ferital** [comment]
I don't know. I'll try to reverse engineer this one as that wouldn't surprise me if there was be some special hack in the code to handle this as there are already such tweaks for other things.

**Comment by petchema** [comment]
Well, in classic it's handled exactly the same. They're large cracks on each side of the door, so you can talk to the guard thru the left one.
![door gap](https://user-images.githubusercontent.com/1211431/71451024-e4194000-276d-11ea-9a94-14e88e45a5cc.jpg)
![door dialog](https://user-images.githubusercontent.com/1211431/71451028-f0050200-276d-11ea-8ff5-bdbf495fc560.jpg)

**Comment by jgweiss01** [comment]
If there's not any reason why you should be locked in the castle, what if the door activation could be "double sided" where you can't open it from one side but can open it from the other? Adding this feature could also add potential maze/puzzle functionality for modders too

**Comment by petchema** [comment]
> what if the door activation could be "double sided" where you can't open it from one side but can open it from the other?
Well, that could be useful in other cases too, like when you're teleported at a quest location, below a trapdoor. However, there's currently no way to activate an object differently depending on side, or depending on direction (the latter being probably easier to implement); So it would both need to be implemented, and then specific objects tweaked to use that new feature...

**Comment by EndlessVoid1** [comment]
Perhaps an implementation could be some kind of invisible object on the inner side of the door which could be separate from the actual door that only was effective based on some type of test or check when teleporting. I'm unsure how the teleportation is implemented or how loading precisely works in daggerfall or daggerfall unity so I'm unsure when that code could actually viably execute to do said test or check. 

And maybe it could check to see if you have entered by talking to the guard? And if not then, allow the invisible object to unlock the door from the inside? That probably isn't a very general fix, however. So, something more general like direction probably would be the way to go and could even be more simple to do than what I'm proposing. 

I would start doing work on this but I need way more information about a couple systems, so, I'll probably need to dig through the current files and read all the scripts that have been made and see how everything is handled.

**Comment by wheybags** [comment]
An extremely simple solution could be to leave the doors permanently open after they are opened the first time.
