### ISSUE TITLE
Save Explorer throws an exception

### ISSUE THREAD

**Issue by rossipaolo** [Interkarma/daggerfall-unity#1628]
**Describe the bug**
Save Explorer utility doesn't work because an exception is thrown.

**To Reproduce**
1. Open Daggerfall Tools > Save Explorer [Beta]

**Additional context**
`DaggerfallConnect.Save.SaveGames` has a reference to `GameManager.Instance.TalkManager` which is not defined in Editor.

```
GameManager could not find GameObject with name TalkManager
UnityEngine.Debug:LogError(Object)
DaggerfallWorkshop.Game.GameManager:GetGameObjectWithName(String) (at Assets/Scripts/Game/GameManager.cs:961)
DaggerfallWorkshop.Game.GameManager:get_TalkManager() (at Assets/Scripts/Game/GameManager.cs:363)
DaggerfallConnect.Save.SaveGames:OpenSave(Int32, Boolean) (at Assets/Scripts/API/Save/SaveGames.cs:253)
DaggerfallWorkshop.SaveExplorerWindow:IsReady() (at Assets/Scripts/Editor/SaveExplorerWindow.cs:489)
DaggerfallWorkshop.SaveExplorerWindow:OnGUI() (at Assets/Scripts/Editor/SaveExplorerWindow.cs:72)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

**Comment by Interkarma** [comment]
It works OK if the DaggerfallUnityGame scene is open, but not if the DaggerfallUnityStartup scene is open. It's something we can no doubt decouple later though.
