### ISSUE TITLE
0.10.15: Ambient rumors too common

### ISSUE THREAD

**Issue by JayH2971** [Interkarma/daggerfall-unity#1650]
I'm testing C0C00Y12, which relies on a rumor to find the right culprit. It uses both anyInfo and Rumors to get to the goal.

The peasants weren't giving me the info I needed, so I went to the Spymaster. Even with him I had to ask 16 times to finally get the answer to the quest. Without the Spymaster this would be very difficult to find out, particularly since many quests don't tell you when to ask for rumors or not; you sort of stumble into them.

I propose reducing the number of ambient rumors (ie: faction feuds, new rulers, etc) to a more reasonable level to ensure quests can inject needed rumors as a solution.

**Comment by Nystul-the-Magician** [comment]
one possible "fix" would be to duplicate the needed answers to artificially increase the number of a successful answer.
Does this quest rely on talking to npcs - is it the only way to solve this quest or are there alternative ways?

**Comment by JayH2971** [comment]
There really is no other way than rumors. The quest requires you to travel to a different town to find a building where a thief lives, and there are no other hints.

**Comment by Interkarma** [comment]
Maybe quest rumours can just be weighted higher so they appear more often. Will see what I can do along these lines.

**Comment by Nystul-the-Magician** [comment]
btw, the spymaster does help in this case as well ;)

**Comment by Interkarma** [comment]
I believe this is now resolved thanks to #2085. Starting quest C0C00Y12 and asking around town where quest was initiated results in relevant rumour being deployed quickly and consistently. After completing quest, ambient rumours are then deployed as normal.
