### ISSUE TITLE
Registration of UI Windows by mods is in reverse order

### ISSUE THREAD

**Issue by ajrb** [Interkarma/daggerfall-unity#1668]
**Describe the bug**
UI Window override registration allows mods later in load order to have their window take precedance over earlier mods. This is the opposite behaviour to that intended by @TheLacus and teh other mod systems.

This is a reminder so I don't forget to fix it.

**Comment by TheLacus** [comment]
Did you mean the other way around? Load order is the same as Bethesda games, what comes after overrides content loaded before it.

There are some games with mod support that do the opposite, but i thought Skyrim style would be the less confusing choice for most people.

**Comment by ajrb** [comment]
Well that's what I originally expected that it would do, but I was under the impression that in DFU mod system was based on the higher the mod is in the list (i.e. loaded first) that its changes take precedence over anything lower.

Sorry, I am not familiar with Skyrim style having never really added mods to that game beyond a UI mod so it was actually playable on a PC. I think that I may have got this all mixed up in a conversation on discord before xmas about this , and then when I saw that conversation yesterday I created this as I'd been convinced that I'd got it the wrong way around for UI windows.

Glad I raised this issue rather than just fixing it then, if its just me getting all confused. I will check all of the mod registration stuff I have added is consistent and then close this.

**Comment by ajrb** [comment]
Okay so the following registration methods don't follow the convention. They all return true if the registration is successful and false if the thing is already registered by another mod. 

**GuildManager.RegisterCustomGuild()** - I think this could stay like this, as two mods both registering guild implementations for the same guild group is never going to work. In my Archs mod it throws an exception if this returns false saying the guild group is already in use.

**Services.RegisterGuildService()**
**FactionFile.RegisterCustomFaction()** - Both connected with guilds and maybe should stay as non-overriding like register guild?
 
**QuestListsManager.RegisterQuestList()** - Again, two mods should not be using the same quest list name, so if this returns false then throw exception and abort mod setup.

**EntityEffectBroker.RegisterEffectTemplate()** - This one is actually Interkarma's and it allows the registering mod to specify whether to override or not.

**PlayerActivate.RegisterModelActivation()** - Should I change this to simply overwrite any previous registration? Could even return any existing registered delegate so mods could chain if they wished. 

**ItemHelper.RegisterItemUseHander()** - Should I change this to simply overwrite any previous registration? Probably.

@TheLacus - would like your opinion please, as lead of DFU modding features. I have created a thread on forums for people to register guild groups and faction id's etc so I think overriding is only appropriate for the last two. Not sure if the deliberate inconsistency is going to be an issue. I can make it clear in the method doc comment though.

**Comment by TheLacus** [comment]
I think the most simple option is to always override current data.

If we want to make sure that load order is always respected in any situation, we can define a standard data holder that require mods to provide data as well as an instance of the mod itsef:

```cs
public struct ModFeatureProvider<T>
{
    public Mod Mod { get; set; }
    public T FeatureData { get; set; }

    public ModFeatureProvider(Mod mod, T featureData)
    {
        Mod = mod;
        FeatureData = featureData;
    }
}
```

For example `RegisterCustomGuild(FactionFile.GuildGroups guildGroup, Type guildType)` would be changed to `RegisterCustomGuild(FactionFile.GuildGroups guildGroup, ModFeatureProvider<Type> guildType)`.

This allows us to ensure that the actual **LoadPriority**  property is followed, no matter at which time a mod try to register something (for example a mod can start on _Start_ or _Game_ event, or even registers implementations after some internal initalization).

Of course this is just an idea and i'm open to feedback.

**Comment by ajrb** [comment]
Everything is now resolved as far as I am concerned. Everything is following the override current data in load order top->bottom, with the exception of the following: 

- GuildManager.RegisterCustomGuild() 
- FactionFile.RegisterCustomFaction() 
- Services.RegisterGuildService()
- QuestListsManager.RegisterQuestList()  _(only an issue if mod authors choose identical filenames)_

My argument for not doing these is that they're fundamental data structures and so if there's a conflict here then the mods will not work together. They all return a bool indicating whether the registration worked, so mods can report errors on conflicts.

If changed to the standard override behaviour, then all kinds of bugs could arise. For example if my Archs mod loads and then another mod registers a different guild implementation for GGroup0 then the Archs mod will break badly. 

The thread for reserving id's on the forums is intended to avoid this type of conflict.
