### ISSUE TITLE
Selecting "New Character" as the start game behavior gives nullpointer to biog file

### ISSUE THREAD

**Issue by Aelthien** [Interkarma/daggerfall-unity#1676]
I assume that is because a default biog doesn't exist.

**Comment by petchema** [comment]
Works for me

- How did you install classic Daggerfall?
- What version of Daggerfall Unity have you used?
- What choices have you selected while creation the character?

**Comment by Aelthien** [comment]
> Works for me
> 
> * How did you install classic Daggerfall?
> * What version of Daggerfall Unity have you used?
> * What choices have you selected while creation the character?
> * Can you provide a game log?

This is running the project in Unity, past versions just let me choose the option and the game would work. But now do I need to make a biog before being able to run in Unity?

Readme says v0.10.x

`ullReferenceException: Object reference not set to an instance of an object
DaggerfallConnect.Arena2.BiogFile.ApplyEffects (System.Collections.Generic.List`1 effects, DaggerfallWorkshop.Game.Entity.PlayerEntity playerEntity) (at Assets/Scripts/API/BiogFile.cs:408)
DaggerfallWorkshop.Game.Utility.StartGameBehaviour.StartNewCharacter () (at Assets/Scripts/Game/Utility/StartGameBehaviour.cs:389)
DaggerfallWorkshop.Game.Utility.StartGameBehaviour.InvokeStartMethod () (at Assets/Scripts/Game/Utility/StartGameBehaviour.cs:144)
DaggerfallWorkshop.Game.Utility.StartGameBehaviour.Update () (at Assets/Scripts/Game/Utility/StartGameBehaviour.cs:117)
`

**Comment by TheLacus** [comment]
So, this happens only when running inside the Unity Editor?

**Comment by Aelthien** [comment]
> So, this happens only when running inside the Unity Editor?

Yeah.
