### ISSUE TITLE
Tooltips rendered under cursor

### ISSUE THREAD

**Issue by JKingweb** [Interkarma/daggerfall-unity#1704]
**Describe the bug**
If the standard mouse cursor is replaced with something larger or of a different shape, tooltips can be obstructed by the cursor

**To Reproduce**
1. Install the DREAM mod HUD & Menu component
2. Hover over an item in your inventory

**Expected behavior**
The tooltip should should be rendered at a position which does not overlap the cursor.

**Screenshots**
I would provide a screenshot, but the correct cursor is not rendered in them. Suffice to say at least the first letter of any item name is not visible.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 0.10.19

**Comment by TheLacus** [comment]
It's not an issue with fullscreen:
![photo_2020-03-20_23-16-02](https://user-images.githubusercontent.com/24359151/77210260-d66f1e80-6b00-11ea-8aa3-b8f574b79d87.jpg)

but it happens with windowed mode at low resolution:
![photo_2020-03-20_23-15-16](https://user-images.githubusercontent.com/24359151/77210220-b8a1b980-6b00-11ea-9aa5-443d13441a0e.jpg)

even with default cursor:
![photo_2020-03-20_23-13-44](https://user-images.githubusercontent.com/24359151/77210163-91e38300-6b00-11ea-86cf-a6c0e9e4513c.jpg)

**Comment by TheLacus** [comment]
Solved by #1837.
