### ISSUE TITLE
Stuck in coffin

### ISSUE THREAD

**Issue by df-ferital** [Interkarma/daggerfall-unity#1736]
**Describe the bug**
There is a well known opened coffin where you can get stuck without any option to get out.

This is not a very important issue but it could be annoying if you're in a dungeon and didn't save for quite some time.

**To Reproduce**
Load the first provided save and walk above the coffin opening until you end in it. It may work better if you jump inside it actually.

Or load the second save where the player is already stuck.

**Desktop**
 - OS: Windows 10
 - Version 0.10.20

[SAVE111.zip](https://github.com/Interkarma/daggerfall-unity/files/4287589/SAVE111.zip)
[SAVE118.zip](https://github.com/Interkarma/daggerfall-unity/files/4287590/SAVE118.zip)

**Comment by Interkarma** [comment]
This is another case where player is sticking on a single-sided polygon (the coffin lid here). The unstick resolver can't overcome this one at the moment.

@petchema You've done some good work on this recently. Do you think any reasonable refinement to unstick handling could overcome this? I'm starting to think some handling for single-sided polygons is needed, although I don't have a good general-purpose way to address this yet during model conversion.

**Comment by petchema** [comment]
I'm still a beginner on those topics, so that's only my best guesses...
I tried turning on Queries Hit Backfaces in Physics Manager, and it changed nothing.
My intuition is that the root issue is those surfaces (both lid and sides) have no thickness, and to be precise that they have no edge faces to collide with so in specific directions the collider can just impale on them. I didn't manage to prove that by walking on the coffin edge without touching the lid though.

**Comment by Interkarma** [comment]
I think this is specific to the "fake physics" in CharacterController. I don't believe the better simulated Rigidbody physics produce this issue. CharacterController just has its own way of doing things. There are pros and cons either way though and a Rigidbody controller has its own problems.

I'm thinking we may be able to "promote" single-sided faces to be double-side during mesh conversion. I'm fairly confident that will solve the core problem and maybe even reduce the need for unstick handling entirely. Have to admit this is a just a half-baked idea right now. I haven't looked into this in any detail.

**Comment by petchema** [comment]
Can anybody confirm it's fixed by Unity 2019.4?
I could not get stuck in coffin geometry, and when reloading some save where I was (using DFU 0.10.23) I could unstick and walk away.
Not sure if they enabled enableOverlapRecovery by default, or implemented a better algorithm altogether...

**Comment by Interkarma** [comment]
Thanks for posting this, would indeed be nice if this little quirk has been resolved by upgrade. I have saves at various sticky spots, will look when I can. Cheers!

**Comment by petchema** [comment]
In fact I wonder if unstick handling could also be obsolete, because I've seen giants cross "broken cave floor" just fine...
![unstick giants](https://user-images.githubusercontent.com/1211431/87250240-cb4f4e00-c463-11ea-824d-98133310a6ec.jpg)

**Comment by petchema** [comment]
I removed unstick handling
https://github.com/Interkarma/daggerfall-unity/compare/master...petchema:remove-unstick-handling
And I could indeed walk around broken cave floors with no problem.
Also fixed misaligned stairs
https://forums.dfworkshop.net/viewtopic.php?f=31&t=2706
And misaligned ledge
https://forums.dfworkshop.net/viewtopic.php?f=31&t=3653

**Comment by Interkarma** [comment]
That's something nice to read. :) I'm very happy for unstick handling to be removed now this is no longer an issue.

**Comment by df-ferital** [comment]
Indeed, this seems to be fixed with Unity 2019.4, this is geat!
