### ISSUE TITLE
Iron Weapon Material Modifier/Negative Values in General Not Added to Final Hit Mod.

### ISSUE THREAD

**Issue by magicono43** [Interkarma/daggerfall-unity#1737]
The "GetWeaponMaterialModifier" method of DaggerfallUnityItem.cs would suggest that weapons made from iron actually have a negative hit modifier for the entity using them, that being they will be penalized for using iron in terms of their hit chances.

If you look at the formula that uses this value though, it would suggest that this currently does not get taken into consideration. If you look at Line 634-638 of FormulaHelper.cs you will notice that GetWeaponMaterialModifier is called in an if-statement and is only ran if the returned value is greater than 0. So everything that is above silver will run and add their positive hit modifier, however, any negative values returned will also pass over this, meaning that negative material mods will not be added as a penalty to the final "chanceToHitMod" variable.

I would think a simple fix for this would be to change: 
`if (weapon.GetWeaponMaterialModifier() > 0)`

to this instead: 
 `if (weapon.GetWeaponMaterialModifier() != 0)`

this way all values will pass and be added, unless they are 0 which would not be effected by a multiplication, or even just have every values pass, since adding 0 would do nothing anyway to the general chanceToHitMod value since it is all adding together anyway.

So possibly take out the if-statement entirely and just have, 
`chanceToHitMod += (weapon.GetWeaponMaterialModifier() * 10);`

**Comment by petchema** [comment]
How does classic Daggerfall behave?

**Comment by magicono43** [comment]
Not sure, just know that it supposedly gives a negative hit value from this source: https://en.uesp.net/wiki/Daggerfall:Weapons

**Comment by magicono43** [comment]
If you look at line 758-762 of Formulahelper.cs, the damage modifier for a weapon material does get applied, whether it be positive or negative.

            'damage += weapon.GetWeaponMaterialModifier();
            if (damage < 1)
                damage = 0;`

So I have to figure this is supposed to work the same way.

**Comment by Interkarma** [comment]
I think this one has already been addressed in a recent refactor. The new formula CalculateWeaponToHit() now just returns `weapon.GetWeaponMaterialModifier() * 10;` which is added straight to chanceToHitMod.

@ajrb Are you also happy that you've fixed this one already?

**Comment by magicono43** [comment]
Roger that, thanks for the update on it!

**Comment by ajrb** [comment]
yeah noticed this and fixed it as I was working on the code
