### ISSUE TITLE
Imp (archive 256) - Emissive maps bugged

### ISSUE THREAD

**Issue by HybOj** [Interkarma/daggerfall-unity#1758]
**Describe the bug**
Imp (archive 256) - when I apply "Emissive maps"  to this mob, than in-game his whole body is emissive when seen from 45degrees angle. Other frames are ok. Ive double-tested - its not because my emission maps are faulty at those frames.

**To Reproduce**

1 - Place these frames of IMP in the "Streaming assets/textures"
new link: https://easyupload.io/tki09l

2 - Spawn Imp (cm 1) at night / disable AI in console ("tai")

3- Go around the imp and see from all sides, front 45 degrees is bad from both sides (its mirrored so it makes sense)

**Expected behavior**
Only the parts specified in the emission map should be emissive, not the whole mob
Only eyes should be glowing (and Imp attack spells)

**Screenshots**
![Untitled-1](https://user-images.githubusercontent.com/23343253/77191103-bcbae080-6ada-11ea-91ec-d7e19155a013.jpg)

**Desktop (please complete the following information):**
 - Win 10 x64
 - Version [e.g. 0.10.1] 0.10.21

**Comment by TheLacus** [comment]
Link doesn't work.

**Comment by HybOj** [comment]
Sorry about that, new link here
https://easyupload.io/tki09l

**Comment by petchema** [comment]
You have some emission maps named *_Emission 1.png

**Comment by HybOj** [comment]
Thanks Pierre, such a silly issue, was too tired :)

so 21. 3. 2020 v 15:44 odesílatel TheLacus <notifications@github.com>
napsal:
