### ISSUE TITLE
Console cannot be opened when playing with QWERTZ keyboard layout

### ISSUE THREAD

**Issue by jotoho** [Interkarma/daggerfall-unity#1776]
**Describe the bug**
I use a german keyboard at my computer so I have set my computer to use the QWERTZ keyboard layout. Normally this shouldn't be a problem but I have noticed that I am unable to open the console with either the key used to open it in other Bethesda games (Morrowind, OpenMW, Oblivion, Skyrim -- same position as tilde on QWERTY) or the button that is labelled with the tilde symbol, however the QWERTZ version of the key has tilde as a side function accessed by pressing "CTRL ALT +" and not as the main symbol.

Switching keyboard layout in KDE system settings to QWERTY allows me to use the console normally by pressing the button where tilde would be, however it is annoying to have to switch between layouts regularly and I do not plan to buy an English keyboard.

**To Reproduce**
1. Make sure that keyboard layout is set to the German QWERTZ
2. Open Daggerfall Unity
3. Try to open the console, fail
4. Change keyboard layout to QWERTY
5. Try to open the console, succeed with button between TAB and 1

**Expected behavior**
For the console to open when pressing the button where tilde would be on QWERTY (like other bethesda titles) regardless of keyboard layouts OR being able to rebind the key in Daggerfall Unity Settings

**Desktop (please complete the following information):**
 - OS: Manjaro Linux 19.0.2 KDE "Kyria" (Repositorybranch unstable, all packages up-to-date)
 - Version Alpha 0.10.21

**Comment by jefetienne** [comment]
This issue will actually be fixed in #1774 where you will be able to rebind the console key to any button you want.

**Comment by jotoho** [comment]
That would be great, thanks. I only looked at the other issues and didn't see that pull request.
Feel free to close this issue now or once that advanced controls menu is merged, your choice.

**Comment by jotoho** [comment]
The pull request above has been merged. Closing this issue...
