### ISSUE TITLE
Replacement loot 3D models rotate according to player direction

### ISSUE THREAD

**Issue by petchema** [Interkarma/daggerfall-unity#1802]
**Describe the bug**
Loot replacement 3d models, can rotate to match player direction, like the billboard loot they replace did

**To Reproduce**
1. Install Handpainted models mod
2. Enter some dungeon
3. Find some modded loot pile
4. Rotate around it and see it always presenting the same side to the player

**Expected behavior**
Stay in the same direction vs the world/dungeon

**Screenshots**
![loot1](https://user-images.githubusercontent.com/1211431/80548374-14424b00-89bb-11ea-81a9-12bbf7f63612.jpg)
![loot2](https://user-images.githubusercontent.com/1211431/80548387-1dcbb300-89bb-11ea-865b-0940c2263459.jpg)

**Desktop (please complete the following information):**
 - Personally tested with Linux, but experienced by others on Windows, at least
 - Tested with 0.10.22, Handpainted models 1.83c (latest)

**Additional context**
Problem seem to happen in MeshReplacement.SwapCustomFlatGameobject, but I'm not sure how to fix it

**Comment by Interkarma** [comment]
Is this a regression? Loot piles were recently parented to their marker object so they can move with linked action objects. That change to parenting might be behind this problem with modded loot models.

**Comment by petchema** [comment]
Bingo! That's a regression
git bisect leads to 841abfd4923d6fbe7bf43f23b0243a1430cfe0b2

**Comment by TheLacus** [comment]
Thank you @petchema for finding the cause and @Interkarma for fixing it so fast!

**Comment by petchema** [comment]
Seems to work fine again in game, I'm closing the issue.
Thanks again!
