### ISSUE TITLE
Key press event leak from video player to Start menu

### ISSUE THREAD

**Issue by mamahnxarya201** [Interkarma/daggerfall-unity#1805]
**Describe the bug**
I am on first dungeon i died and when i click load saved game the game just crashed

i have no mods installed

**To Reproduce**
1. Dead
2. Click load saved game
3. Crash

**Expected behavior**
The game not crashed and i can load my saved game without exiting 

**Desktop (please complete the following information):**
 - OS: Windows 10 1903 OS Build 18362.418
- CPU : AMD A9-9425
- RAM : 4 GB
- GPU : Radeon R7 M440
- Version Alpha v0.10.22

**Comment by petchema** [comment]
I assume you saved your character just before dying?
What do you mean by crash? Freeze, return to desktop?
Does it happen if you restart the game and try to load your save? If so, can you attach an archive of the save files?
Can you attach the game logs (output.log or Player.log) after the game crashes?
(logs and saves are located in the Persistent Data Path https://forums.dfworkshop.net/viewtopic.php?f=24&t=313 )

**Comment by mamahnxarya201** [comment]
yep I saved it before I died and after died I want to load it
the game does not freeze its return to dekstop
no it's not crash when I restart the game
the crash only happens after I died 
and then the game goes to homescreen and i click load saved game and it return to my dekstop

here's my file
[output_log.txt](https://github.com/Interkarma/daggerfall-unity/files/4569033/output_log.txt)

[Saves.zip](https://github.com/Interkarma/daggerfall-unity/files/4569037/Saves.zip)

**Comment by petchema** [comment]
Thanks for the files!
Sadly I haven't seen much in the logs, they just... stop.
I can load the 3 saved games just fine, so at least they don't seem corrupted.

I can only suggest trying to remove settings.ini and see if it helps, as it has been suggested several times in the forums in similar cases (say, https://forums.dfworkshop.net/viewtopic.php?f=5&t=3020 )

**Comment by mamahnxarya201** [comment]
thanks for the guide. i delete the settings.ini but still crashes now i try to downgrade to previous version

**Comment by mamahnxarya201** [comment]
thanks for the guide. i delete the settings.ini but still crashes now i try to downgrade to previous version

**Comment by mamahnxarya201** [comment]
sorry a little bit late report
so I found out if I not skip the intro logo (i skip it by pressing "e") the game will run fine and not crash. is it normal behavior ? I still not sure if its bug or not

**Comment by petchema** [comment]
Well, releasing the "e" key in the start menu selects "Exit", so at least that part or the mystery is solved.
I'm not sure how to prevent that, if it's even worth preventing...
