### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [Interkarma/daggerfall-unity#1824]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing Daggerfall Unity on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by jefetienne** [comment]
Unfortunately, I don't believe it's possible to create Flatpaks with Unity-created applications.

**Comment by petchema** [comment]
We can't bundle classic Daggerfall files, so the benefit would be limited... 
just automate the creation of the desktop icon basically?

**Comment by jefetienne** [comment]
I know OpenMW is a Flatpak, so I think it's not a bad idea, but I just don't know how or if it's feasible to do so.

**Comment by SISheogorath** [comment]
> We can't bundle classic Daggerfall files

As someone looking into making a flatpak, how do you get the files currently? As download from a site? In this case flatpak has the concept of external data, which has exactly this purpose and is used to allow applications like Spotify that disallow redistribution to work.
