### ISSUE TITLE
0.10.??: Enemies can spawn stuck by height

### ISSUE THREAD

**Issue by JayH2971** [Interkarma/daggerfall-unity#1878]
**Describe the bug**
My wording is bad but enemies can spawn in places where they can't move due to height restrictions. Perhaps some height logic should be included?

**Screenshots**
[Twitch clip in action](https://clips.twitch.tv/BoringSuperPoxOSsloth)

**Comment by petchema** [comment]
I think this is 0.10.24?
It should be fixed in later versions, just by switching to Unity 2019.4.

**Comment by JayH2971** [comment]
He afterward added that he's using a version that's a few months old, so it isn't 0.10.24. I couldn't immediately see what version he's using.

**Comment by petchema** [comment]
In https://www.twitch.tv/videos/693358854 I see 0.10.22 in the upper right corner of the video at times
Either way, that's the switch to Unity 2019.4 that fixes several similar issues, so I really meant "is he using some version < 0.10.25?"

**Comment by Interkarma** [comment]
I believe this one should be resolved in 0.10.25+.
