### ISSUE TITLE
0.10.25: world borders have become sticky

### ISSUE THREAD

**Issue by petchema** [Interkarma/daggerfall-unity#1911]
**Describe the bug**
When trying to go past world borders, you get stuck in place and can only free yourself by mean of, say, fast travel
Tested with north, east and south borders.
tdbg shows that players goes slightly further than the border coordinate (say going south, coordinate becomes 9995, when the border is at 10000).

**To Reproduce**
1. Load game save below
2. Travel north until you hit world northern limit
3. Try to get away from the border

**Expected behavior**
Be blocked at the world border, but be able to move away from it

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 0.10.25

Tested to work with 0.10.24 compiled with Unity 2018.2.x.

**Additional context**
Game save near northern world border
[SAVE752.zip](https://github.com/Interkarma/daggerfall-unity/files/5147330/SAVE752.zip)

**Comment by Interkarma** [comment]
This is a good find. Cheers :)

**Comment by SoullessHumanoid** [comment]
Tested this in Unity editor. I never got permanently stuck to the border, but did experience visual jitter and was temporarily suspended above ground when jumping against the border. Found some possibly unsafe code:
`gameObject.transform.position = lastFramePosition;`
If somehow `lastFramePosition` is set outside the world border, it would be impossible to move. I think it would be better to clamp only the coordinate that is outside the limits (Z for northern border), making it behave similar to a wall.
I could try to implement this, after researching how world coordinates (`worldX, worldY`) correspond to player transform position.

**Comment by petchema** [comment]
Fixed in master branch
