### ISSUE TITLE
Arrows bugging on player death

### ISSUE THREAD

**Issue by DFIronman** [Interkarma/daggerfall-unity#1913]
**Describe the bug**

If there's an arrow in the air when the player dies, an error message spams the Unity console. Player logs could become huge because of it (doesn't stop unless you exit the program) - on my machine, 999 error messages in probably less than 5 seconds.

**To Reproduce**

Die with an arrow midair/possibly even die to an arrow.

**Expected behavior**

No error. Perhaps all arrows should be removed from memory on player death/game reset/load, etc. so Update() can't be called on them? Or, at least, a NaN check and Destroy() the GameObject when necessary?

**Screenshots**

![image](https://user-images.githubusercontent.com/54879668/92185810-b232a000-ee09-11ea-8cd1-0431b34c7d97.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.10.26

**Additional context**
Spell missiles don't seem to cause the issue

**Comment by Interkarma** [comment]
I've not been able to reproduce this one, even when slowing down arrows and intentionally killing player via console while several arrows are still in flight.

Searching around for this seems to indicate it might be an edge case with Unity's physics. There's nothing specifically wrong with the transform addition at line 274.

If someone can find a reliable way to reproduce in live code, I'll take another look. If not, I'll close this out later.

**Comment by ajrb** [comment]
I had this happen once, but was never able to reproduce it and dig into what was going on.

**Comment by Interkarma** [comment]
I was never able to reproduce this. It's possibly an internal physics issue resolved after updating from 2019.4.2 to 2019.4.10. I'll close this one for now.
