### ISSUE TITLE
Mantellan Crux crushing hazard

### ISSUE THREAD

**Issue by petchema** [Interkarma/daggerfall-unity#1914]
**Describe the bug**
The apparatus below can be a crushing hazard under several conditions, including some mundane ones that could be worth fixing
![Screenshot](https://user-images.githubusercontent.com/1211431/92312562-36c81e80-efc2-11ea-923e-590fe087388b.jpg)

**To Reproduce**
1. Stand in front of the apparatus, very close to it
2. Click on the left "red butterfly"
3. The lid opens and crush you on the ground

**Expected behavior**
Be pushed back?

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Linux
 - Version master (0.10.25)

[SAVE773.zip](https://github.com/Interkarma/daggerfall-unity/files/5178550/SAVE773.zip)

**Comment by Interkarma** [comment]
This is a fun one. Can think of a few ways to mitigate this. Thanks for report. :)
