### ISSUE TITLE
Game freezing up to 20s when opening the console

### ISSUE THREAD

**Issue by petchema** [Interkarma/daggerfall-unity#1915]
**Describe the bug**
When trying to openi the console, the game may freeze up to 20s before the console opens

**To Reproduce**
1. Press the key to open the console
2. Wait...
3. The console opens

It does not always happen, and when it does I noticed intense disk activity.
I guess that when console opening is fast, some caching is going on.

**Expected behavior**
Console opens in less than a second

**Desktop (please complete the following information):**
 - OS: Linux
 - Version master (0.10.25)

I don't remember this behavior happening in older versions

**Additional context**
I traced files activity, and opening the console at 12:29:00
It seems the game is busy enumerating fonts.
So the issue could be related to recent localization support changes, and also be system specific.
[daggerfall_file.strace.zip](https://github.com/Interkarma/daggerfall-unity/files/5179470/daggerfall_file.strace.zip)

**Comment by petchema** [comment]
I also had the game rarely freeze for similar amounts of time in 0.10.25 while displaying dialog box.
But I have no idea whether the issue is directly related, or something totally different.
![20s freeze](https://user-images.githubusercontent.com/1211431/92324063-5c930900-f03e-11ea-90d7-924fb6dae854.jpg)

**Comment by Interkarma** [comment]
It's not something I've experienced yet in editor or builds. Do you experience this in the editor and are you able to use the Unity Profiler to see what's happening?

The console uses Unity UI system whereas DFU uses bespoke DagUI. There aren't really any crossover points between them and seems unlikely these would be related.

I've heard of console being slow to open on Linux before, so not sure if this is just another instance of that. The fonts being enumerated in your trace aren't part of DFU, looks like something the Unity runtime is doing.

**Comment by petchema** [comment]
I think I manage to run profiling, but I've yet to understand what I'm looking at :p

**Comment by Interkarma** [comment]
That's OK. :) You do experience in editor also, though?

I'm not sure, but it really sounds like uGUI is stalling enumerating system fonts when the console opens. Systems with more fonts will stall longer than others.

Maybe there's a way to prevent this. I'm not the most experienced with uGUI, so will need to do some digging.

**Comment by jefetienne** [comment]
While I haven't had the console be that slow when opening up, I have found through the profiler that the way Daggerfall fonts get rendered is very expensive from Graphics.DrawTexture(). I think it's because each letter is drawn individually(?) via DrawClassic/SDLGlyph(). Here's a deep profile of the Setup wizard:

https://imgur.com/a/flf5sSE

You can see that Graphics.DrawTexture on is taking 2ms worth of rendering (deep profiling makes it take more time, but I think it's still proportionally expensive). Above TextLabel.Draw() is Checkbox.Draw() and if I were to open up why that one is taking 5ms, it's because there's a TextLabel inside that as well.

You can also notice this latency if you move with a joystick software cursor when you first open a book (for some reason after moving down the page bit the re-rendering significantly reduces the GUITexture.Draw() calls). The cursor gets very choppy and moves slow. Here's a shallow profile, you can see that GUITexture.Draw() is initially 7000 calls in this book:

https://imgur.com/a/UL69y3b

Last night, after finding #1931, I tried looking into rendering the fonts on a more low-level via the Unity GL library and certain methods like OnPostRender() but I didn't have any success really nor do I have much low-level graphics knowledge.

**Comment by Interkarma** [comment]
Rendering glyphs individually is quite standard, other GUI libraries will handle this in a similar way. Future optimisations aside, I consider text rendering "good enough" for our needs here.

I'm not sure if you were watching back in the early days - my original label implementation would pre-render labels to a Texture2D and use that texture for subsequent redraws unless label text changed. Fast, but has other problems with consuming lots of texture memory and doesn't play nice with variable glyph widths (e.g. localization changes) or wrapping text. The current implementation is designed to be flexible first. A few of time in a mostly static UI is a very minimal overhead.

In any case, unrelated to issue here. :) DagUI fonts are not related to the enumeration of system fonts Pango is observing on his system. The console uses uGUI and has no overlap with the Daggerfall UI.

**Comment by jefetienne** [comment]
Ah I see, that makes sense. I was also thinking about pre-rendering labels as well but now I see where the pitfalls would lie with that.

> In any case, unrelated to issue here. :) DagUI fonts are not related to the enumeration of system fonts Pango is observing on his system. The console uses uGUI and has no overlap with the Daggerfall UI.

Understood :) I was just mentioning that case in response to Pango's screenshot with the dialog box.

**Comment by petchema** [comment]
I do observe the issue in the editor indeed. I have to wait a long time between observations though, because when cached by the system opening the console becomes very fast. (I'm using an hybrid disk subsystem, classic hard drive + bcache SSD caching, which may partially explain timing discrepancies).

**Comment by haloterm** [comment]
I can confirm this issue; it was very confusing when I first stumbled upon it because I thought the console key would not work.

**Comment by petchema** [comment]
If that's Unity calling Font.GetPathsToOSFonts internally, there's probably not much we can do about it....
https://docs.unity3d.com/ScriptReference/Font.GetPathsToOSFonts.html

**Comment by petchema** [comment]
I think the issue is that the console uses the "Arial" font, leading to a system scan for the font closely matching the properties of that font family.
Switching the console to the OpenSansRegular font included in DFU may fix the problem (the console opened quickly, but because of caching effects I'm not sure the issue is definitively fixed, will have to experiment with it more).

**Comment by ajrb** [comment]
I noticed a slowdown in console when we moved to unity 2019 (I think) but it was a few seconds, never 30 for me.

**Comment by Interkarma** [comment]
I tried a simple switch to OpenSansRegular in both text components of console. Unfortunately text being entered isn't rendered correctly after this change. I think you're onto the solution however, I just need to understand why the text input field stops rendering after change. My knowledge of uGUI is a little sparse.
