### ISSUE TITLE
Player sometimes falls through ground when rapidly walking between map pixels

### ISSUE THREAD

**Issue by SoullessHumanoid** [Interkarma/daggerfall-unity#1924]
When crossing the border between map pixels, player sometimes falls through the ground.

**To Reproduce**
1. Go to border between map pixels
2. Walk back and forth repeatedly across the border
3. Player falls through the ground

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10.0, Build 17763

**Additional context**
Bug only appeared when walking on foot, not riding a horse.
Could not reproduce the bug when waiting a few seconds before crossing the border again.

**Comment by monobelisk** [comment]
Same thing happens for me when walking or running at extreme speeds. It never happened in 0.10.24, but happens very often in 0.10.25.

**Comment by Interkarma** [comment]
I can reproduce this but don't have a satisfying mitigation at this time. Thanks for report.
