### ISSUE TITLE
Weather (and maybe climate?) not updated during teleportation

### ISSUE THREAD

**Issue by petchema** [Interkarma/daggerfall-unity#1930]
**Describe the bug**
It is possible to carry snow from a snowy region to a non snowy region by teleporting back
It seems that casting teleport inside or outside buildings doesn't matter.

**To Reproduce**
1. Go to anywhere Sentinel during winter
2. Cast recall to set an anchor
3. Go to anywhere in Ykalon
4. Wait until it snows
5. Cast recall to teleport back

**Expected behavior**
Weather should be adjusted when you change places using teleportation

**Screenshots**
![2020_09_12_12_22_40](https://user-images.githubusercontent.com/1211431/92993554-cd309e80-f4f2-11ea-8da1-c25c5bab7fdd.jpg)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version master 

Gamesave in Ykalon at dusk; Problem can be repeated by waiting 'til midnight, and if it snows, recall to Sentinel
[SAVE758.zip](https://github.com/Interkarma/daggerfall-unity/files/5212526/SAVE758.zip)

**Comment by SoullessHumanoid** [comment]
I am not sure how to best fix this. If weather is always updated when teleporting, then player could instantly change weather by casting Anchor and then Teleport, forcing weather to update without changing location. Maybe only update weather when teleporting into a new climate zone or some minimum distance?

**Comment by petchema** [comment]
If you aim at consistency, currently weather only changes on day or different climate.
Since the day should not change with teleportation, I'd say only update weather if the climate zone changes...

**Comment by joshcamas** [comment]
Perhaps it would only update the weather if the new climate zone does not "support" the current weather?
