### ISSUE TITLE
0.10.25: Structs and interfaces no longer work in virtual mods

### ISSUE THREAD

**Issue by monobelisk** [Interkarma/daggerfall-unity#1938]
**Describe the bug**
Mods that have structs and/or interfaces among its loaded assets no longer work in play mode if they're loaded as virtual mods. A NullReferenceException is thrown by the file Mod.cs. On line 1015 (don't trust the screenshot, I added a few lines on my own for testing), inside the method FindModLoaders(), `foreach (MethodInfo mi in type.GetMethods())` fails because `type` is null. A Debug.Log of `type.name` reveals that all script classes get loaded, until it comes to a struct or interface (which is where `type` is null). 

Building a .dfmod file for a mod containing structs and/or interfaces and placing it in StreamingAssets/Mods works; the mod loads and runs just fine in play mode.

Structs and interfaces will work if they're changed into classes and/or abstract classes.

Bug repro mod: [StructInterfaceTest.zip](https://github.com/Interkarma/daggerfall-unity/files/5240246/StructInterfaceTest.zip)

**To Reproduce**
1. Download one of the latest DFUnity commits and load it in Unity 2019.4.2f1 (all the recent commits should have this bug).
2. Download the repro mod above and extract into Assets/Game/Mods.
3. Open the DaggerfallUnityStartup scene, enter play mode, make sure the mod is loaded and hit Play.
4. See the included code files for further info.

**Screenshots**
![dfunity-structinterface-error](https://user-images.githubusercontent.com/71452944/93495679-ac12e800-f90e-11ea-8904-acaac2601a8e.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 (64-bit)
 - Version: 0.10.25 (from commit [16e4552](https://github.com/Interkarma/daggerfall-unity/commit/16e4552357c6a8fa89adaf07fa6cdadd4eeefa86) and newer - most likely older commits as well)
- Unity version: 2019.4.2f1

**Comment by TheLacus** [comment]
Thank you for this bug report and for providing files to reproduce the issue.

This is a regression caused by #1883. Each C# file corresponds to an instance of `MonoScript`, where `MonoScript.GetClass()` is used to retrieve a class inheriting from `MonoBehaviour.` A check against null is needed to handle different situations (i.e. any C# files that doesn't include class definition).

**Comment by monobelisk** [comment]
No problem, and thanks for looking into it :)
I can confirm that the issue is resolved.
