### ISSUE TITLE
System performance extremely bad with Daggerfall in background

### ISSUE THREAD

**Issue by keenerb** [Interkarma/daggerfall-unity#1942]
Any way to decrease framerate or CPU usage, especially with Daggerfall as a background process?  I can hardly switch to a different application, rendering seems to run at 100% even with app minimized.

**Comment by petchema** [comment]
Just saw that Unity sends events when losing/receiving focus, so it should be at least possible to disable parts of the main loop when the game doesn't have the focus: 
https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnApplicationFocus.html

**Comment by Interkarma** [comment]
It's possible to disable "run in background" in player settings so that runtime will be suspended when game is minimised or otherwise loses focus.

**Comment by ajrb** [comment]
Isn't it just easier to press escape to bring up the main pause menu and the alt-tab? That should remove most of the work Unity is doing shouldn't it?

**Comment by keenerb** [comment]
That doesn't seem to help, actually.

**Comment by Interkarma** [comment]
Are you sure this is an issue with DFU and not your mods? DFU only uses around 10% CPU and <1GB RAM when in a large city.

Please use the Help & Support forums for support with individual setups.

https://forums.dfworkshop.net/

**Comment by keenerb** [comment]
The mods exacerbate the issue, but DFU with or without mods still seems to consume the same CPU and GPU resources in the foreground as it does minimized.  Whether you want to spend the time pausing the render thread (or whatever you programmers do) is up to you of course!

I managed to bring cpu/GPU usage down to acceptable levels by setting targetframerate to 30 in settings.ini

**Comment by Interkarma** [comment]
I can change this to suspend the runtime when game is minimized or loses focus. This should resolve that problem.

This was known to cause issues in older builds, which is why the setting was disabled. Now that engine has been updated to a later version, this shouldn't be an issue any longer. I'll roll this change out with 0.10.27.
