### ISSUE TITLE
Automap performance fine 1920x1080, abysmal at 3240x2160 (Surface Book 2 w/Nvidia 1060)

### ISSUE THREAD

**Issue by keenerb** [Interkarma/daggerfall-unity#1944]
Both 24 w/mods and .26 without mods have similar issues.

Performance when running in windowed high resolution is abysmal specifically for automap.  Game itself runs perfectly fine at very high resolution.

Videos:
https://streamable.com/s0eer9

https://streamable.com/qrisat

Will tinker with some settings; maybe it's texture memory issue or something...

**Comment by Interkarma** [comment]
Please use the Help & Support forums for support with individual setups.

https://forums.dfworkshop.net/
