### ISSUE TITLE
Passing-out Notification can trigger again during burial cutscene and in main menu

### ISSUE THREAD

**Issue by jotoho** [Interkarma/daggerfall-unity#1945]
When experimenting with the mods Interesting Terrain and Travel Options, I fell through the world.
After a failed attempt to get back up using the console, I eventually decided to just disable God-Mode and die from the void.

I began to lose fatigue rapidly and after a few popups about me passing out and mobs spawning, eventually got the death-by-passing-out message and died. 

When the cutscene started, I skipped it and a few moments after arriving on the scroll-screen (where you load a savegame or start a new character), the death sound played again and I got the death notification again. (See Screenshot 1)

When reproducing this using the console command "speedy 500", running off the world and disabling godmode the notification appeared on the scroll-screen again, so I decided that it is consistent enough to write a bug report.

Addendum: I also tried this again and this time, I did not skip the burial cutscene and both the sound and notification showed up during it, instead. (See Screenshot 2)

**To Reproduce**
1. Go outside
1. Execute console command "speedy 500"
1. Run until you fall out of the world (should only take a few seconds)
1. Disable Godmode with console command "tgm"
1. Die from the void
1. Skip burial cutscene (optional)
1. Wait a few seconds for sound and notification to appear again.

**Expected behavior**
Only get one death notification before the burial cutscene and the load/start screen should wait for my next action, instead of giving the same notification and sound again.

**Screenshots**
![Dead in Main Menu](https://user-images.githubusercontent.com/12120743/94366809-d3ba3b00-00da-11eb-8490-13e7642c7883.png)
![Dead in Cutscene](https://user-images.githubusercontent.com/12120743/94367246-c488bc80-00dd-11eb-864a-57e533ab4f81.png)

**System Information**
 - OS: Arch Linux (kernel 5.8.10-arch1-1)
 - DFUnity Version 0.10.26

**Comment by jotoho** [comment]
I do not think that it is relevant but here's my most recent save (just in case you need it for debugging).
[SAVE105.zip](https://github.com/Interkarma/daggerfall-unity/files/5288452/SAVE105.zip)

**Comment by EndlessVoid1** [comment]
It doesn't seem Interkarma or anyone else actively works on this project anymore. I don't know what happened exactly, but it just seems that way. I also have no idea where Interkarma went. It doesn't seem that he works on this project anymore, or at the very least he almost never checks the issues tab. I was looking to start fixing bugs but it also seems that nobody really actively creates discussion anymore for solving problems. 

Another thing: 1. You are on Linux and 2. You have an issue from a mod. When games or even engine remakes are made with modding allowed most of the time the creators don't take responsibility for the game doing weird things or breaking. Meaning, you will probably never get a response from someone like Interkarma and if you do he will probably just tell you to go ask the people who made the mod. (That's what I've seen from the Skyrim and Minecraft modding scene if you are familiar.)

Idk how many of the devs have arch linux but I doubt very many. And virtual machines can be annoying to tinker with. 

Here's what I personally think the problem could be: Perhaps the script for dying and the whole feature/system never accounted for dying from the void or at least never accounted for dying from the void in the way you did and certain things that would cause dying and reloading to be smooth work as intended - break. I would have to dig through both what the mod does and the scripts in the files that control that. 

If you know how to program or are some type of dev we could start a discussion and get this figured out. We'd probably end up having our fix stuck in limbo forever though, so don't know how good of an idea it would be to start this endeavor. We could also just do something external if you are down.

**Comment by jotoho** [comment]
@EndlessVoid1 It's true that there isn't much activity on this issue tracker but I would say Interkarma is still pretty active on this project (Primarily reviewing and merging PRs from what I can tell of from my email notifications but still). His last commit on master was only a week ago.

I think it is important to remember it is an OpenSource Project that, as far as I know, no one is paid to work on and this is a rather minor issue compared to some other things like working on mod support.

As far as my installation of Daggerfall Unity is concerned, I somewhat doubt that this issue was caused by my installed mods as there was nothing that should interfere with the death logic. (Especially for falling into the void.)

Regardless of whether it was a modding issue, due to a recent mistake during file transfer between my PC and a server at home I accidentally deleted the folder my installation of DFUnity was stored in and failed to restore the files, so I will need to set up everything from scratch anyway.

As for my Operating System, there have been no indicators so far that the issue I experienced had anything to do with it, so until proven otherwise (which may be difficult since the installation was lost) I will presume that it is a cross-platform issue. I mentioned my OS because it was requested by the issue template.

As the autumn school break begins this weekend in my home region, I may experiment if this issue still occurs with the fresh install I will have to make.

As for my programming knowledge, I know and have some experience in C, C++ and Java with a bit of Python and [ComputerCraft-Style](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked) Lua but have never learned C# and do not know this codebase, so I do not know how much help I would be in making a patch.

**Comment by jotoho** [comment]
@EndlessVoid1 Also I just saw that your github-account was only just created on the 28th and there is no other activity visible on your profile, so forgive me for being slightly suspicious.

**Comment by EndlessVoid1** [comment]
Yeah, I'm not a professional lol. I don't work as a software engineer and contribute on the side as some other people do. I'm mainly just trying to get experience by helping with projects and look through code. 

I got the basics of C# and have done scripting before so it's not that bad when I look at everything. 

I think I remembered I tried to find where death is handled but I don't remember what I found or if I even tried looking.

Clearly, it has something to do with being outside of the world. Maybe, some scripts don't work properly due to where you end are when you fall through the world. 

There's another sort of not-important type bug that hadn't been commented on in over a year before I commented. I investigated and found the quest script and according to the script the bugs should of never happened. The script was quite straight forward. Most likely the issue is somewhere else but I stopped caring as this community seems super dead and issues that aren't critical are basically swept under the rug - it seems. :/

I think it could be that sort of case where this is something that will never be looked at and you are just going to have to avoid it. 

I could try. - but like I said it simply doesn't seem worth it when the community is just so dead.

The C# language isn't that bad if you drop by the C# tutorials at the Microsoft docs. 

I probably made a general statement about how many people actually use Arch Linux. I actually have no idea generally how many people use that os for development. 

I only created this account recently because I decided to finally put the things I've been learning over the summer to use - but that is widely off topic (not like there's people who actively moderate these issues anyway lol). 

I wouldn't mind working on this together and start looking through the files. Although, ultimately to get a better take on this problem we would probably need to contact Interkarma. 

Have a great day/night!

**Comment by jotoho** [comment]
@EndlessVoid1 

I just did some more quick digging with a temporary install of DFUnity 0.10.26a that had no mods installed and have several things to note.

* When I loaded into a save on the same character I uploaded in a previous comment and went into the console (after a multiple second delay as noted in #1915) I was not able to find the same "speedy" command I recommended using in my opening post.
* After some searching in the `help`-output I instead chose to use the command `set_walkspeed 10000` to achieve a similar effect
* After some attempts and quite a bit of waiting I eventually found myself beneath the world and began to lose stamina but no creatures spawned around me to kill my character off quickly (Seems that part was modded)
* Luckily, after around half a dozen forced naps the sun went up and my vampire character died of sundamage during his naps, finally killing him off.
* The first few seconds of the burial cutscene went as expected before the bug I described earlier occured. Strangely **the bug was worse than before** and a new death message would show up roughly every 0.5 to 1 second, interrupting the cutscene multiple times before continuing on the load/create-new-character screen. It only stopped when I hit the "Exit"-Button between messages and the game terminated normally.

As I said, I have no knowledge or experience with C# or Unity. I have heard that C# and Java are very similar though and it seems that I can understand some of the code I've looked at.

My lessons on programming (mostly part of a three year school-based education in IT at a vocational college in Germany) have also been mostly limited to projects with only a few source files so I may have some trouble navigating a code base of this size.

A quick GitHub-Search for "death" [led me to this source file, which probably contains most code surrounding player death.](../blob/master/Assets/Scripts/Game/PlayerDeath.cs)

This issue is of no particular importance to me, since if I fall through the world I probably have to reload anyway. I just wanted to document it here for others who may be experiencing the same issue and to make sure the maintainer(s) are aware of this.

If you wish for me to do more testing or another opinion on some piece of code, I will see what I can do but I do not intend to learn another programming language "just" for this small issue. I also have a good understanding of Git version-control if you want some help with that.

**Comment by jotoho** [comment]
I just took another look at the source file I linked in my last comment and from my rudimentary understanding it seems that the Sound I hear is triggered in the function `PlayerEntity_OnDeath(DaggerfallEntity entity)`. As I do not see any loops in that function and the game is seemlingly paused before the sound is played, I do not think that is supposed to happen.

I would guess there either is another location in the code the death sound effect is played, the OnDeath is called multiple times or the EventHandler called at the very end of the function is responsible.

As I do not understand how Eventhandling works in Unity and System.EventHandler is apparently not defined in this codebase (Probably from C# itself or the Unity engine), I cannot say any more than that.

Also I think it's interesting that the EventHandler-call in `PlayerEntity_OnDeath` does not seem to communicate which Event it should process. Does it somehow read that from the name of its instance "OnPlayerDeath"?

**Comment by jotoho** [comment]
I think I need to correct myself. When I reproduced this issue in vanilla DFUnity, I made a screenshot of the notification appearing in the burial cutscene but forgot to upload it. 

I just noticed that the text in the notification is regarding me running out of fatigue and not strictly a "death notification".

This makes me question whether the issue could be caused by the void damage to the players stamina still being applied even though the game was paused by the death. Or perhaps my fatigue was at zero when the character died and this is still being checked while the game is paused during the cutscene and main menu.

Here's the screenshot:

![Same Issue in vanilla Daggerfall Unity](https://user-images.githubusercontent.com/12120743/96880755-d90e6980-147d-11eb-8988-28aa285f8273.png)

**Comment by Interkarma** [comment]
This popup is event driven, and in some circumstances events can be queued multiple times. I'm not able to reproduce just by running out of fatigue in the void, but I can see how this would happen if one system managed to trigger the exhaustion event several times in a row.

I'll add a check to prevent this popup firing when player is already dead, in addition to the UI stack prevention check already in place.
