### ISSUE TITLE
Can we make `CanRest()` in `DaggerfallRestWindow` virtual?

### ISSUE THREAD

**Issue by lonegamedev** [Interkarma/daggerfall-unity#1962]
Would help a lot, cause now I have to copy-paste the entire `DaggerfallRestWindow` class to extend the default `CanRest()` method.

**Comment by jefetienne** [comment]
Hey there, so there is a method for modding that can allow for a mod to prevent a player from resting without having to override anything, called RegisterPreventRestCondition. It is found in GameManager.

```summary: Registers a boolean method that prevents the player from starting or continuing to rest
'handler' - The method returning a boolean whether the player can rest
'message' - The message to be displayed
public void RegisterPreventRestCondition(Func<bool> handler, string message)
```

I believe the handler method should return true to prevent resting, false to continue resting.

**Comment by lonegamedev** [comment]
Hi, thank you for replying. 

In that case, can we have:
public getter for `currentRestMode` 
and 
'enum RestModes' public?

Cause in my case, I want to allow loitering, but prevent them from resting.

I can make a pull request if that helps.

**Comment by jefetienne** [comment]
Hey lonegamedev, sorry for the wait. I made a PR (#1965) that should help with this.

**Comment by lonegamedev** [comment]
Hey, no worries. Thank you for that. Looking forward to the merge and the release 😃

**Comment by Interkarma** [comment]
I've merge this PR now. :)
