### ISSUE TITLE
Can't talk to quest NPC

### ISSUE THREAD

**Issue by wheybags** [Interkarma/daggerfall-unity#1972]
**Describe the bug**
I can't talk to an NPC that I need to talk to to finish a quest.

**To Reproduce**
1. Load the attached save file
2. Open the quest log and scroll to the bottom. The quest there indicates I need to talk to Bedoryan Moorsmith.
3. The NPC directly in front of the player is Bedoryan Moorsmith, and attempting to talk to him does nothing.

**Expected behavior**
A quest dialog opens and the quest advances.

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 20.10)
 - Version: 0.10.27

**Additional context**
Save file: [dfu_bug_quest_cant_talk.zip](https://github.com/Interkarma/daggerfall-unity/files/5611268/dfu_bug_quest_cant_talk.zip)

**Comment by petchema** [comment]
The quest seems to be "The Ransom"
I noticed that there's no quest Jade in your inventory, but I can't tell what sequence of events led to that.
Hopefully somebody with deeper knowledge of quest system can have a look.

**Comment by Interkarma** [comment]
The main trigger here is S.02, which requires the quest jade to be in your inventory.

    _S.02_ task:
        toting _gem_ and _kidnapper_ clicked

As the quest jade isn't present, you aren't able to initiate the click. Using "getallquestitems" to add the jade allows the click to fire. As Pango says, it's hard to say what led up to this situation. As S.02 hasn't fired yet, it's unlikely to just be the dialog not showing up. Is it possible the jade was dropped/sold with "CanDropQuestItems=True"?

I'll close this issue now, as reason quest doesn't continue is apparent (quest item missing), and it's not possible to say with any confidence why quest item is gone at this stage of quest.

**Comment by wheybags** [comment]
Definitely didn't modify any ini settings, for what it's worth. As for whatever else I might have done in-game, I really can't remember unfortunately :(
