### ISSUE TITLE
Dumped Map Block json causes all doors to use model 9000

### ISSUE THREAD

**Issue by XJDHDR** [Interkarma/daggerfall-unity#1989]
**Describe the bug**
I've noticed that when you use a Map Block Record override, all of the doors placed by that block will use model 9000 regardless of what the door models being used was before.

**To Reproduce**
1. Load the attached save. Note that all the ground floor doors use models 9003 or 9004.
2. Open the console and type "DumpBlock MAGEBA00.RMB". "DumpBuilding" while inside will also work. Quit the game.
3. Drop the json file created above into the WorldData folder.
4. Start the game and load the save again.
5. You will now see that all of the ground floor doors are using model 9000.

**Screenshots**
Here are two screenshots showing two of the doors without the dumped MBR loaded:
![Good door 1](https://user-images.githubusercontent.com/7355441/104258209-e454bc80-54e3-11eb-84d5-5f1509013702.jpg)
![Good door 2](https://user-images.githubusercontent.com/7355441/104258211-e585e980-54e3-11eb-8d5b-883840c98a3f.jpg)

Here are those same doors after dropping that json into the WorldData folder:
![Bad door 1](https://user-images.githubusercontent.com/7355441/104258263-064e3f00-54e4-11eb-89e4-62c32f6ff071.jpg)
![Bad door 2](https://user-images.githubusercontent.com/7355441/104258265-06e6d580-54e4-11eb-9c49-dd59372b38ae.jpg)

**Desktop:**
 - OS: Windows 10 Pro x64
 - Version: 0.11.0

[Save.zip](https://github.com/Interkarma/daggerfall-unity/files/5799254/Save.zip)

**Comment by XJDHDR** [comment]
I've also found the solution. Changing the DoorModelIndex variable in DFBlocks.cs to public then dumping the block once again will have the new block overrides preserve the original door model choices.

Here are the same two doors as above with the block override installed and the fix applied:
![Fixed door 1](https://user-images.githubusercontent.com/7355441/104259472-58905f80-54e6-11eb-9e9d-4b50ef8aeb1f.jpg)
![Fixed door 2](https://user-images.githubusercontent.com/7355441/104259475-59c18c80-54e6-11eb-8742-76708f5633b4.jpg)

**Comment by df-ferital** [comment]
Good catch and fix, however you created the PR on your own fork instead of DFU's main one.

**Comment by XJDHDR** [comment]
Oops, haven't done this before. Attempt number 2.

**Comment by XJDHDR** [comment]
I've noticed that my pull request only solves this problem in the DumpBlock command. The DumpBuilding command still has the same problem and I don't know what needs to be done to fix this. On a side note, I've also noticed that the DumpBuilding command saves BuildingType as a number verses DumpBlock which saves it as a word.

**Comment by ajrb** [comment]
It solves it for both based on my testing. Regarding the building type, you're comparing the dumped data with the building metadata for specific buildings. See BuildingReplacementData struct for more.
