### ISSUE TITLE
Various issues in Runtime Materials

### ISSUE THREAD

**Issue by XJDHDR** [Interkarma/daggerfall-unity#1990]
Pango and I have found some problems in Runtime Materials. You can reproduce all of them using this mod:
[UBLaMF.zip](https://github.com/Interkarma/daggerfall-unity/files/5800223/UBLaMF.zip)

**First:**
If you enable the "Use Dungeon Texture Table" option on a prefab and the prefab is used outside a dungeon, Runtime Materials doesn't assign any of the materials it was supposed to. Pango spotted this in a Mages Guild that uses model 9004. Here is a screenshot of the issue. The left shows what the door looks like and the right is what happens if I switch on the "Use Dungeon Texture Table" option.
![MG Door](https://user-images.githubusercontent.com/7355441/104280658-26e0be00-5511-11eb-903f-43a911791370.jpg)

Here is a save you can use to test this: 
[MG Door save.zip](https://github.com/Interkarma/daggerfall-unity/files/5800287/MG.Door.save.zip)

**Second:**
Runtime Materials does not seem to work properly with the dungeon automap. When I replaced vanilla models with ones that used Runtime Materials, these models showed up on the map with completely white texturing. This is despite the models looking perfectly fine in the dungeon itself. Here is a screenshot showing what I saw. The opaque staircase model in the middle is one which I temporarily textured the regular way and the corridor pieces on the left are ones using Runtime Materials. Strangely, the opaque cave passageway model on the right is also using Runtime Materials but looks fine. Maybe the save being saved right next to that model has something to do with it. (Btw, don't worry about the models being opaque, Pango has already fixed that issue).
![Runtime Materials bug](https://user-images.githubusercontent.com/7355441/104281935-26e1bd80-5513-11eb-9e54-6b25964d5ddb.jpg)

Pango, OTOH, [mentioned seeing these models not using the correct textures instead](https://forums.dfworkshop.net/viewtopic.php?p=51315#p51315). You can use this save to test this issue. It loads right next to the cave passageway model in the picture. To find the staircase, just turn around and head back in that direction.
[Automap texture issues.zip](https://github.com/Interkarma/daggerfall-unity/files/5800377/Automap.texture.issues.zip)

**Third:**
I've noticed that in a few dungeons, the "Use Dungeon Texture Table" or "Apply Climate" option is selecting the wrong texture archive for the model to use. I've only seen this happen in Privateer's Hold and Daggerfall City's castle. Pango [spotted the same problem in Lysandus' Tomb](https://forums.dfworkshop.net/viewtopic.php?p=51316#p51316). So it appears that this is happening in the game's special/story dungeons.

This first screenshot is the stairs in Daggerfall Castle's throne room. The left shows what the stairs are supposed to look like. The right shows the stairs textures applied by Runtime Materials. The vertical portion of the steps are supposed to use the texture from Archive: 020, Index: 4. Runtime Materials is instead giving them the texture from Archive: 320, Index: 4.
![Castle stairs texture](https://user-images.githubusercontent.com/7355441/104283385-5396d480-5515-11eb-935e-30006417ab0b.jpg)

These next 2 screenshots are a staircase that is found in Privateer's Hold just before the room with the archer in it. In both pictures, you can see on the right the staircase with the textures Runtime Materials gave it and on the left is a neighbouring model with the correct textures. 

The ceiling portion of the staircase is supposed to use the texture of Archive: 020, Index: 4. It uses Archive: 320, Index: 4 instead. 
The walls are supposed to use Archive: 020, Index: 0 but use Archive: 320, Index: 0 instead. 
Finally, the horizontal parts of the steps are meant to be using Archive: 020, Index: 2. Instead, they used Archive: 320, Index: 2.
![Bug staircase 1](https://user-images.githubusercontent.com/7355441/104283744-dcae0b80-5515-11eb-9ff8-1087cb93c880.jpg)
![Bug staircase 2](https://user-images.githubusercontent.com/7355441/104283746-dd46a200-5515-11eb-8165-83aa0d09c986.jpg)

**Desktop:**
 - OS: Windows 10 Pro x64
 - Version 0.11.0

**Comment by TheLacus** [comment]
Second issue is probably related to [this bug reported on the forums](https://forums.dfworkshop.net/viewtopic.php?f=31&t=4412).

**Comment by XJDHDR** [comment]
First, I want to apologise because I forgot to attach the models that were in my screenshots to my report. I'll fix that now:
[Models.zip](https://github.com/Interkarma/daggerfall-unity/files/5825734/Models.zip)

I did some testing with your pull request #1994. Thank you for fixing the first issue. I also have some good news. It looks like your pull request also partially fixes the second problem. Here is a screenshot of what I see without your pull request:
![No PR](https://user-images.githubusercontent.com/7355441/104834975-36dd1100-5908-11eb-81b9-ff056224edb8.jpg)

This is what happens with your PR:
![PR installed](https://user-images.githubusercontent.com/7355441/104834984-43fa0000-5908-11eb-8a3f-ddc1d9ece1f6.jpg)

The only aspect of problem 2 I still see is that the models are not being affected by the climate and/or dungeon texture table options.

I also tested your PR with DREAM textures and I don't seem to be experiencing the problem in that forum thread:
![DREAM textures](https://user-images.githubusercontent.com/7355441/104835319-a522d300-590a-11eb-931d-72b707216ea5.jpg)

Problem 3 is still present.

**Comment by XJDHDR** [comment]
I've just found that Direnni Tower is also affected by the third problem I reported. I'm beginning to think that the solution to this problem is that if the model is in a Main Quest dungeon, the climate parameter must be forced to 0, regardless of anything else. Though I'm curious how this is done in the code for vanilla models.

**Comment by XJDHDR** [comment]
Just found that Castle Buckington in Ilessan Hills is also affected by the second problem. Runtime Materials is giving them textures from the 319 archive whereas neighbouring vanilla models are getting textures from the 019 archive. 

This is new because this is the first time I've seen this issue in a dungeon that doesn't appear to be associated with the main quest.

**Comment by XJDHDR** [comment]
I decided to investigate this a bit more.

For problem 2, I've found that the problem appears to be that for the Automap models, the DungeonTextureTable portion of the script is not working correctly. Conversely, the Climate portion appears to be correct. One thing I tried was to add a bit of debug scripting to the Awake function that logged a message telling me which layer the model was part of. Every message I received from this debugging told me that the model was in layer 0 (Automap models are in layer 10). So it sounds to me like the script on the Automap models never runs even though it is attached to them. 
This tells me that these models are not getting their texture data from the Runtime Materials script but rather, are being copied from the actual dungeon's models. And this copying is happening before the DungeonTextureTable portion has assigned it's textures. This is also probably why the fix for problem 1 also got rid of the white textures: Before that fix, the models didn't have any textures when the Automap logic copied the models whereas the fix meant that now they had at least the no DTT textures.

As for problem 3, all I've been able to find is that the problem is being caused by the Climate part of Runtime Materials. For some reason, RM thinks that the dungeon interior is part of climate 3 in every case I've seen whereas it is, in fact, climate 0.

**Comment by XJDHDR** [comment]
One of my mod's users has reported seeing problem 3 in "Ruins of Castle Moorston" in Wrothgarian Mountains. I wonder what all of these dungeons have in common?

**Comment by XJDHDR** [comment]
I've figured out why problem 2 is occurring but I haven't managed to figure out how to fix it. The problem is that the Automap creates it's models after DaggerfallDungeon has invoked the OnSetDungeon event. This means that the Automap models get initialised with I'm assuming the default texture table then registers for the OnSetDungeon event, which doesn't happen. 

This means the solution should be a way to make Automap either invoke it's own event that RM registers for or the DaggerfallDungeon event. Or maybe there is a better way to do this?
