### ISSUE TITLE
Record quest-related dialogues in the messages/notebook log

### ISSUE THREAD

**Issue by iamthegithubghost** [Interkarma/daggerfall-unity#2021]
**Describe the bug**
Sometimes a plot important message shows up (letter received/talking to an NPC before and after doing quests), and if you miss it, accidentally close it there's no way of re-reading that again. 

Suggestion: when these messages pop up, add them to the message log as well. I think that would be nice to have.

**Comment by ajrb** [comment]
FYI You can copy any conversation text you like to the log using the button on the talk window. Select the entries you want to copy and left click the copy button, or right click it to save the entire conversation.

Regarding quest text messages, that would need the quest scripts to be modified with the log entries being improved.
