### ISSUE TITLE
Stuck inside Direnni Tower (in Medora's room)

### ISSUE THREAD

**Issue by iamthegithubghost** [Interkarma/daggerfall-unity#2023]
**Describe the bug**
I teleported to Medora using a teleport spell after obtaining the item for her quest in another dungeon. Now I'm stuck near the area where she is in, cause the movable walls are blocking the way and the levers are on the other side.

**To Reproduce**
1. Use teleport spell to place and anchor near Medora in Direnni Tower
2. Leave and go to another dungeon and teleport back
3. You are now stuck inside Medora's room with no way out

**Expected behavior**
There should be some sort of switch on the other side to move the walls again, or just leave the walls in the correct position that they were before so you can pass normally.

**Screenshots**
![nao consigo sair](https://user-images.githubusercontent.com/32682282/106923712-217c2b00-66ed-11eb-895b-f3e420e7f54d.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Daggerfall Unity 0.11.0

**Comment by petchema** [comment]
This matches classic behavior

**Comment by Interkarma** [comment]
There are really many places a player could trap themselves using Teleport where the controls to exit an area are outside the Anchor location. Dungeons will reset when exiting dungeon (unless using a mod to persist dungeon state) and a prudent player should know not trap themselves inside a one-way labyrinth. Changing this by adding new switches to game data is outside the scope of Daggerfall Unity. This is more in the realm of WorldData mods.

The only spot I'd consider special handling for this is the front doors in Castle Daggerfall, but even then I'm not sure it's within scope. I'll consider that case sometime in future.
