### ISSUE TITLE
Mod System does not support negative float values in Mod Settings

### ISSUE THREAD

**Issue by Bl4ckh34d** [Interkarma/daggerfall-unity#2034]
**Describe the bug**
It seems that negative float values in the mod settings do not get carried over and instead reset back to default values.
I am using the float slider option and my range is from -4 to 4. Positiv values get saved but not the negative ones.

**To Reproduce**
1. Create a test mod
2. Create mod settings for the mod
3. Use float slider and set to a range of -4 to 4
4. When adjusting to a negative value and saving, the change will not be saved.

**Expected behavior**
Settings should get saved and carried over to the game instead of only positive floats getting saved.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 20.04
- Version: DFU 0.11.0

**Comment by TheLacus** [comment]
Related to fae09e9112f86e99c0332bc56e6a332130943ce9, leading signs must be parsed.
