### ISSUE TITLE
Teleportation to specific dungeon after loading

### ISSUE THREAD

**Issue by asdfdsad** [Interkarma/daggerfall-unity#2038]
**Describe the bug**
The game is currently teleporting my character to another location after I load the game. It doesn't matter which location I save at. I teleport to this same location every time.

**To Reproduce**
I'm not sure what causes it. The only thing I can thing of is that I left the dungeon with a recall anchor

**Expected behavior**
I shouldn't be teleporting at all after a load or reload.

**Screenshots**
In order. Load save
https://i.imgur.com/raytufg.jpg
Place I load into
https://i.imgur.com/7g80u7Z.jpg
Place I get teleported to instantly
https://i.imgur.com/v2jQQz5.jpg

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version beta v0.11.0

**Additional context**
I'm not sure what else applies. However, I attached the save file for the game in case this is useful
[SAVE0.zip](https://github.com/Interkarma/daggerfall-unity/files/5983213/SAVE0.zip)

**Comment by asdfdsad** [comment]
PS. Another possible cause for this teleporting may be related to the azimuthal vectors quest. 
https://en.uesp.net/wiki/Daggerfall:Azimuthal_Vectors
I ended up having to follow path II scenario 2. The NPC was supposed to have teleported me to the new location though I am not repeatedly teleported to the note on reloads. Just either to the entrance of the dungeon or some other room in the dungeon.

**Comment by asdfdsad** [comment]
I loaded the game, completed the quest Azimuthal Vectors. The path II scenario 2 for the quest is bugged. After you deliver the alchemy item and are teleported, it seems that the quest will teleport you to the dungeon where the catalogue item is whenever you load the game regardless of whether or not you picked up the catalogue or you went to the indicated dungeon and collected the item. It seems to teleport you to the catalogue's dungeon whenever you reload until the quest is completed or failed.

**Comment by Interkarma** [comment]
Can confirm the teleport quest action is firing again on load. I'll determine if this is faulty quest logic or some other issue. Cheers.

**Comment by Interkarma** [comment]
I have a related bug report on forum bug tracker for this quest. I'll combine these reports together and look at both at the same time. Will close this rather than keep both related issues open.

https://forums.dfworkshop.net/viewtopic.php?f=31&t=4599
