### ISSUE TITLE
"triedModels" cache can break location/climate model variants

### ISSUE THREAD

**Issue by rossipaolo** [Interkarma/daggerfall-unity#2042]
**Describe the bug**
#1148 by @ajrb  introduced a sort of cache to avoid additional seeks for models that are known not to be available. Unfortunately i didn't notice at the time that it can cause false positives when location/climate model variants are involved. Specifically this happens if a variant is available but the base prefab is not; this is probably a rare situation but i think it should still be supported properly.

**To Reproduce**

1. Make a mod containing prefab named `41116_Desert`. This is the variant only used for desert climate; base variant `41116` is not provided.
2. Load save in desert. Desert variant is used as expected.
3. Load save in a different climate than desert. No matching variant is found, so original asset is used. This is intended behaviour.
4. Load save in desert again. Desert variant is not used because model id was marked as missing.

**Expected behavior**
Climate/season variant should always be used if available, even if base variant is not provided. Behaviour shouldn't change depending on which climate/season is met first. 

**Desktop:**
 - Version 0.11.1

**Additional context**
Cache shouldn't only contain model uid, but also information on climate/season to allow proper invalidation.

[Saves.zip](https://github.com/Interkarma/daggerfall-unity/files/5990561/Saves.zip)
[Example.zip](https://github.com/Interkarma/daggerfall-unity/files/5990575/Example.zip)

**Comment by ajrb** [comment]
Ah yes this was for performance. Not sure if I realised that there were variants that were checked for at the time, but I think it's not unreasonable for us to require that all variants of a model to be replaced or none.

Has anyone actually encountered this issue? 

It's certainly something that should either be clear from documentation, or should be changed. I would favor the former, as I think it's an edge case.

**Comment by TheLacus** [comment]
I'm actually considering to make a global model cache, similar to the material cache that already exists. I noticed this issue so i wanted to fix it first.

I agree that is potentially an edge case, but i think it should work consistently. I didn't consider it an intentional limitation, but i understand is a bit ambiguos.
