### ISSUE TITLE
Generating sample of dialogue

### ISSUE THREAD

**Issue by seannyD** [Interkarma/daggerfall-unity#2066]
I'm trying to get a representative sample of dialogue from Daggerfall. I know it's procedurally generated. Is there a way to use these scripts to generate a set of possible dialogues, for example from a random NPC? That is, can I avoid actually playing the game and just run a script to automatically generate 1000 lines of dialogue text? (perhaps being able to specify characteristics for the NPC/quest etc.)?

Or would I be better off trying to parse the main quest QRC files?

**Comment by petchema** [comment]
Hi, that's not an issue, you'd be better asking similar questions in the forums
https://forums.dfworkshop.net/
Or Subreddit
https://www.reddit.com/r/daggerfallunity/
Or in the Discord server
https://discord.gg/TNSnFBJx
