### ISSUE TITLE
Sentinel Map Bug

### ISSUE THREAD

**Issue by AvnarJakob** [Interkarma/daggerfall-unity#2072]
When I´m in Wayrest and I want to fasttravel to Sentinel the Province Map of Sentinel is bugged. 
I´m on Windows 10 and the Version is 0.11.2
https://user-images.githubusercontent.com/75129695/113424084-d8d0ad80-93cf-11eb-902d-e66b1d4c0bc7.mp4

**Comment by petchema** [comment]
That was discussed in forums already I think: https://forums.dfworkshop.net/viewtopic.php?f=5&t=4668
Does that help?

**Comment by AvnarJakob** [comment]
ok thanks

**Comment by Interkarma** [comment]
This is due to bad data in a mod. Thank you @petchema for linking the forum article. :)
