### ISSUE TITLE
Enhancement Request: bundle cs files as source in precompiled

### ISSUE THREAD

**Issue by AsesinoBlade** [Interkarma/daggerfall-unity#2076]
Hi, this is not a bug, more of an enhancement Request. 

I get quite a bit of value from seeing other people's code examples so I use extract files often. 

I see that the precompiled option is getting more frequent user lately. When this option is selected, the code source doesn't make it into the dfmod. The only thing I see is the DLL. 

My request is to have the mod builder create a source directory and move all the code into it and bundle that with the dfmod. 

Thank you for your consideration. 
A

**Comment by XJDHDR** [comment]
I don't support this request at all. If a modder wanted other people to be able to look at their source code, they would provide it in an easily accessible format that doesn't require extracting it from the mod, or at least give it to anyone that asks.

Conversely, if a modder doesn't want their source code to be seen by anyone other than themselves, DFU has no business providing mod users a way to easily bypass the author's wishes.

**Comment by AsesinoBlade** [comment]
Hi XJDHDR, I can see your point.  I hadn’t been looking at it from that perspective; I was only saying that the functionality exists today but with the new precompiled option, it is now 100%.  I was only asking to put the functionality back to pre-precompiled.   If we want to remove the functionality, I understand.

Thanks for providing your perspective.
A

**Comment by gsaeed** [comment]
Hi, as I was updating my mods in Morrowind, I got to thinking about this a bit more.  All mods in Morrowind, Oblivion, and Skyrim are easily accessible; a user can load up the construction set, and customize the code  as they see fit.  So long as no one tries to repackage the code as their own or distribute their own variation of the code without prior approval, there is no issue.  I don't see how the mods for Daggerfall should be treated any different.

Just my two septims.
a

**Comment by XJDHDR** [comment]
The main question that should be answered is whether people who mod DFU are required to share the source code and files for their mods. If so, then this request should be done, assuming it's possible. If not, then I think my comment still stands.

I can understand that some would want to learn from what other have done but at the end of the day, the mod belongs to the modder and what they want should take precedence. As for the ease of looking at a mod's code for Bethesda's other games, that the nature of modding these games makes the framework of a mod open for everyone to see does not automatically mean that the same nature should be transplanted into DFU modding. The two environments run on different engines and use different toolsets to create the mods.

As for a Beth game mod's scripts specifically, it is entirely possible to distribute your mod without any source code present. For Creation Engine games, all you need to do is distribute the mod's PEX files and keep the PSOs to yourself. As for GameBryo, it's not as easy but can still be done. You just open your mod in a low-level editor (e.g. TES4Edit), open every script record in your mod and delete each one's SCTX subrecord. In both cases, this means the only thing the mod user has is the compiled script.

**Comment by Lazaroth** [comment]
1. Are there any MIT licensing concerns regarding this?
2. Are there any possibilities for a mod to do something malicious that could be hidden? 
/A lurker

**Comment by XJDHDR** [comment]
1. Unlikely. The MIT license, unlike the GPL for example, doesn't contain any provisions that force anyone linking to MIT licensed code to use the same license.
2. Mods have access to the full C# API and so, they could potentially perform malicious actions. Interkarma's [stance appears to be](https://www.dfworkshop.net/projects/daggerfall-unity/modding/#security-considerations) that the burden is on the mod user to ensure that mods don't do anything malicious.

**Comment by rossipaolo** [comment]
There are many mod authors that provide the source code for their mods, so that's already a good starting point to learn how create new ones.

Said that, the ability to export C# source code for security concerns has always been there, as part of the modding system as designed by Lypyl. Likewise, .dll files can be exported and is possible to review the content of such files if someone is really worried about it. I personally believe this is a little but important functionality to have for security and should't be removed or hidden.

I also think that current setup is good enough for the original purpose of ensuring safety of downloaded mods. For any different need, asking the mod author is probably the best approach to satisfy all different opinions.

**Comment by petchema** [comment]
Could adding more optional metadata fields, like mod URL and mod sources repository URL, be considered a gentle nudge for having sources somehow available?

**Comment by Interkarma** [comment]
I agree the current setup is good enough. It's difficult to enforce this without creating other problems, and it doesn't really solve any security concerns from malicious mods which could use techniques to bypass this anyway (e.g. obfuscation in DLL). I think Pango's gentle nudge is a better way to handle things. Encourage people to share but don't try to enforce it.

I'll close this one now. Maybe it's something that could be revisited later with a different approach.

**Comment by KABoissonneault** [comment]
The issue I have with precompiled mods is that suddenly DFU has to not only care about API compatibility, but also ABI (Application Binary Interface) compatibility. While I admit to not being much familiar with the .NET ABI, we've seen this issue pop up in the past when we had to decide to assign enum values for the UI Window Factory in an out-of-order manner to ensure precompiled mods wouldn't suddenly pass the wrong enum values.
I don't know if we have all the guidelines needed to ensure precompiled mods never break.

Given this reality, this means that authors of precompiled mods need to be extra aware, and, most importantly, present on every DFU update to potentially recompile and reupload their mods in case of ABI breakage.

In reality, many mod authors will make perfectly good mods and eventually go MIA. Some of these mods will not be using the precompiled option, and therefore their source can be recovered and the recompilation can be accomplished. Others will have a public repo available with the source, and those aren't an issue either. 

I think what OP suggests would help for that last case, where a mod author uses precompiled mods, has no available repository for the source, and they're not committed to maintaining the mod indefinitely. In that case, the community could extract the source, recompile it, and host it themselves. In general, platforms like Nexus tend to be good at ensuring people only use this for these scenarios, and not for stealing other people's work.

Just something to keep in mind.
