### ISSUE TITLE
impossible to climb through the "window"

### ISSUE THREAD

**Issue by d3vv** [Interkarma/daggerfall-unity#2081]
Into original dos-game it is possible to get through the window via crouch + levitation/climbing..

It looks like to impossible to use crouch+levitation or crouch+climbing at the same time for Daggerfall Unity..
But why not? Cause it's strange..

Such "Window" you can see at Screenshot below:

![2021_04_17_05_25_49](https://user-images.githubusercontent.com/32866346/115116919-d2802b00-9fa4-11eb-9472-8cfd3a3274df.jpg)

**Comment by petchema** [comment]
You can cross them using several techniques, crouch then jump, climb above window then crouch,...

**Comment by Interkarma** [comment]
Thanks Pango. :)
