### ISSUE TITLE
Question: Is the dungeon bug an issue for DFU?

### ISSUE THREAD

**Issue by d3vv** [Interkarma/daggerfall-unity#2086]
I have a Quest:

![2021_04_21_11_36_47](https://user-images.githubusercontent.com/32866346/115526673-f2f80000-a298-11eb-9ad6-a68c3da0514c.jpg)
![2021_04_21_11_36_13](https://user-images.githubusercontent.com/32866346/115526886-2a66ac80-a299-11eb-9995-774bfb42389c.jpg)

But I can't do it because I can't get through the cage:

![2021_04_21_11_35_41](https://user-images.githubusercontent.com/32866346/115526981-479b7b00-a299-11eb-8739-3f2ccb297695.jpg)
![2021_04_21_11_38_56](https://user-images.githubusercontent.com/32866346/115527094-68fc6700-a299-11eb-9aea-96269a9c3d53.jpg)

**Comment by petchema** [comment]
You have to click on the torch nearby to move the cage.
This should really be asked in help & support forums first
https://forums.dfworkshop.net/viewforum.php?f=5
