### ISSUE TITLE
Die with Silence effect

### ISSUE THREAD

**Issue by d3vv** [Interkarma/daggerfall-unity#2088]
If I die with silence effect on me, very often I can't cast any spell after "Load Game".
"Exit Game" it is only one way to resolve this issue.
It was seen on 0.11.3/0.11.2 DFU versions.

**Comment by Interkarma** [comment]
I attempted to reproduce this using the following method:

1. Ensure using a level 3 character - this is the start of level range where humanoid enemies will reliably cast silence
2. Save game
3. Use console command "cm 128" to generate a humanoid mage
4. Allow mage to Silence player then kill player while Silence is active
5. Load save from step 2 and test casting spells

Issue was not reproduced. All active spell bundles are removed and player is able to cast spells normally after loading prior save.
