### ISSUE TITLE
Can't escape from Castle Daggerfall

### ISSUE THREAD

**Issue by d3vv** [Interkarma/daggerfall-unity#2091]
Due to completing a Main Quest, I set an Anchor (Recall spell) in the throne room..
When I came back via Teleport (Recall spell), I was stuck in the castle, because the exit is blocked by magic doors..

**Comment by Interkarma** [comment]
There's already an active discussion about this: #1584.

Please refrain from creating low-information or duplicate topics in Issues. This facility is for developer discussion, not general feedback, user support, or gameplay requests.
