### ISSUE TITLE
[0.11.3] Last spell not saved for "recast spell"

### ISSUE THREAD

**Issue by hfc2x** [Interkarma/daggerfall-unity#2111]
**Describe the bug**
In classic Daggerfall, the key you could bind to "recast spell" would always remember the spell you used last from your list of spells in your grimoire. If, after doing this, you "used" an enchanted item that casts a spell (say, Fireball, Shock, etc.), the "recast spell" this would ignore this, and pressing the key would immediately use your last actual spell.

In Unity, this doesn't happen. Once you use an enchanted item that casts a spell, the game completely forgets what spell you last used.

**To Reproduce**
1. Cast a normal spell from your grimoire
2. Use an enchanted item that casts a spell on use
3. Try pressing the "recast spell" key

**Expected behavior**
The game should remember last spell cast, like classic Daggerfall does.

**Comment by petchema** [comment]
I just checked that classic Daggerfall behaves as you described.
Then I checked Daggerfall Unity, and that's how it behaved too:

1. Hurt myself so my HP is not maxed out
2. Cast heal health from spellbook
3. Cast slowfall using an item
4. Recast last spell, and got healed some more

**Comment by petchema** [comment]
Are you using mods?

**Comment by hfc2x** [comment]
Okay, I tested it, and it's Destruction spells cast from items that make the game forget the previous spell. Tried the same as you, but with an item casting Shadow Form, and I could successfully recast Balyna's Balm.

Trying to cast, at least with the items I had (mods or not), Shock or Fireball from items made the game forget my previous spell, but classic has no problem with these either.
