### ISSUE TITLE
Strange Game Engine Behavior

### ISSUE THREAD

**Issue by d3vv** [Interkarma/daggerfall-unity#2120]
Attached Save below started via DFU 0.11.2 (current versa 0.11.3)

Two serious problems:
1. No any quest letter since 4 level (current 28lvl)
2. If I raise the main skill (In this case "Destruction") - There is no any level progress

[SAVE1.zip](https://github.com/Interkarma/daggerfall-unity/files/6497615/SAVE1.zip)

**Comment by petchema** [comment]
Level 28 without editing the character, or importing a character edited in classic Daggerfall?

**Comment by Interkarma** [comment]
Please use the forums for gameplay support.
