### ISSUE TITLE
Broken download links?

### ISSUE THREAD

**Issue by fosskers** [Interkarma/daggerfall-unity#2129]
For some reason, every attempt I make to download DFU from the Unity cloud is thwarted by:

> The share link requested was not found.

The tab title is "Device Detection", not sure if that's relevant. 

Is there something wrong on my end, or did the links expire / get taken down internally? Thanks for any insight you can offer, looking forward to playing this classic game.

**Comment by petchema** [comment]
That's an issue tracker, not support

**Comment by Interkarma** [comment]
Please use the forums for general questions and support. Answer below and info in where to find a mirror here on git.

https://forums.dfworkshop.net/viewtopic.php?f=5&t=4830

**Comment by fosskers** [comment]
Thank you.
