### ISSUE TITLE
Mouse Weapon Sensitivity does nothing.

### ISSUE THREAD

**Issue by SpicerXD** [Interkarma/daggerfall-unity#2132]
It's implemented in WeaponMaster.cs on line 773.
But it's multiplying a value unrelated to the sensitivity of the gesture.

**Comment by KABoissonneault** [comment]
You mean this line?
https://github.com/Interkarma/daggerfall-unity/blob/master/Assets/Scripts/Game/WeaponManager.cs#L773

What do you mean by a value unrelated to sensitivity? `weaponSensitivity` is initialized to the settings value here
https://github.com/Interkarma/daggerfall-unity/blob/master/Assets/Scripts/Game/WeaponManager.cs#L196

**Comment by SpicerXD** [comment]
The issue is the AttackThreshold check below it uses an unmodified travel dist value from the gesture object. So effectively weapon sensitivity does nothing. As the sum var is just used when calculating the angle.

**Comment by Interkarma** [comment]
Yep, I see what you mean. Looks like the settings lost their meaning during a refactor to gesture controls. I'll remove the settings as they no longer apply.
