### ISSUE TITLE
Lower Power Magicka in Light/Dark not working indoors at day

### ISSUE THREAD

**Issue by JayH2971** [Interkarma/daggerfall-unity#2142]
**Describe the bug**
My High Elf character has both Lower Power Magicka in Light and Lower Power Magicka in Darkness. I had previously tested in classic that ""Light" is considered by the game to mean outdoors from 6AM to 6PM. "Darkness" is any circumstance that is not light." (https://forums.dfworkshop.net/viewtopic.php?f=4&t=270) However, there appears to be a gap between the two conditions in current DFU. At 6 AM, indoors, the "darkness" multiplier stops working and the "light" multiplier does not take over, meaning I get unreduced max magicka. I tried waiting all the way into the afternoon by changing the timescale, and I finally got 2/3 max magicka at 18:00.

**To Reproduce**
1. Make a character with lower magicka at light and darkness
2. Rest in a tavern until 6 AM (during the night, max magicka is reduced to 2/3)
3. Max magicka should be unreduced until you go outside or until 6 PM

**Expected behavior**
A character with lower magicka light & dark should always have a reduced max magicka of 66%. While indoors during the day, I have 100% max magicka.

**Desktop:**
 - OS: Linux 0.11.3 and 0.11.4

**Additional context**
[Lower Power Magicka.zip](https://github.com/Interkarma/daggerfall-unity/files/6620973/Lower.Power.Magicka.zip)

**Comment by Interkarma** [comment]
Light Powered Magery penalty is only applied at night time or inside dungeons in DFU. In classic, this _also_ takes effect inside buildings during the day (i.e. buildings are considered darkness). I seem to have intentionally changed this to not penalise the player for just going in and out of well-lit buildings during the day. Cannot recall reasoning behind this or if it was a misunderstanding on my part.

https://github.com/Interkarma/daggerfall-unity/blob/master/Assets/Scripts/Game/MagicAndEffects/Effects/Special/PassiveSpecialsEffect.cs#L212

Considering this now, it gives players with this penalty no disadvantage for the many indoor quests available around town (e.g. extermination, rampaging barbarians, etc.). It also doesn't match classic, so time for a fix here.

Thank you Jay. :)
