### ISSUE TITLE
Only Fire Atronachs can be soul trapped?

### ISSUE THREAD

**Issue by bernsamr** [Interkarma/daggerfall-unity#2167]
Tried to soul trap some Atronachs and wondered why they always made a saving throw in DFU Version 0.11.4 Beta. Then I looked at the code and saw that only Fire Atronach exists here. Flesh/Air Atronach, Ice/Water Atronach and Iron/Earth Atronach are missing and also naming inconsistencies in Classic DF are not solved as mentioned in comments here:

https://github.com/Interkarma/daggerfall-unity/blob/3d9f8bbc8afc902a70188c5af1172b50c2d5259b/Assets/Scripts/Game/MagicAndEffects/Effects/Enchanting/SoulBound.cs#L210

Take a look at the last comment from PLRDLF on UESP at https://en.uesp.net/wiki/Daggerfall_talk:Bestiary#Air_and_Water_Atronachs
It makes everything clear how implementation was intended in Classic DF.

**Comment by Interkarma** [comment]
The code you linked is unrelated to soul trapping process or saving throws. Rather, these are the forced effects associated with specific souls when added to an enchantment using the item maker. There are no effects related to these other soul types (Air/Water/Earth) as they do not exist.

My code comments are there for classic context only, and as a potential point of expansion. These comments should also be clarified as it's quite possible to soul capture Atronach type other than Fire. See screenshots below for a few examples.

![image](https://user-images.githubusercontent.com/10426244/124386738-263a1f00-dd1f-11eb-8b4c-690924f53bb0.png)

![image](https://user-images.githubusercontent.com/10426244/124386866-b5473700-dd1f-11eb-98a8-e7f02c16bbe3.png)

![image](https://user-images.githubusercontent.com/10426244/124386964-30105200-dd20-11eb-9718-dae3cfce22ae.png)

Souls trapped in DFU also do not have any naming inconsistencies that I'm aware of. As there is no issue in DFU here to resolve, I will close this now.

**Comment by bernsamr** [comment]
I found the reason for the saving throws. For some unknown reason I used a cold based custom soul trap spell and the Ice Atronach I targeted is immune to cold based magicka. The question here is: Does it make sense to allow any other than magicka based soul trap effects in spell maker? (other such things are fixed in DFU)

The other thing is that in classic DF it was intended that Fire Atronach, Flesh -> Air Atronach, Ice -> Water Atronach and Iron -> Earth Atronach souls should behave as mentioned at https://en.uesp.net/wiki/Daggerfall:Enchantment_Power (which they obviously do not except for Fire Atronach souls):

Fire Daedra | 55000 | -500 | Enhances Skill: DaedricCast When Used: Resist Fire | Bad Reactions From: Animals
Air Atronach | 35000 | -300 | Cast When Held: SlowfallingFeather Weight | Item Deteriorates: In Sunlight
Water Atronach | 35000 | -300 | Cast When Used: Resist FireCast When Used: Ice StormCast When Held: Resist Cold | None
Earth Atronach | 35000 | -300 | Strengthens Armor | Extra Weight

The following are only existing in classic because of a wrong implementation that has its cause in renaming Atronachs (Iron Atronach souls do not even exist in the table):

Flesh Atronach | 35000 | -300 | None | None
Ice Atronach | 35000 | -300 | None | None

**Comment by KABoissonneault** [comment]
From reading the code and your comment... it seems like DFU reproduces the classic behavior by having Flesh and Ice souls only give you the -300 cost? As long as DFU reproduces the classic behavior, there's not really any issue there. 

As for the rest, note that the spellmaker can be modded to change the element selection behavior, and the SoulBound effect can similarly be replaced to do something else if you want. 
For sure DFU has implemented fixes and balance changes over the years, but I don't think it's going to happen at this point in development

**Comment by bernsamr** [comment]
Maybe I am wrong but classic behaviour is the following mentioned at https://en.uesp.net/wiki/Daggerfall_talk:Bestiary#Air_and_Water_Atronachs

1. The F3-Info on atronachs still alive always says it's a flesh, fire, ice, iron atronach. The person who stated otherwise is clearly wrong.
2. Using th F3-Info on the corpses of flesh, ice and iron atronachs says indeed it's an air, water or earth atronach.This is also the reason why I've never noticed this, who would ever want to know what kind of corpse it is lying to his feet
3. Capturing the souls of these three atronachs will always result in a captured soul of an air, earth or water atronach.
4. Air, Earth and Water Atronachs are not mentioned with a single word anywhere in the Daggerfall Chronicles, neither in its bestiary nor in the soul bound table.

And if this is true no Flesh or Ice Atronach souls should exist (like Iron Atronach souls) _or_ Air, Water and Earth Atronach souls should be renamed to Flesh, Ice and Iron Atronach souls with the right advantages and disadvantages mentioned at https://en.uesp.net/wiki/Daggerfall:Enchantment_Power

**Comment by KABoissonneault** [comment]
>Air, Water and Earth Atronach souls should be renamed to Flesh, Ice and Iron Atronach souls with the advantages and disadvantages mentioned at https://en.uesp.net/wiki/Daggerfall:Enchantment_Power

DFU takes this approach, by not having Air/Water/Earth souls at all. Given how it behaves, we can claim that instances of corpses/souls with those names are bugs. Flesh, Ice and Iron Atronach souls have their benefit as listed on your list (except Iron, which is not featured on that list, but can be reasonably be given the same benefits as Ice/Flesh).

By the way, I suggest you verify with the original game itself, and not treat UESP as gospel­. Especially the Daggerfall pages, which sometimes date from the 90s, and contain urban legends from that era as opposed to the reverse engineering work that's been done on DFU.

**Comment by bernsamr** [comment]
I have played DF in the 90s myself but I am interested in DFU because on current platforms DF with all its flaws is a horror (its concept and art are still one of the best of all time but DOS implementation is not state of the art in any way -- this game is 35 years old!). I only wanted to help and comments in DFU code say exactly that current implementation in this case is not really a complete revers engineering because its not known to the author how it worked in classic.
