### ISSUE TITLE
The Mod Settings button in the pause menu should be hidden if the mod system is off.

### ISSUE THREAD

**Issue by SpicerXD** [Interkarma/daggerfall-unity#2184]
Basically just remove the Mod Settings button in the pause menu when the mod system is disabled.

**Comment by jefetienne** [comment]
Fair point – I'll look into adding some improvements.

**Comment by qingpaul** [comment]
there isn't a "setting" button on the mods menu，how do get it out?

**Comment by SpicerXD** [comment]
The button in question is in the in-game pause menu at the top left, not the mods menu in the launcher.

**Comment by Interkarma** [comment]
> Fair point – I'll look into adding some improvements.

Maybe in addition to disabling if mod system off, also disable if no mods active. But either might be a problem if other features are added to that arrow later.

Another option is to change the texture to something a bit less eye-catching that the red arrow. Example being a grey upward chevron with transparent areas. Something like below scaled down into same space.

![image](https://user-images.githubusercontent.com/10426244/128652652-f4a9e940-e1a0-41ab-b9d2-5cbf2d32e4c3.png)

**Comment by jefetienne** [comment]
I think what I will do is implement functionality to have certain ListBox items be disable-able and grayed out – that way people without editable mods can at least know where the option is.

I can definitely use a new texture. My first commit for the PR originally used [simple triangle textures](https://github.com/jefetienne/daggerfall-unity/blob/5a70647885ec609a944383f7c1852b95b19229f0/Assets/Resources/arrow_up.png) I made, but I think the chevron looks better.
