### ISSUE TITLE
Automap in outdoor area

### ISSUE THREAD

**Issue by bernsamr** [Interkarma/daggerfall-unity#2185]
DFU Version 0.11.5 Beta

Currently the automap key "M" opens an empty map in outdoor areas (and it seems you can not even escape from this map anymore).

**Comment by Interkarma** [comment]
I have tested this in 0.11.5. My observation is the automap can be opened while anywhere inside a location map pixel. Once player moves outside of a location map pixel (i.e. wilderness proper), then automap key M does not open the UI. This is a variance from classic which only opens automap while player is inside the enclosing rect of a location. I'll re-label this as a classic variance and resolve. Cheers.

The second item mentioned is not reproduced. I am able to close automap UI using either the Esc key or toggling closed again with the bound key. This sounds like a local setup issue with either bindings or shortcuts keys. Please feel free to use Help & Support on the forums for individual support.

https://forums.dfworkshop.net/

**Comment by bernsamr** [comment]
The cause of the problem seems to be a mod that was installed, see https://www.nexusmods.com/daggerfallunity/mods/5?tab=bugs

**Comment by Interkarma** [comment]
Thanks for info on mod incompatibility. I'm issuing a hotfix for this specific problem, and have offered a workaround to KoW on forums that he might be able to use as well.

**Comment by bernsamr** [comment]
Thanks I can confirm that the automap works again with the mod and and the new version 0.11.6 Beta
