### ISSUE TITLE
Saved derived character attribute value

### ISSUE THREAD

**Issue by bernsamr** [Interkarma/daggerfall-unity#2186]
DFU Version 0.11.5 Beta

If character attributes are modified by some value then also derived attributes are modified partly by these modifiers. Sometimes it seems that these modifiers are ignored or are applied in the wrong order when you save your game.

This happens i.e. if you are a lycanthrope and your original strength and/or endurance is lower than 100. When you save your game then sometimes it happens when you reload it that you have your fatigue about halved. This does not happen all the time but when this happens it seems the stored value in saved game is wrong and everytime you load this exact saved game afterwards the fatigue value is wrong.

**Comment by Interkarma** [comment]
This is related to below bug on forum tracker. As you guessed, it's likely due to load order application of effect modifiers.

https://forums.dfworkshop.net/viewtopic.php?f=31&t=4549

I'll add your notes to the above topic and close this one now so we don't have duplicates. Cheers.
