### ISSUE TITLE
Quest fix needed: K0C00Y06, A Mix-Up

### ISSUE THREAD

**Issue by JayH2971** [Interkarma/daggerfall-unity#2191]
I'm aware I'm "the quest person," but there are times when a job is really, really beyond me. Anyone is free to pick this up and try to fix it. The sheer number of variables and paths through this quest makes it gigantic to debug and repair properly.

I'm not going to give a thorough explanation of what's broken in the quest (if I could, I'd fix it and be done with it), but a few of the problems are NPCs who should appear in buildings where they don't, quest topics that should be made available but don't, and paths that depend on certain actions to happen but don't. Whether people choose to collaborate or work on it separately is up to them.

This issue is for workflow's sake, so we don't forget about it by the time 1.0 comes around.

**Comment by KABoissonneault** [comment]
Unrelated, but personally I'd like to restore the classic rep gains for that quest. I was thinking of instead adding a new check that cuts the quest early if your legal rep is 10 or above (ex: someone off-screen vouches for you). Our current workaround removes the primary option for restoring a bad legal rep.

I'll have a look on the code side and see if there's anything we don't handle well. Maybe there's some more stuff we don't handle properly, such as the semantics of the "Local" factions, as Ferital discovered

**Comment by JayH2971** [comment]
> I was thinking of instead adding a new check that cuts the quest early if your legal rep is 10 or above

That isn't extant in the current quest conditions, so the first step would be designing that (assuming the idea is accepted; I'm neither for nor against it).

I think the exaggerated nature of the quest opens itself to criticism. It's kind of silly that a mass murderer could get accused of stealing a gem, and once it's returned, you suddenly become a local hero to law enforcement. It's mechanically useful, but a really wild concept when taken with fridge logic. Daggerfall really needs more methods to improve legal rep, IMO.

**Comment by mundifex** [comment]
Along with the fixes introduced for #2190, the quest is now very playable. It's still the abstruse beast it always was in classic but the usual suspects are where they should be, the witness is where you're told, and I was able to both clear my name and return the stolen gem across several attempts.

**Comment by JayH2971** [comment]
My gosh. I had no idea this much hecking help would come along for this thing. I can't call it finished until IK makes the decision, but I'm very grateful for what's been seen and fixed so far. No wonder trying to resolve this on my own felt like sinking into quicksand!

**Comment by Interkarma** [comment]
I believe K0C00Y06 is working well enough to close this one now. Please let me know if some problems exist that still need attention and we can reopen or create a new issue.

A big thanks again to @mundifex for review and helping to fix those bugs.
