### ISSUE TITLE
Nocturnal's Summoning Day does not match book text

### ISSUE THREAD

**Issue by Zebendal** [Interkarma/daggerfall-unity#2204]
Not too big of an issue, but Daggerfall in-game has Nocturnal's Summoning Day as the 8th of Hearth Fire instead of the 3rd of Hearthfire. The later is the intentional, and the former is a bug and here is my argument. The Daggerfall version of the book, the [Invocation of Azura](https://en.uesp.net/wiki/Lore:Invocation_of_Azura_(Daggerfall)), gives a list of Daedric Prince Summoning Dates out, the 3rd of Hearthfire is stated to be the one for Nocturnal, with 8th of Hearthfire nowhere to be seen. The Morrowind, Skyrim, and Elder Scrolls Online [version of the book ](https://en.uesp.net/wiki/Lore:Invocation_of_Azura) also keeps the 3rd of Hearthfire as the intended date for Nocturnal. Lastly, the Daggerfall Chronicles also gives the 3rd of Hearthfire as the official Summoning Day for Nocturnal, it would be nice to see this patched to reflect the intended date.

**Comment by KABoissonneault** [comment]
I agree that I think the book and the actual date should be consistent, in terms of player experience (given the summoner explicitly tells you to go read that book as a reference).
However, I'd be fine with fixing the book instead. It may be less intrusive for veteran players.

**Comment by Zebendal** [comment]
I understand a purist take, but dev intent has it as the 3rd so changing the book

**Comment by ajrb** [comment]
If someone can confirm what classic does whether the summoning day is 8th or 3rd then we can change the day or the book to match depending on that.

**Comment by KABoissonneault** [comment]
Oh, it's well known that classic has the same inconsistency - that's why UESP described it that way. It's a request for an improvement.

**Comment by Interkarma** [comment]
I'll tag this one as a refinement. It's not a bug as the current date is intentional to match classic.

I'll go with whatever the consensus is for change - whether it's fixing the book or changing the date. There does seem to be a lot of merit to the date being wrong, just keep in mind that if we change the date then the next bug report will be that the date is different to classic. :)

It's funny, but I can imagine a bleary-eyed tired programmer in the 90s reading someone's handwritten notes and confusing a 3 with an 8 here.

**Comment by ajrb** [comment]
I think it would be the best to change the book, and keep the date the same as it's always been.

**Comment by Nkfree** [comment]
From briefly reading the book I understood that 8th is the summoning day of Malacath, so I support the idea of changing it in the back-end side and refrain from touching the book.

**Comment by KABoissonneault** [comment]
You've misread the book. It says the 8th of _Frostfall_ is the summoning day of Malacath, not the 8th of Hearth Fire

> The only days we are forbidden to invoke her are those prescribed to one of the other fifteen Princes: the 1st and the 13th of Morning Star, the 2nd and the 16th of Suns Dawn, the 5th of First Seed, the 9th of Rains Hand, the 9th of Second Seed, the 5th of Mid Year, the 10th of Suns Height, **the 3rd of Hearth Fire, the 8th and the 13th of Frost Fall**, the 2nd and 20th of Suns Dusk, and the 20th of Evening Star. I know who is summoned on the 3rd of Hearth Fire, the 2nd of Suns Dusk, and the 20th of Evening Star, but I am not certain of the others.

**Comment by Nkfree** [comment]
Right, I apologize for that oversight, I should have realized that ajrb would be aware of that. Anyway it would seem that fixing the date is more vanilla friendly than editing the book.

**Comment by Interkarma** [comment]
>However, I'd be fine with fixing the book instead. It may be less intrusive for veteran players.

>I think it would be the best to change the book, and keep the date the same as it's always been.

Having let this one sit for a while, I'm with @KABoissonneault and @ajrb here. I think Daggerfall should keep it's functional summoning date and correct date in book.

This is a easier fix once books are added to localization however, so will leave issue pending until then.
