### ISSUE TITLE
there isn't a setting button on the mods menu anymore

### ISSUE THREAD

**Issue by qingpaul** [Interkarma/daggerfall-unity#2206]
**Describe the bug**
A clear and concise description of what the bug is. Please attach a save game to demonstrate or reproduce bug if possible.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux Universal, Mac Universal]
 - Version [e.g. 0.10.1]

**Additional context**

**Comment by Interkarma** [comment]
There is no usable information on this issue. Please use the forums for individual support.

https://forums.dfworkshop.net/
