### ISSUE TITLE
Setting ShowOptionsAtStart to False causes the Gold info box text to show a localetext-notfound error.

### ISSUE THREAD

**Issue by SpicerXD** [Interkarma/daggerfall-unity#2207]
To reproduce:
Set ShowOptionsAtStart to false from the launcher or file.
Restart and go in game and open the inventory screen.
Hover over the Gold button and the info box below with read as "<LocaleText-NotFound>".

**Comment by Interkarma** [comment]
Cheers. This has already been raised on forums and is being tracked there.

https://forums.dfworkshop.net/viewtopic.php?f=31&t=4954
