### ISSUE TITLE
The volume sliders in the launcher are far less granular than the in-game ones.

### ISSUE THREAD

**Issue by SpicerXD** [Interkarma/daggerfall-unity#2208]
Basically if you lower the volume to say 5% using the in-game settings menu and then open the settings in the launcher, the volume setting will be rounded to 0% by the launcher and saved as such.

**Comment by Interkarma** [comment]
Both controls manage a value from 0.0 through 1.0, but the way the two interfaces work is different. The slider in launcher uses a scroller with 0.1 increments. The interaction in game uses percent of xpos within the control panel for the volume selector.

One solution would be to change the units of scroller to have more resolution. I'd prefer that over making the in-game control have less resolution to match the launcher.

I'll tag this as a refinement. Until then, just use whichever control you like the most.

**Comment by Interkarma** [comment]
This was an easy fix so pushed a change before work. Also fixed the horizontal scroll thumb cracking that I forgot to do when fixing vertical scroller.
