### ISSUE TITLE
Check SoundClips labeling of 65 and 73

### ISSUE THREAD

**Issue by JaceySanders** [Interkarma/daggerfall-unity#2213]
SoundClips labels clip 65 as AmbientWindMoan, and 73 as AmbientMonsterRoar. Based on hearing these effects (indirectly, though Cleaned Sound Clips), I think DFU might have them mislabeled, with their names being swapped. 65 sounds like a roar, and 73 sounds like the wind.

I was unable to confirm this using an unmodded source for the sound files, so check and make your own judgement.

**Comment by petchema** [comment]
Here are sounds as extracted from DAGGER.SND by DaggerSoundExtract.exe, and correctly formatted as 8bit 11111Hz mono wave files:
[DaggerSoundExtract_then_sox.zip](https://github.com/Interkarma/daggerfall-unity/files/6995067/DaggerSoundExtract_then_sox.zip)
How one interprets synthetic sounds can be subjective, personally I think current naming is okay
