### ISSUE TITLE
Missing Classic feature: highlighting and hiding rooms on dungeon Automap

### ISSUE THREAD

**Issue by KABoissonneault** [Interkarma/daggerfall-unity#2217]
There's a classic feature DFU is missing on the Automap (in addition to custom labels on the town map): hightlighting and hiding "rooms" on the dungeon Automap.

Each dungeon block has a list of models which represent either a partial, or complete room in the dungeon. For this context, I will use "room" generically for any individual model that represents a chunk of the layout, be it an actual room, part of a room, or part of a hallway.

In classic, if you left-click on a room while on the Automap, it will flash a bit to highlight it. If you right-click it, it will disappear for good until you close and reopen the Automap.

The former is mostly useful for telling what room will be affected by a right-click at this location, while the latter is useful for navigating extremely dense blocks, even with DFU's many automap improvements, in my opinion.

Here's a GIF to give an idea of what I mean. First half is left-clicks, second half is right-clicks.
![2021-08-19 10-21-58](https://user-images.githubusercontent.com/5789925/130094394-d381cbc6-df10-4bc4-8bfd-49639bd7a8d9.gif)

I'm not really expecting a fix for this, especially not before 1.0. Just trying to document this issue and get some opinions from people who've worked in this area.

**Comment by KABoissonneault** [comment]
Note: 

This pull request has this mention from Nystul
https://github.com/Interkarma/daggerfall-unity/pull/1699

>imho classic behavior is not a good measure since the "peeling" was a horrible mechanism in my opinion which led to more confusion than it helped

I think the "peeling" refers to the feature this issue is discussing, and so I think not implementing this feature was done on purpose.

This PR actually reminded me of the 2D mode, and taught me about the "near plane" cut that it uses. From a quick test, it does seem better to just use that than to "peel" rooms by hand, as in classic. Remove my note about this being useful for DFU, then :P

**Comment by Interkarma** [comment]
It's not really missing, just the same concept is implemented differently (and better) in DFU. The concept being to see what is below upper layers of dungeons and assist navigation.

Classic does this by disabling models, which is about all it could do with its rendering tech. DFU does this by allowing player smoothly swipe transparency up and down to incrementally peek through one or more layers of dungeons. When it comes to navigating dense blocks, the higher draw distance and better controls overall also make it unnecessary to toggle individual models.

I prefer Nystul's take on the automap, by far. I've watched streams where experienced Daggerfall players heap praise on the new map, and this my personal experience playing the game as well. Anyone frustrated by the dungeon automap in DFU are more likely just frustrated with Daggerfall's spaghetti dungeons. They either didn't play classic or don't recall how much less useful the automap was.

I'll leave this open for discussion as requested. But I see no need to implement this exactly, or that it would improve the way this concept is already implemented in DFU.

**Comment by JayH2971** [comment]
Hiding specific dungeon pieces may not be necessary anymore, but I did enjoy being able to make a dungeon piece blink in classic. I would look for a junction near the exit in a complex dungeon, make it blink, and then tracing my way to it from my current position. There have been a couple times in DFU that would've made my returns easier. Unless there's a similar function in DFU I'm missing?

**Comment by petchema** [comment]
> I did enjoy being able to make a dungeon piece blink in classic. I would look for a junction near the exit in a complex dungeon, make it blink, and then trace my way to it from my current position. There have been a couple times in DFU that would've made my returns easier. Unless there's a similar function in DFU I'm missing?

Closest feature would be notes, assuming you haven't used too many notes already given there's only one kind of note marker...
