### ISSUE TITLE
Quest n0b00y17, Catalogue didn't spawn

### ISSUE THREAD

**Issue by jhardin101** [Interkarma/daggerfall-unity#2224]
When going through the mages guild quest id "n0b00y17", after retrieving the ingredients for the expert on the magical item, they teleported me to the dungeon but it appears that the catalogue didn't spawn in, so I couldn't finish the quest.

**Comment by Interkarma** [comment]
This sounds like a known classic variance where player is not spawned directly on top of target item. There's an open bug report for this below. You can still locate item through exploration or using "tele2qmarker" to move player directly to target item.

https://forums.dfworkshop.net/viewtopic.php?f=31&t=4599

**Comment by jhardin101** [comment]
Hm, I explored the whole dungeon, but never found it. Thanks for pointing out the bug report.
