### ISSUE TITLE
Mages Guild "Guard the Guild" bugged due to quest marker changes, 0.12.2

### ISSUE THREAD

**Issue by JayH2971** [Interkarma/daggerfall-unity#2233]
I hope I'm not overstepping my bounds here. I just want to make a reminder for the bug reported here: https://www.reddit.com/r/daggerfallunity/comments/pedfh0/cant_guard_mages_guild/

Interkarma suspects regression from PR #2197.

User on Reddit reported reproduced with no mods on 0.12.2. Error is:

Parsing quest N0B10Y03.txt FAILED! Could not find local site for magesguild with P2=11 in Daggerfall/Daggerfall. (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 39)

**Comment by Interkarma** [comment]
Thank you Jay! I've already made a note to tackle this one later today or this evening when I can.

**Comment by Interkarma** [comment]
Confirmed that reverting #2197 fixes this regression and N0B10Y03 runs again. I'll look for a solution to exclude same-building quest-questor assignments like this bouncing quests while still solving the multiple building assignments that code change is intended to fix.
