### ISSUE TITLE
(modding) - Contains, GetItem, etc don't work with custom items

### ISSUE THREAD

**Issue by joshcamas** [Interkarma/daggerfall-unity#2245]
**Describe the bug**
ItemCollection.Contains, ItemCollection.GetItem, etc all use this logic to get the groupIndex:

```
int groupIndex = DaggerfallUnity.Instance.ItemHelper.GetGroupIndex(itemGroup, itemIndex);
```

For any modded item (ie an item with a custom template index), this will always return -1. However, it looks like any of these modded items have a groupIndex identical to their templateIndex.

Thus, the contains code, for example, should be this:

```
public bool Contains(ItemGroups itemGroup, int itemIndex)
        {
            int groupIndex = DaggerfallUnity.Instance.ItemHelper.GetGroupIndex(itemGroup, itemIndex);
            foreach (DaggerfallUnityItem item in items.Values)
            {
                if (item.ItemGroup == itemGroup && (item.GroupIndex == groupIndex || groupIndex  == -1 && item.GroupIndex == itemIndex)
                    return true;
            }
            return false;
        }
 ```
 
 This would make the default group indices work as expected, but also make this code function with modded items.

**Comment by Interkarma** [comment]
Thank you for raising, and offering a potential solution. :)

**Comment by ajrb** [comment]
I think I have a simpler way to solve this. @joshcamas Can you take a look at my PR and see if you see any problems.
