### ISSUE TITLE
Download File Name Request

### ISSUE THREAD

**Issue by Narthaxx** [Interkarma/daggerfall-unity#2251]
I'm not really familiar with github these days beyond having it be a place where programs and code gets uploaded, so sorry if this isn't trivial, but would it be possible to just add Daggerfall or DFU or _something_ to the name of the download files so they're easier to find?  It's not such an issue if I extract it and run it from the download list in my browser right away, but the current naming of the file makes it get lost in all the drivers, .iso files, utilities, zip files from work, sketchy .rar's I got on russian forums, random files with broken characters that I can't delete that show up whenever I use public wifi, and other perfectly legit files like that in my downloads folder.

This isn't a huge thing, and it's not like I can't rename it myself, but it is a little annoying to download a file, extract it, mess around with getting all the game files in order, start it once just to make sure it's working, go to bed, and come back the next day unable to find it, think I'm going mad, look again, accept that I'm probably already waaaay past mad and must have imagined downloading it, check one more time that I didn't move it somewhere stupid or had to extract it to the GOG folder where my Daggerfall game data is stored or something, fall into despair over my declining mental state, and then download it again only to find that I just downloaded "windows_64bit-v0.12.3-beta **_(1)_** "

Even just "DFU" or something similar at the beginning that would at least put it in the same general alphabetical location would be better than no name at all.  I download a bunch of zip files and office docs every day for work and other stuff I do, and I'm probably not the only one.  Like I said, it's a very small thing, but it's annoying when files are given names that don't really mean anything and just get lost immediately as a result.  This engine overhaul is neat, y'all should be _proud_ of it instead of naming it like a trojan :P

**Comment by Interkarma** [comment]
Sure thing. :) I'll start prefixing download filenames with "dfu_" from next release.
