### ISSUE TITLE
Repair Object Works Incorrectly

### ISSUE THREAD

**Issue by rag-ray** [Interkarma/daggerfall-unity#2256]
As of 0.11.4 the following is true:

The Repair Object enchantment does not work when "Repair Magic Items" is turned off. This does not duplicate the behavior of the original game. Repair Magic Items should apply only to smiths, but not to enchantments.

**Comment by Interkarma** [comment]
The Repairs Objects enchantment does not increase condition of enchanted items in classic Daggerfall unless "MAGICREPAIR 1" is also added to Z.CFG.

By way of testing, please refer to below classic save where character is holding an enchanted dagger at Used condition, alongside other items with Repairs Objects enchantments. No amount of resting will increase the condition of dagger - unless "MAGICREPAIR 1" is also enabled.

[SAVE0.zip](https://github.com/Interkarma/daggerfall-unity/files/7327336/SAVE0.zip)

The behaviour in Daggerfall Unity matches classic precisely here, with "Repair Magic Items" setting the equivalent to MAGICREPAIR in classic. In both versions of game, Repairs Objects will not operate on magic items unless this option is enabled.

Please use the forums for personal support around mods and checking on function of items before opening Issues. Thank you so much. :)

https://forums.dfworkshop.net/
