### ISSUE TITLE
Loot Icons Do Not Persist

### ISSUE THREAD

**Issue by rag-ray** [Interkarma/daggerfall-unity#2258]
As of 0.11.4 this was true:

When I am running the Persistent Dungeons mod and I drop loot on the ground, the icon I select to show its location does not persist if I leave the dungeon and then return. The icon may be replaced by a smaller one or may disappear altogether. In that case, I can still access the loot by clicking on the place where I know it must be.

This has been an issue during many subsequent releases of the game.

**Comment by JayH2971** [comment]
Hello!

The issues in this repository have the focus of an unmodded Daggerfall Unity. Since this problem deals only with a mod, the best approach would be to address it with the mod creator directly :smiley:
