### ISSUE TITLE
[0.13.2] Spell and arrow missile objects appear to be colliding early with caster/archer at instantiation position

### ISSUE THREAD

**Issue by dzmcclur** [Interkarma/daggerfall-unity#2266]
I have been playing on 0.13.1 for a while and upgraded to 0.13.2. Since then, I noticed that I never seemed to hit with arrows. I figured it was due to monsters getting more difficult, but as time went on I went through hundreds of arrows without a hit. Finally, I realized something was up when I was in combat with several humanoid opponents and they were all firing arrows at me: none of them would ever hit!

I picked a fight with a ranger and just sat there letting myself get attacked from a range, and never got hit. I disabled mods dealing with combat, nothing changed.

When I ran 0.13.1 again and loaded the save, archery worked as expected again. Perhaps some recent change is affecting how arrows work and causes them to "collide" with an invisible object?

**Comment by Interkarma** [comment]
Thank you for raising. I have reproduced issue with missiles (both spells and arrows) terminating improperly after release. Arrows do seem most affected though. It looks like missile object is improperly colliding with caster/archer.

I'll investigate further and resolve this one as a priority before next release.

**Comment by Interkarma** [comment]
I've determined the cause here. There's a BoxCollider on the new PostProcess Volume object in scene interacting with missiles. Not sure how that happened - will remove and issue a hotfix.
