### ISSUE TITLE
Different weapon swings with mouse look?

### ISSUE THREAD

**Issue by jason-mehmel** [Interkarma/daggerfall-unity#2278]
If I remember right, weapon swings would use the way you moved the mouse to determine between a swing, a thrust, and a chop.

Is that implemented in the Mouselook option? I've tried moving my view in the direction I want the swing to go but I'm not seeing any consistent results.

**Comment by Interkarma** [comment]
Daggerfall Unity uses gesture based attacks by default, same as classic Daggerfall. You need to hold attack button and drag mouse continuously on the axis you want to swing.

If you have Click to Attack enabled, then swing direction is random. You'll need to disable Click to Attack for gesture based attacks.

Please use the forums for personal support and gameplay questions. Thank you.

https://forums.dfworkshop.net/
