### ISSUE TITLE
Anisotropic filtering doesn't work.

### ISSUE THREAD

**Issue by daedrixxx2** [Interkarma/daggerfall-unity#2283]
**Describe the bug**
Anisotropic filtering in v0.13.4 doesn't work. It worked fine in v0.12.3

**Screenshots**
![2022_01_23_21_36_16](https://user-images.githubusercontent.com/61243321/150697359-14f907ec-cc8a-4200-bf6b-a15fa8dfd76d.jpg)
After 5m or so, the ground is blurry.

Anisotropic filtering is of course activated (x16) in the Nvidia Control Panel

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2
 - GPU: GTX 970  latest drivers available as of today

**Comment by Interkarma** [comment]
Hi, please use the forums for personal support. Thank you. :)

https://forums.dfworkshop.net/
