### ISSUE TITLE
Weird terrain in Tigonus

### ISSUE THREAD

**Issue by KABoissonneault** [Interkarma/daggerfall-unity#2291]
In the corners of world coordinates [470, 355], [470, 356], [471, 355], and [471, 356], there is a weird mountain. These screenshots were taken with all mods disabled.

![image](https://user-images.githubusercontent.com/5789925/151727143-8b9fb947-569f-4e52-90e3-7e72c702c7a4.png)

![image](https://user-images.githubusercontent.com/5789925/151727219-6236fa88-da70-4880-afdd-d6fbc44aa642.png)

It seems to form a plateau at some kind of height limit, and forms a perfect circle when viewed from the top, with each quadrant in its own map pixel.

One way to reach it is to go to The Old Kharkur Shack in Tigonus. You'll know you have the right place because the location is placed over water.

![image](https://user-images.githubusercontent.com/5789925/151727432-be4c2b6d-fffd-4048-bf2f-cbcfb76739a5.png)

This is fortunately not an issue, because it behaves the same in the original Daggerfall.
From there, you can head straight south and reach it in minutes on foot.

I assume these map pixels have a crazy high heightmap value, because even the original Daggerfall has a small hill there.

![image](https://user-images.githubusercontent.com/5789925/151727569-0390d564-35b4-460b-a7e2-2e6b551bbf55.png)

I feel like the DFU's terrain generation should sanitize out this value so that it's not that extreme.

**Comment by Interkarma** [comment]
Hi, this is very well known and is the result of a single max-height pixel in WOODS.WLD. I don't have any plans to remove it. :)
