### ISSUE TITLE
I miss every attack even if im aiming at my target

### ISSUE THREAD

**Issue by L0d1n** [Interkarma/daggerfall-unity#2305]
i downloaded yesterday the game and im still stuck in the first dungeon because no matter how much i try to hit my target i always miss them. I tried multiple ways: I tried bringing the enemy to the corner or leaving the option where holding down the right mouse button I entered the attack mode, but nothing works. Is this a problem of the game or am i just a bot at it?

**Comment by jotoho** [comment]
I suspect that the [Daggerfall Workshop Forum](https://forums.dfworkshop.net/) is a better place for this kind of general game advice. This issue tracker is more for confirmed issues/bugs in the engine.

Whether your attack hits your target is determined using random numbers and math based on your character's abilities/stats and the weapon used. So unless you have some mod installed that messes with these things, you're probably doing something wrong. (I couldn't tell you what without more information)

*Disclaimer: I'm just another player and neither a contributor nor a Daggerfall expert.*
