### ISSUE TITLE
0.13.4: Candle from the Light spell has collision

### ISSUE THREAD

**Issue by sanscriptum** [Interkarma/daggerfall-unity#2306]
- OS: Windows 7

The candle created by the Light spell appears to have a collision. Any ranged spells and arrows will hit it or barely just pass it, especially spells as they have a really fat hitbox. Thus, you can't hit anything that is standing in front of you where the candle is, and the enemies can't hit you either as long as their projectiles hit the candle. Melee seems to work fine.
[Video Demonstration](https://i.imgur.com/giLIr1o.mp4)

**Comment by Interkarma** [comment]
In the base game, there are no collider elements of any kind on the MagicCandle prefab, or on the subordinate DaggerfallBillboard clone. I've confirmed in editor with current code (see bottom of reply for screenshots).

When testing this in game, I experience no collision behaviours casting out or receiving from enemies with magic candle active. The spell missiles pass through it as expected.

I can't say what's happening in your game, but it's definitely not baseline behaviour. I can only suggest that a mod or some other change has introduced this. Please ensure you have remove all mods and are testing the base game only. It might be worth providing a save on forums if problem continues.

![image](https://user-images.githubusercontent.com/10426244/159625947-1324c95c-48ef-4206-abb9-074cc1db6701.png)

![image](https://user-images.githubusercontent.com/10426244/159625990-3b693f28-77ba-4756-868e-6a16aa9f320d.png)

**Comment by Interkarma** [comment]
Something else I noted when watching clip is there's a tooltip displayed for an NPC called Elyzanna Yeomton when crosshair is over  candle billboard. This really looks like something weird produced by a mod, as that tooltip doesn't happen in base game and the candle billboard isn't associated with any NPCs.

Best I can suggest is to strip all your mods and post a save to forums if it still happens. We'll do our best to get to the bottom of it. :)

**Comment by sanscriptum** [comment]
Oh, I haven't considered that at all somehow. The tooltip mod is called World Tooltips, which didn't seem to cause that behavior. I then turned off all the mods, and spells seem to pass the candle as they should, however arrows will be stopped with the sound playing if it hits the candle directly. Maybe that's just another part of wonky arrow hitbox detection? [Demonstration](https://i.imgur.com/wz6cMtE.mp4)
The tooltip on candle shouldn't be shown, as for the mod that causes the spell collision to occur, I think it's because of Darker Dungeons mod. The tooltip starts to appear, and the collision with spells appears also.

**Comment by Interkarma** [comment]
Thanks for isolating. Sounds like Darker Dungeons is overriding light prefabs / scripts and adding a collider for some reason. This subsequently introduces weirdness with tooltip mod once the candle is collidable.

I'm not encountering any problems with arrows colliding with magic candle either (which makes sense as candle has no colliders in base game). But as you say, arrows have some other general problems that might be getting involved in your tests. Archery needs a pass before beta is done.

In any case, best to raise issues with magic candle collider with mod author. They'll want to need to check why mod adds colliders to lights.

**Comment by sanscriptum** [comment]
Yup, done and done. I reported it on their nexus page.

**Comment by sanscriptum** [comment]
According to Ralzar, the mod creator, this issue should be addressed in DFU's codebase itself:
`This is likely caused by making candles clickable. Which no one has done before, so there is likely no code that makes sure to differentiate between a candle sprite placed in a dungeon and the candle sprite used by the light spell. This should be solved in the DFU code, if it is the case. InterKarma is aware of it so hopefully a future update of DFU will solve it.`
