### ISSUE TITLE
Run with SDL_VIDEODRIVER=wayland

### ISSUE THREAD

**Issue by michelesr** [Interkarma/daggerfall-unity#2307]
I'm on Arch Linux, and I can run `daggerfall-unity` with `SDL_VIDEODRIVER=x11`, however I'd like to run it using wayland, since sdl2 supports that. When I do that, I get no error message but no window is created at all, the app just hangs.

Any suggestion?

**Comment by petchema** [comment]
Daggerfall Unity uses Unity3D 2020.3 release if I'm not mistaken, the Wayland support seems still experimental;
Does specifying -force-wayland make any difference ?
https://docs.unity3d.com/2020.3/Documentation/Manual/PlayerCommandLineArguments.html

**Comment by michelesr** [comment]
Do I set directly on `daggerfull-unity` flags? e.g.:

```
SDL_VIDEODRIVER=wayland daggerfall-unity -force-wayland
```

**Comment by petchema** [comment]
By bad, looking at the sources again DFU uses Unity 2019.4.28f1
Doesn't change anything, that version already supported the -force-wayland option
https://docs.unity3d.com/2019.4/Documentation/Manual/PlayerCommandLineArguments.html
Wayland support must have been at least as experimental though ;)
I need to check if wayload support has to be compiled in specifically

**Comment by petchema** [comment]
I saw nothing Wayland-related in build options.
Running the game under Wayland, I get the "Desktop is 0 x 0 @ Hz 0" which seem common with Unity3D.
https://wiki.archlinux.org/title/Unity3D#No_window_opens:_Desktop_is_0_x_0_@_0_Hz
Daggerfall Unity may support Wayland eventually when Unity3D support for Wayland improves.
