### ISSUE TITLE
0.13.5 Left click does nothing

### ISSUE THREAD

**Issue by YLemelin09** [Interkarma/daggerfall-unity#2314]
**Describe the bug**
just installed 0.13.5 windows x64. LEft clicking does nothing

**To Reproduce**
Create character. Try to open the first door in the first dungeon. Left click does nothing. Right click does swing the weapon.

**Expected behavior**
Being able to play the game

**Desktop (please complete the following information):**
 - OS: Windows
 - Version [e.g. 0.13.5]

**Additional context**
Installed it on my desktop last night, it worked. But does not work on laptop

**Comment by Interkarma** [comment]
Please use the forums for personal support. Thank you.

https://forums.dfworkshop.net/
