### ISSUE TITLE
incompatible with steam version of daggerfall

### ISSUE THREAD

**Issue by LithRakoon** [Interkarma/daggerfall-unity#2318]
**Describe the bug**
When selecting the steam provided files for use with daggerfall unity theres multiple errors that arrive when using diffrent paths in the
installed folder of daggerfall.
you get this error "Found 'arena2' but its missing one or more .VID files" when using this path:
~/SteamLibrary/steamapps/common/The Elder Scrolls Daggerfall/DF/DAGGER/

and you get this error "Found 'arena2' but its missing ARCH3D.BSA" wit this path:
~/SteamLibrary/steamapps/common/The Elder Scrolls Daggerfall/DF/DFCD/DAGGER/

**To Reproduce**
1. open ''DaggerfallUnity.x86_64"
2. navigate folder of the steam downloaded version of daggerfall
3. open either one of the folders with "arena2" in it
4. get one of the errors described above

**Expected behavior**
daggerfall unity works with the steam provided files, and runs

**Screenshots**

![image](https://user-images.githubusercontent.com/41258148/165625397-c24aaeda-3218-48ad-bd1b-3d0f004c8e46.png)
![image](https://user-images.githubusercontent.com/41258148/165626188-0b87fec0-c77b-4c31-a3f4-a077b30ed515.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Fedora 35

**Comment by jotoho** [comment]
I have repeatedly heard on reddit (didn't verify this myself) that Bethesda has uploaded the oldest and buggiest version of Daggerfall (release 1.0) to Steam. If that hasn't been fixed since then, it's probably Bethesda's fault.

**Comment by JayH2971** [comment]
Hello! As noted by other users, this is a problem with Bethesda offering a sub-standard version of their game. Please follow these instructions instead: https://forums.dfworkshop.net/viewtopic.php?f=5&t=2360&p=27538#p27538. You can extract the DaggerfallGameFiles to your Steam Daggerfall folder if that makes it easier for you, or place it in a different folder.

**Comment by Interkarma** [comment]
I've already committed to supporting Steam version in a future release. :)
