### ISSUE TITLE
Text of GUI buttons is not middle-aligned

### ISSUE THREAD

**Issue by nxtpl** [Interkarma/daggerfall-unity#2326]
Hi!
The interface text written on buttons is not centered vertically. As I see in the code, it should be - but it's not working properly.
Maybe because of the border? Or some rounding? Totally no idea.

I don't know how to fix it properly, but tested it with adding an integer value of 2 and it looks much better.
Maybe this will help someone to resolve this issue ;)

![dfu-button-text-alignment-bug](https://user-images.githubusercontent.com/4273740/167704552-0b40304b-cfab-430a-8042-55a9ffa4d05e.png)

**Comment by KABoissonneault** [comment]
Have you tried testing this with the SDF Font turned off? I suspect it could be broken by your suggested change, and maybe it's SDF Font that needs fixing

**Comment by nxtpl** [comment]
Just tried with SDF font off and the problem still exists

![obraz](https://user-images.githubusercontent.com/4273740/167713782-a00540fb-7683-4b06-af2a-5b7eba6c08b5.png)

**Comment by KABoissonneault** [comment]
Could it be that you feel the text is 2 pixels off because the text width includes the shadow of the last letter? In your example, "Advanced" clearly has 2 pixels of padding on both sides, which means it is centered. Yet, the text _feels_ biased to the left because the brighter parts are more to the left.

**Comment by nxtpl** [comment]
The issue is with vertical alignment (up/down), the right-left centering is okay :)
The text should be a little down from the top border.

**Comment by Interkarma** [comment]
This is perfectly middle-aligned based on the typeface properties. It helps to visualise the total label area with a solid background.

![image](https://user-images.githubusercontent.com/10426244/167739726-41bf50cc-a71e-48dc-9cbc-527e0254326b.png)

In typography this space is accounted for by the tail / descender area of certain glyphs. It's important to account for these typeface properties as it will render differently in other languages (in English vs. Kanji for example) and depending on the text. Here's an image from the TextMeshPro docs that helps visualise what goes into calculating line height.

![image](https://user-images.githubusercontent.com/10426244/167740802-d5c6e721-9281-48df-92a3-58547aed979c.png)

The classic 8-bit bitmap font doesn't have proper tail / descenders, rather each glyph has fixed dimensions and are drawn to give the appearance of descenders, but these labels are still technically perfectly middle-aligned inside the button area based on typeface height.

![image](https://user-images.githubusercontent.com/10426244/167740586-af1a613d-114d-416b-967e-355cd4b25aeb.png)

Could this be better and make adjustments depending on whether something is upper or lower case, or has descenders or not? Sure, but it's not an easy thing to make work with all languages and character sets. Maybe adjusting for descender area might work universally, but I'll have to test against glyphs in other languages. There would also need to be a separate pathway for classic fonts as they have no descender properties like modern TMP/SDF font data. It's unfortunately a much deeper problem than adding +2 so it looks good only under one set of conditions.

I'll leave this one open as a possible improvement and take a look at some time in future. But it's considered low priority at this time, and I don't promise anything.

Cheers.
