### ISSUE TITLE
Random crashes between area transitions

### ISSUE THREAD

**Issue by Star-X555** [Interkarma/daggerfall-unity#2327]
**Describe the bug**
When changing between outdoor and indoor areas, the game will sometimes just randomly crash.  Seems to be no rhyme or reason, it just does.

**To Reproduce**
Totally random, just happens while playing.

**Expected behavior**
Doesn't crash.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux Universal (using Arch Linux)
 - Version: 0.13.5

**Additional context**
Log file included.

Game is modded, but nothing in the crash section of the log implies any of the mods.  I've also tried turning off a huge number of them, still eventually randomly crashes.
[Player.log](https://github.com/Interkarma/daggerfall-unity/files/8665904/Player.log)

**Comment by Interkarma** [comment]
Hi there. Please use the forums for personal support.

https://forums.dfworkshop.net/
