### ISSUE TITLE
QoL train mercantile skill by value of items sold

### ISSUE THREAD

**Issue by Krwak** [Interkarma/daggerfall-unity#2331]
**Describe the issue**

Mercantile skill is trained when "one enters into negotiations with a merchant, attempting to buy or sell an item at the best possible price." therefore it only promotes selling items one by one to maximize the training potential. Which is a problem cause it's a lot of mindless clicking.

**Expected behavior**

I propose changing it to train mercantile by basic value of items sold. Not yet clear on the exact ratio though. Please suggest in comments if you have an idea of balanced ratio.

**Desktop (please complete the following information):**

 - OS: Windows
 - Version 0.13.5

**Comment by KABoissonneault** [comment]
Mods can overwrite the Trade window and change how much Mercantile experience is gained from the transaction. No sense making an editorial decision here when a mod already suffices.
DFU has done such changes in the past, but they were mostly for entirely broken features. Leveling Mercantile is not necessary (and not really useful), so the fact that leveling it is tedious is not a blocker issue.
If you have other balance suggestions, may I suggest the [Mods & Features General](https://forums.dfworkshop.net/viewforum.php?f=12&sid=39b3fe8f70c239a8be9926730594c78f) section on the dfworkshop forums?
