### ISSUE TITLE
Main Quest mission requirement ordering

### ISSUE THREAD

**Issue by hfc2x** [Interkarma/daggerfall-unity#2332]
Not an issue exclusively affecting Daggerfall Unity, but more an oversight that has always been a part of Daggerfall's main quest (please don't kill me if this has been addressed already).

Morgiah's Wedding (S0000004) mission contains relevant plot information that's meant to lead the player to the emperor's letter being in possession of Gortwog, and this mission automatically starts when the player reaches level 3, with no context as to why Princess Morgiah specifically addresses the player, and just leading the player directly into the emperor's letter, a seemingly endgame event. There's no setup or investigative work the player can do, which they're explicitly asked to do at the start of the game. It just happens out of nowhere. However, The Emperor's Courier (S0000012) seems to have been originally a prerequisite for starting this one, because it actually gives the player some clues on how to possibly find out what happened to the letter, and leads the player into talking to Morgiah about this issue.

The problem is that the latter mission can only be started after the player reaches level 5, and playing said mission results in the player being hinted to start a mission they have already completed. I suppose they also changed it so it's not a requirement because of the alternative ways you can fail that mission.

Another quest that leads you to the letter is Barenziah's Book (S0000011), which is an optional quest. But said quest happens at level 9, and you also require a reputation of 15 with Queen Barenziah as well.

I think the level requirements for these quests should be rearranged, with S0000004 being the one happening at level 9, S0000012 happening at level 3, and S0000011 happening at level 5. It makes more sense from a story perspective. Also making S0000012 a requirement (either complete successfully or fail it) for S0000004 to even start.

There's a Daggerfall retrospective on YouTube that explains this in far more detail: [https://youtu.be/16YEMiNxNCs?t=8926](https://youtu.be/16YEMiNxNCs?t=8926)

Again, apologies if this has already been addressed.

**Comment by JayH2971** [comment]
From a gameplay perspective, I completely agree. It makes little sense for Cyndassa to lead you to Morgiah, who's probably the first person you ever spoke to after Brisienna for the MQ.

For changing it in core Daggerfall Unity, that's probably not the best approach. It'd be a big variation on the original main quest, which would take new information in the community, a drastically different starting path, etc. It isn't in line with a Daggerfall recreation. This could very easily be done by a mod, which is more in harmony with DFU's approach.

**Comment by Interkarma** [comment]
I appreciate the idea, but agree with Jay this falls more into mod territory.

**Comment by fosskers** [comment]
Sorry for the resurrection. Was such a mod ever made? I didn't manage to find anything on Nexus.

**Comment by JayH2971** [comment]
No one has.

**Comment by fosskers** [comment]
Notes for a potential future version of myself:

- http://www.dfworkshop.net/projects/daggerfall-unity/modding/features/
- https://forums.dfworkshop.net/viewtopic.php?f=22&t=277

For the pros who may wander by here, please let me know if there are better resources for learning how to mod.

**Comment by JayH2971** [comment]
I recommend this: https://dfu-modding.fandom.com/wiki/Making_Mods

**Comment by fosskers** [comment]
Nice, thank you. I imagine patching _existing_ quests shouldn't be too complicated.
