### ISSUE TITLE
Character can not rotate after pressing Enter in free text dialogues

### ISSUE THREAD

**Issue by AKryukov92** [Interkarma/daggerfall-unity#2335]
Daggerfall unity beta v0.13.5 installed nearly a week ago.
Windows 10
No mods

I have met this issue twice.
First time in Daggerfall castle. Guard asked me something about rules and open textbox.
Second time was in Shedungent (Wrothgarian Mountains). Skeleton statue guarding the door asked for some text.
If you close this dialog by "Esc" then all OK.
But if you type text and press "Enter", then character becomes unable to rotate camera with mouse.
![image](https://user-images.githubusercontent.com/24266616/168412036-d1cc2803-d0a0-4940-a3a0-2832b5da05a0.png)

Opening dialog again and pressing "Esc" don't help.
Loading the save don't help.
Saving and restarting the game application helps. Thats why I don't attach savegame.

I expect that camera should rotate after I type some text to this dialog and press "Enter".

**Comment by Interkarma** [comment]
The Enter key is also the "Activate Cursor" keyboard. Use this key to toggle active cursor on/off. This is same behaviour and is expected.

![image](https://user-images.githubusercontent.com/10426244/168412578-aaad4705-2d31-4d05-b416-3d406dade33e.png)

Please use the forums for gameplay questions and personal support. Thank you. :)

https://forums.dfworkshop.net/

**Comment by AKryukov92** [comment]
Thank you for super-fast response. Pressing Enter again actually helps.
Though, I think in this case pressing Enter is not expected to work as hotkey.
I expect it to confirm entered text and nothing more. So it feels like bug.

May be there should be some message "cursor activated" to emphasise that it is happened intentionally?

**Comment by Interkarma** [comment]
I agree it's quirky. The behaviour does match classic though and for now no plans to change.

A workaround if you don't plan on using activate cursor for anything (e.g. with large HUD), you can clear keybind by right-clicking on the field in screenshot above. This stops the behaviour of cursor becoming active when not intended.

I will take your feedback on board. Thank you!
