### ISSUE TITLE
Inconsistency between displayed AC and to-hit formula for enchanted armor

### ISSUE THREAD

**Issue by KABoissonneault** [Interkarma/daggerfall-unity#2342]
"AC" is the number displayed on the paperdoll when equipping armor. "Armor value" is the actual contribution to the to-hit formula provided by armor.
As a rule, AC gives you 5 armor value - it reduces hit by 5% for each AC point.

Currently, this rule breaks for `IncreasedArmorValueModifier` and `DecreasedArmorValueModifier`. `StrengthensArmor`, `BadReactionsFrom`, and `WeakensArmor` change these values by 5. 
The inconsistency is that `IncreasedArmorValueModifier` and `DecreasedArmorValueModifier` change both the displayed AC and the hit chance by 5 (see `PaperDoll.RefreshArmourValues` and `FormulaHelper.CalculateArmorToHit`). 

Having an AC of 20 reduces hit by 100, but add a +5 enchantment, and suddenly you have an AC of 25 that reduces hit by 105.

Classic does change the displayed AC by 5 for these enchantments, but I don't know about the effect on hit.

Proposed solutions:
1. if this is consistent with classic, do nothing (mods can override the `CalculateArmorToHit` formula if they don't like this)
2. Multiply `IncreasedArmorValueModifier` and `DecreasedArmorValueModifier` by 5 in the default `CalculateArmorToHit` formula (visibly consistent with classic)
3. Divide `armorMod` by 5 in `Paperdoll` (no impact on gameplay)

My favored solution is #2, as ±5 hit from the enchantment is pretty weak.

**Comment by Interkarma** [comment]
I recall some conversations and tuning around this to match behaviours, but can't dig up them up right now. Still, there's always a chance I made a mistake when implementing and nobody has caught it until now.

I'm not opposed to the change in 2 however, and I agree the enchantment is pretty weak. Something to investigate for sure.

**Comment by Interkarma** [comment]
Feedback on this one. I can't find any conversation history to confirm IncreasedArmorValueModifier and DecreasedArmorValueModifier should _not_ be subject to multiplier. I'll consider this a bug in my implementation and apply *5 as per solution 2 in Kab's issue.
