### ISSUE TITLE
Suggestion: Add xBRZ as a texture filter option

### ISSUE THREAD

**Issue by Star-X555** [Interkarma/daggerfall-unity#2344]
Bilinear and Trilinear don't even remotely get close to the level of high def texture filtering as xBRZ.  AFAIK it is the texture filtering algorithm that has the best ratio of quality to performance, and can be used in realtime.  Most advanced sourceports feature an option to scale textures/flats/whatever with xBRZ and benefit immensely visually from it.  Any chance DFU might be able to get that added at some point in the future, distant or otherwise?

Example sprites, for reference:
https://a.fsdn.com/con/app/proj/xbrz/screenshots/xBRZ_Doom.png

**Comment by Interkarma** [comment]
Hey there. :) Thank you for the suggestion. I have no plans to add upscaling options to DFU. This would more rightly fit in mod territory. You could try raising in Mods & Features General on forums and see if anyone salutes.

https://forums.dfworkshop.net/viewforum.php?f=12
