### ISSUE TITLE
0.13.5, QUESTING: "create foe msg ####" allows duplicate message display

### ISSUE THREAD

**Issue by JayH2971** [Interkarma/daggerfall-unity#2352]
**Describe the issue**

I'm writing a custom quest that spawns two enemies at irregular intervals:

`    create foe _vamw1_ every 25 minutes 1 times with 20% success msg 1011`
`    create foe _vamw2_ every 17 minutes 1 times with 15% success msg 1011`
    
Msg 1011 fires when the first enemy spawns. However, I expected it to only fire once; the game currently shows message 1011 when the first instance of _each_ enemy spawns, so in this case I get two of message 1011 at two different times.

**To Reproduce**

A quest file is attached: [JHKN201.txt](https://github.com/Interkarma/daggerfall-unity/files/8878072/JHKN201.txt)
1. Start the quest with the console.
2. Loiter until the ghosts/wraiths spawn.
3. The 1011 message will appear at the first spawn of each enemy.

**Expected behavior**

Message 1011 should appear only once, as is the rule in the quest engine.

**Comment by Interkarma** [comment]
The way this is implemented now is it's the "action" that only presents text once. The text resource itself is just data. So each of those "msg 1011" actions should only display text once, it's just they both use the same text data.

This made more sense to me than actually locking out the data. If that's the preference, I can no doubt accommodate that. :)

**Comment by JayH2971** [comment]
My alternatives to attempt this same effect in this quest and others would be sub-optimal, I think. I believe the change would be good here; I'm certain the same issue will pop up for myself and others in future quests, and having the text box appear only once would be the best way.

**Comment by KABoissonneault** [comment]
My concern is that I think either behavior can be desirable. Whichever one we make the default, we need to ask: how hard would it be to get the other one? IMO the one that's easiest to get through another workaround should not be the default

**Comment by JayH2971** [comment]
Following that logic, a fix is needed. I'll demonstrate:

1. If I want a message to only appear once when multiple groups of enemies spawn, I cannot accomplish this currently.

2. If I want a message to appear at the first spawn of each type of enemy, I can do this.

If we were to change it:

1. If I want a message to only appear once when multiple groups of enemies spawn, I would be able to do this; and

2. If I want a message to appear at the first spawn of each type of enemy, I would be able to do this. (I can create a different message block for each enemy type with duplicate contents, thus showing  the same message each time).

Therefore, the fix I recommend opens more possibilities rather than closing any.

**Comment by BadLuckBurt** [comment]
> The way this is implemented now is it's the "action" that only presents text once. The text resource itself is just data. So each of those "msg 1011" actions should only display text once, it's just they both use the same text data.
> 
> This made more sense to me than actually locking out the data. If that's the preference, I can no doubt accommodate that. :)

I brought this up briefly on the forum but I didn't fully understand the issue at that time. I 'fixed' the quest by dropping the msg id part from the second createfoe call but then Jehuty explained that the actual quest has random spawn chances so there is no guarantee which enemy would spawn first so I get it now.

Instead of tracking the message id in the action and unsetting it after it's shown once, I think you can easily solve this by having the task (the action's parent) keep track of the message ids it has displayed so far or the reverse (keep a list of the message ids it's still allowed to display). 

I may have taken this too literal but it sent my alarm bells ringing:

> Once the fix for this issue is live, messages can only be presented once - ever.

The 'once - ever', is that once per quest, once per task?

**Comment by JayH2971** [comment]
> Instead of tracking the message id in the action and unsetting it after it's shown once, I think you can easily solve this by having the task (the action's parent) keep track of the message ids it has displayed so far or the reverse (keep a list of the message ids it's still allowed to display).

If this is implemented, I believe this would cause no problems with classic Daggerfall quests. I don't expect many, or perhaps any, problems with other quests I've written either, so if this is possible, I support it.

**Comment by Interkarma** [comment]
> The 'once - ever', is that once per quest, once per task?

@BadLuckBurt Per message block. Meaning once a message is displayed it can never be shown again. This is actually how classic operates. I tried to make things more flexible and implemented this based on task arming instead, so DFU is more flexible here.

This actually works OK almost all of the time. The problem @JayH2971 presents here is with the msg suffix and the assumption it would work like classic and lock out the text data once presented.

I'll solve this problem in a way that compromises with Burt and retains some flexibility.

**Comment by BadLuckBurt** [comment]
Thank you. I haven't really gotten to the quest writing yet but I know that when I do, I'll need reusable dialogue with the branching I want to implement.
