### ISSUE TITLE
0.13.5, ==symbol_ mismatch from classic

### ISSUE THREAD

**Issue by JayH2971** [Interkarma/daggerfall-unity#2368]
In the quest A Mix-Up (yep!), a reference is made to ==priest_ in dialogue:
[Github link](https://github.com/Interkarma/daggerfall-unity/blob/1b3bc813c0c332d5467622b61c4d6d84927d59a3/Assets/StreamingAssets/Quests/K0C00Y06.txt#L660), [UESP link](https://en.uesp.net/wiki/Daggerfall:A_Mix-Up)

![generictemple](https://user-images.githubusercontent.com/37541932/176271475-c991613a-d28d-4c6e-bf48-2f5d79b4f560.jpg)

DFU currently interprets this data as "Generic Temple," whereas UESP says it should resolve to a temple of some kind:

`Dear (priest's name),
Ignore my last letter when I applauded you
for your enormous contribution to (priest's temple).
That (gem) that you said was a donation
was stolen from (employer's name). If
it becomes known that the gem was stolen for our
temple, our prestige in (region) would
greatly suffer. (Noble's name) already
hates us, and with (his/her) influence on the royal
family, (priest's temple) will have
much for which to answer.
We will discuss at our next meeting what
appropriate castigation this situation merits.
Do not think of challenging the temple.`

I attempted a few small fixes like changing it to =priest_ or __priest_, but I couldn't get a temple resolution from these changes. An engine change seems feasible for this.

**Comment by andreiserbanrazvan** [comment]
Hello @JayH2971 any chance you have a save game for this ?

**Comment by JayH2971** [comment]
No, this was reported to me by a third party.

**Comment by Interkarma** [comment]
I believe the issue here is the same basic problem as #2393 where _priest_ Person resource could be assigned "Generic Temple" faction.

This should also be resolved by 91fc7ae.
