### ISSUE TITLE
Travel map & Marking issue & improvement

### ISSUE THREAD

**Issue by AssassinLV** [Interkarma/daggerfall-unity#2400]
So there are 1 issue and 1 improvement
Let's go with issue:
Marking (Middle mouse click on Travel map objects) currently are not persistent on saves, it would be nice if it would be persistant - so mark would not dissappear after loading the game next day.

Improvement:
Tooltip on cities adding list of known building types (only those that you had visited) For example in city XYZ I've discovered (entered in them or people added on my map) the general shop and 2 blacksmithes. Then in city Travelmap a tooltip would say:

**XYZ**
- 2x Blacksmiths
- 1x General Shop
- 3x Unknown Guilds
- 2x Unknown Shops
- 1x Unknown Tavern

The list migth be a bit lengthy but would show to me - if the city is the one I want to be. Also not sure about unknown part - maybe that could be skipped or added as known for as long you had ever been in that city..

**Comment by Interkarma** [comment]
>Marking (Middle mouse click on Travel map objects) currently are not persistent on saves

This sounds related to a mod (Travel Options?). Middle mouse has no function on the travel map in DFU. This is an issue tracker for core game, any mod questions should be raised with mod creator on Nexus or Forums.

> Tooltip on cities adding list of known building types

There are no plans to add new functionality like this to the core game. It could possibly be added to a mod (e.g. Travel Options). But again, this should be raised with the mod creator.
