### ISSUE TITLE
Cinematics Closing/Skipping When Running 0.14.4 Via Steam

### ISSUE THREAD

**Issue by PhluXx1** [Interkarma/daggerfall-unity#2428]
**Describe the issue**
Please be advised I've discovered an issue with Daggerfall Unity when adding it as a non-Steam game and playing it. Cinematics will close at random as if being skipped with a key press. I have replicated this issue and confirmed it does not occur if Daggerfall Unity is launched normally. Initially I thought it was an installation or mod issue but have ruled this out, after troubleshooting the issue I've confirmed it only occurs via Steam. I've also verified that this is not a problem with the Vanilla version of Daggerfall available through the Steam store.

**To Reproduce**
1. Launch Steam.
2. Click Library
3. Bottom left click + icon Add Game
4. Choose Add a Non-Steam Game
5. Browse to DaggerfallUnity.exe and add
6. Once successfully added to steam launch Daggerfall Unity
7. Play game and let cinematic splash screen play it should automatically close at random
8. Create new character and watch first in-game cinematic which should also close at some point.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64bit 21H2
 - Version 0.14.4 BETA

**Comment by Interkarma** [comment]
Hi, please use the forums for troubleshooting personal support problems. Adding DFU as a non-Steam game is a user-side configuration unrelated to the game itself.

The recommended method for setup is using the DaggerfallGameFiles method below.

https://forums.dfworkshop.net/viewtopic.php?p=27538#p27538

**Comment by PhluXx1** [comment]
I'm not requesting support I'm reporting a interoperability bug with your software and the biggest game launcher in the world (your software is still in beta AKA the phase to report such bugs so that you may improve it). Again it's a bug report I don't need support also raising this issue in the forums will yield no results as it's a bug. Whether you want to address the bug or not is entirely your own prerogative however. Thank you for your reply.

**Comment by petchema** [comment]
Currently mouse clicks any keyboard event (even pressing modifier keys like Alt(*)) will abort cinematics; If this problem happens without any interaction with the keyboard, then I assume the Steam overlay generates phantom events, or otherwise messes with events handling.
Filtering what keys can interrupt cinematics could help, assuming that's the only problem overlay causes.

(*). I know this because sometimes Twitch streamers want to adjust volume or otherwise switch to another app while cinematics are playing, but Alt-Tab immediately interrupt playback

**Comment by jefetienne** [comment]
In that case, we could definitely exclude keyboard modifier keys from being used. Cinematics use AnyKeyUp() or something similarly named.

**Comment by PhluXx1** [comment]
> Cinematics use AnyKeyUp() or something similarly named.

Limiting cinematics skipping to Esc and Enter would likely solve a lot of potential issues.

**Comment by KABoissonneault** [comment]
Add left-click and Space, and I agree. I get that some people will accidentally skip cutscenes trying to put focus on the game, but I'm sure many users have already taken the habit of clicking through everything, and I'd rather not force people to change habits

**Comment by petchema** [comment]
Ninja'd by @KABoissonneault, I agree with that

**Comment by petchema** [comment]
Commit 76f6d2d6 introduced some regression for me, I can no longer bind modifier keys to actions in Controls.
Forums: https://forums.dfworkshop.net/viewtopic.php?t=5944

**Comment by jefetienne** [comment]
> Commit [76f6d2d](https://github.com/Interkarma/daggerfall-unity/commit/76f6d2d6f01ecfc23c00767383f17cef399dc1af) introduced some regression for me, I can no longer bind modifier keys to actions in Controls. Forums: https://forums.dfworkshop.net/viewtopic.php?t=5944

Oops, my mistake there. It's an easy fix, and at least as a workaround I can say just editing the Keybinds.txt file will work.
