### ISSUE TITLE
Only certain mod settings load in game

### ISSUE THREAD

**Issue by DeathWrench** [Interkarma/daggerfall-unity#2429]
Clicking on the top left in the pause menu only shows certain mods, some mods that have settings are missing. This isn't that bad but having to restart the game every time you forget to change something can be cumbersome.

**Comment by Interkarma** [comment]
Only mods which support `HasSettings` and `LoadSettingsCallback` are available to configure in-game via this menu. This isn't an issue in Daggerfall Unity, simply not all mods support in-game changes.

It's best to raise this with individual mod authors either on forums or Nexus, and ask them to support this. Depending on the mod, it might not be possible to change settings in-game.
