### ISSUE TITLE
0.14.4: %god fails to resolve for Fighters Trainers

### ISSUE THREAD

**Issue by JayH2971** [Interkarma/daggerfall-unity#2430]
0.14.4 with no mods, testing a custom quest. The game chose Fighters Trainers as a local temple location. Upon entering, a message containing %god is supposed to fire, but the quest crashes instead. The following appears in the player log:

> Restoring scene: DaggerfallInterior [MapID=77960988, BuildingKey=197120] 
> (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 39)
> 
> [RLQtempleescort] Error in quest follows. Terminating quest runtime. 
> (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 39)
> 
> Specified argument was out of the range of valid values.
> Parameter name: There is no Divine that matches the factionId: 41 
> (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 39)

Since the game can't produce an appropriate divine to this location, the quest dies. I'm attaching a repro save, the quest file, and the player log.

[God Crash.zip](https://github.com/Interkarma/daggerfall-unity/files/9584187/God.Crash.zip)
[Player.log](https://github.com/Interkarma/daggerfall-unity/files/9584188/Player.log)
[RLQtempleescort.txt](https://github.com/Interkarma/daggerfall-unity/files/9584189/RLQtempleescort.txt)

**Comment by KABoissonneault** [comment]
Is this in Hammerfell? Just curious if the rumor that Hammerfell FG halls are temples is true

**Comment by JayH2971** [comment]
Yes, that's the key. Hammerfell uses Fighters Trainers buildings, and this one was chosen as a temple.

**Comment by Deeznutzzxx** [comment]
i have a question. Its kinda unrelated though, but where do put this file the (master file) I downloaded the dfu unity.exe file from there website and that worked of course, and it contains only a few of things inside the master file. Where exactly do I put this master file?
