### ISSUE TITLE
Non-ASCII characters are not rendered in BOOKs

### ISSUE THREAD

**Issue by ravea** [Interkarma/daggerfall-unity#2451]
If you edit a book using DF Tools, HEX or a text editor and insert, for example, Russian characters, then they do not exist, as if they did not exist.

Book from https://www.nexusmods.com/daggerfallunity/mods/299

[YELOBOOK.TXT](https://github.com/Interkarma/daggerfall-unity/files/9826961/YELOBOOK.TXT)

The problem is not with fonts, example:
![image](https://user-images.githubusercontent.com/113205164/196874210-22bff114-b4f7-4ec8-88cd-daf7601506e8.png)

**Comment by Interkarma** [comment]
Hey there. :) Books are not yet part of localization. This is still under development. I'll post more details about book localisation as this continues in the future.
