### ISSUE TITLE
Build failure Windows/Linux

### ISSUE THREAD

**Issue by noabody** [Interkarma/daggerfall-unity#2468]
```cs0234 namespace localization does not exist in unityeditor Assets/Scripts /Game/StringTablePatcher.cs``` clean build from git with appropriate Unity version.

Identical behaviour to [The type or namespace name 'Localization' does not exist in the namespace 'UnityEngine'](https://forum.unity.com/threads/the-type-or-namespace-name-localization-does-not-exist-in-the-namespace-unityengine.932901/#post-7370627)

Was able to resolve by stealing this piece of code from the localization example called ```Loading Strings```.  Absolutely no idea why that allows a build to be successful.

Adding this statement allows it to work:
```diff
diff --git a/Assets/Scripts/Game/StringTablePatcher.cs b/Assets/Scripts/Game/StringTablePatcher.cs
index ea7c66364..978956741 100644
--- a/Assets/Scripts/Game/StringTablePatcher.cs
+++ b/Assets/Scripts/Game/StringTablePatcher.cs
@@ -15,6 +15,7 @@ using UnityEditor;
 using UnityEditor.Localization;
 using UnityEngine.Localization.Settings;
 using UnityEngine.Localization.Tables;
+namespace UnityEditor.Localization{}
 
 /// <summary>
 /// ITablePostprocessor string table patcher for in-game text.
```

**Comment by Interkarma** [comment]
Hi, thanks for raising. I can produce the same error when attempting to build addressables.
The new code here isn't required except as a once-off and as a future reference. I've commented out the not-required using statements and I'm able to build addressables + game normally again now.
If you still have issues, please try a fresh clone from master into a new folder then attempt building addressables first, then game.

**Comment by karljj1** [comment]
Try removing  'using UnityEditor.Localization' instead 😉

**Comment by Interkarma** [comment]
Hey Karl! Yep, I've already removed those using statements causing the issue. Cheers.
