### ISSUE TITLE
Allow mouse sensivity more than 8 or custom

### ISSUE THREAD

**Issue by mr-sihc** [Interkarma/daggerfall-unity#2475]
Allow the mouse to be
[in range 1 - 20 in the ui slider] and/or
[allow console commands, custom number input on the slider or editing the config manually to be higher (uncapped)],
right now, if i edit the config, it will reset to 8 which sucks...

this should be fairly easy, and would help me a lot!

**Comment by Interkarma** [comment]
The 8x multiplier is in fact very high. If you're experiencing delayed mouselook with maximum multiplier, there's probably something else going on, e.g. low performance / poor framerate.

Please try setting up the game fresh using the recommended method below. Do not install any mods yet, or use any third-party installers like GOG Cut that come pre-packaged with mods.

https://forums.dfworkshop.net/viewtopic.php?p=27538#p27538

If you still experience mouse issues, Help & Support on the forums is the best place to try and troubleshoot personal support issues. Please include your system full specifications in your post, along with the DFU version you're using and how the game was installed.

**Comment by mr-sihc** [comment]
the game runs fine, no fps issues, no mods, installed manually
all fine
except mouse
maybe its a linux problem, but 8 isn't very high

i can send a video

**Comment by mr-sihc** [comment]
https://user-images.githubusercontent.com/85245131/206878041-a1fcd75d-5caa-4f99-b11d-3b3431f5684c.mp4

(is actaully .mkv but github wont allow mkv file extension)
the recording makes it look higher sensitive than it is because of framerate

**Comment by Interkarma** [comment]
Please use the forums for personal support questions. In your post, be sure include your system full specifications, along with the DFU version you're using and how the game was installed. The community is very helpful, and someone will try to help.

https://forums.dfworkshop.net/viewforum.php?f=5

This is a bug tracker for the development team to follow accepted bugs. It's not for support or feature requests.

**Comment by mr-sihc** [comment]
okay...

**Comment by Interkarma** [comment]
Thank you. :) I have heard of some weird issues with mouselook input capture and Linux before. It seems to be specific to some distros and Unity engine capturing mouse input, rather than just DFU. If you detail your Linux environment in forum post, one of our Linux users might be able to offer some targeted help.
