### ISSUE TITLE
Pixel With No Region ID (Wrothgarian Mountains)

### ISSUE THREAD

**Issue by spockthewok** [Interkarma/daggerfall-unity#2484]
Originally reported on the DFU discord in December but could see no report here or on the forums so am reporting myself. Confirmed by Kamer to be a vanilla issue:

![1](https://user-images.githubusercontent.com/108099948/211329790-735a4aef-5275-4fab-8076-0681e5a8dd21.PNG)

**How to reproduce**:

1. Head directly West from Vandale in the Wrothgarian Mountains
2. Watch as your fatigue drains over and over, soft-locking your character

Below is a screenshot with coordinates from the tdbg command (the only active dfmod is Basic Roads for easier navigation):

![image](https://user-images.githubusercontent.com/108099948/211331444-54d5edd2-26c3-45fe-a7f8-2da8414fd870.png)

**Comment by Interkarma** [comment]
This is handled in DFU as of 0.15.0. There's a post on the first page of Help & Support in forums 

https://forums.dfworkshop.net/viewtopic.php?t=6003

**Comment by spockthewok** [comment]
You're quite right, I completely missed that post, sorry for the double report!
