### ISSUE TITLE
Cannot Access Hidden Folders When Setting Daggerfall's Game Files Path

### ISSUE THREAD

**Issue by RolandMarchand** [Interkarma/daggerfall-unity#2487]
## Info
- Version: 0.14.5
- OS: Linux fedora 37 6.1.6-200.fc37.x86_64w
## Issue
When launching DFU for the first time, it asks for the path to the Daggerfall game files. Though, my files are in a hidden folder `$HOME/.steam/...`, which is unable to be selected in DFU's file browser. I am also unable to type it out in the path box.
### Show/Hide Button
DFU's file browser could have a "show hidden files" checkbox that could be toggled on and off.
### Editable Path Box
Alternatively, I could have the option to manually edit the path in the path box.

**Comment by Interkarma** [comment]
Hey there :)  Please use the forum for individual support setting up the game.

https://forums.dfworkshop.net

**Comment by dogue** [comment]
Personal opinion: I don't think this should have been dismissed as an individual support issue.

The default install location for Steam in Linux is under `~/.local/share/Steam/steamapps/common` (symlinked to `~/.steam`), which means you cannot set the path as `.local` is a hidden directory.

I don't think the suggested solutions in the original report are unreasonable.

**Comment by KABoissonneault** [comment]
Yeah it seems DFU explicitly filters out Hidden folders there. Maybe it makes sense to remove clutter in many cases, but if it's common to install DF under a hidden folder, then the toggle makes sense too. Putting this back for the next version
