### ISSUE TITLE
Weird GPU usage on 0.14.5 beta

### ISSUE THREAD

**Issue by SomeWhiteGuyy** [Interkarma/daggerfall-unity#2490]
I originally was using the 0.13.5 version of daggerfall unity and decided to update with a complete fresh install. i noticed with 0.14.5 beta however it ends up using a weird amount of GPU after some time. when i use to play on 0.13.5 beta it basically ran with idle temps and usage on the GPU. now after about 20 minutes of having daggerfall unity loaded the gpu temps rise to a point where its nearly maxing out the safe threshold. 

I'm not sure if this is common or whats happening. mods do not seem to be a culprit to the increase either, this happens with and without mods installed

**Comment by SomeWhiteGuyy** [comment]
noticing i might be related to the having graphical quality to the highest setting, setting the graphics down from "fantastic" to "beautiful" has helped keep the temps and usage more stable

**Comment by Interkarma** [comment]
Hey there. :) Please use the forums or Discord for individual support.

Forums:
https://forums.dfworkshop.net

Discord:
https://discord.com/channels/559842137374457876
