### ISSUE TITLE
Shop merchandise shelf incorrectly recognized as private property

### ISSUE THREAD

**Issue by hyperhippy92** [Interkarma/daggerfall-unity#2494]
![image](https://user-images.githubusercontent.com/38664702/217362041-565dc4ce-e74b-4b73-b036-2bfa335b7923.png)
in DOS Daggerfall, the shelf I am pointing to in the screenshot enclosed was only private property if you clicked the cupboard below it, but the display case on top of it was supposed to register as a store interface. In DFU as currently provided, the entire piece of furniture, including the storefront, counts as private property, and I am given a warning whether or not I want to look through it.

**Comment by Interkarma** [comment]
Hey there. :)

There is no distinction between the model based on top or bottom half. If this is something you'd like to demonstrate in classic, please provide a classic save to forums in Help & Support that demonstrates issue.

**Comment by Interkarma** [comment]
Something that could be happening is that classic uses texture to capture click (as it does with static doors), so there's a difference when clicking the top or bottom parts of model.

Using the texture to differentiate model parts wouldn't be compatible with mod system, as modders replace the object and textures entirely. This will need to continue using model ID as it is now.
