### ISSUE TITLE
Stuttery character rotation under Linux

### ISSUE THREAD

**Issue by Mortecha** [Interkarma/daggerfall-unity#2498]
**Describe the issue**

I started a fresh game under the Linux build of the game as I dabble with Fedora and wanted to play. So I began a new game and in the first dungeon, the game seems to stutter whenever the character is rotating. I suspect this issue is deeper than this project and is instead a Unity thing, but I'm not sure yet.   

**To Reproduce**

1. Create a dual boot machine with Fedora installed as the 2nd OS
2. Download and Run the game
3. Create a new character, (Loading an existing save will probably also reproduce the issue)
4. Rotate the character around

**Expected behavior**

Smooth character rotation is expected, just like when played under Windows

**Screenshots and Logs**

I could probably make a video of it if required. 

**Desktop (please complete the following information):**

 - OS: Fedora 37 running the release version of the game
 - Version 0.14.5

Thanks in advance for any consideration:)

**Comment by petchema** [comment]
You'll probably need to make a video, I use Linux as my primary OS, and as far as I can tell the game runs perfectly smoothly. Maybe you have some background process periodically using resources or something, that this is most noticeable when view rotates or something.

Also, as it is now your request lands in user support requests, and should be submitted thru the forums; 
https://forums.dfworkshop.net/viewforum.php?f=5

**Comment by Mortecha** [comment]
I'll look into it further, thank you for the reply and the advice:)

Kind regards,

- Sam
