### ISSUE TITLE
Blind accessibility?

### ISSUE THREAD

**Issue by Tetrismonster** [Interkarma/daggerfall-unity#2499]
Hi.
I hope everything is going well.
I'm a blind gamer who discovered this game recently, and was wondering if someone might be willing to create a mod to allow us to be able to play this game.
Unity does have an accessibility pluggin to pipe text to the screen reader or sapi, and various audio cues would allow us to know what's going on.
For more info on how we play games, visit:
forum.audiogames.net.
I'd love to play this game, and if anyone might be willing/able to do this, that would be great.
Thanks in advance.

**Comment by Interkarma** [comment]
Hey there. :) A better place to discuss mod requests is on the DFU Discord. The majority of mod creators are present there. Link below.

https://discord.com/channels/559842137374457876/650507773389307935

I don't know enough about this subject to say how possible it would be. I've encountered a partially blind player who played classic Daggerfall and said the chunky graphics and large text made it possible to enjoy. Depending on the individual, it might be possible to get by in DFU with retro mode, changing fonts, adjusting brightness sliders, and other hacks. It's also possible to change automap colours in DFU, but the accessibility options are certainly limited.

I do think it would be challenging to implement accessibility features for players on the more total side of blindness spectrum. Neither Daggerfall or DFU were designed with this in mind from the start. It would likely require a fork of the whole project to integrate needed support in the core. If someone works on such a project or mod for DFU, I'd certainly be interested in learning how they go about it.

I'll close this one now, as it's more a feature request than an issue. Good luck and all the best!
