### ISSUE TITLE
Store / guild door open time failure to update

### ISSUE THREAD

**Issue by btietz** [Interkarma/daggerfall-unity#2502]
**Describe the issue**

When standing around outside of guilds or stores, if it is closed, and you watch the time via "status" until the hour rolls over and the guild or store should be open now, the door status does not update.  It continues to say it is closed and state the open time, even after the opening time has rolled over.  If you pan the view off the door so that the the info panel disappears then pan back over the door, the store is open.  Loiter is similarly affected.  It seems like the door state needs to be updated periodically, or at trigger moments like exiting "status" or at the conclusion of loiter.

**To Reproduce**

As stated in describing the issue.

**Expected behavior**

The info panel stating that a store or guild is closed should update when appropriate, without having to pan off the door then back on.  Panning off and on is of course a simple workaround, but when I first noticed this issue, the workaround was not immediately apparent.  I only noticed that the workaround is available while characterizing the issue with respect to loiter.  Initially, I used save / load.

**Screenshots and Logs**

N/A

**Desktop (please complete the following information):**

 - OS: Windows 7
 - Version: 0.13.5

**Additional context**

In October 2021, I was forced out of my software engineering job after a 25 year career, because of a COVID vaccine mandate with which I was unable to comply due to a heart condition putting me at elevated risk from myocarditis.  At the time, I went onto github looking for a project that I would be interested in to keep my skills sharp.  Nothing caught my interest, but I have now found a project that I would like to contribute to.  I want to fix this bug, and as I continue to play through the game, fix any more bugs that I come across.  Or just start knocking out bugs reported by others, as long as I've played through the game far enough to be able to repro them.

I use Windows mainly, but I have an xubuntu virtual box that I use for light coding to maintain my skills.  IMO Visual C++ express 2008 was the apex of Microsoft's IDEs, before feature creep set in.  Much like how Windows 7 was the apex of Microsoft operating systems before they decided with Windows 8 that a desktop should have a tablet UI, then in Windows 10 doubled down by introducing user data harvesting / monetization, an overt violation of privacy.  But visual C++ express 2008 isn't available any longer.  So what is the best environment to use so that I may begin to contribute to this project?  I am guessing that would be linux (in my case, xubuntu) in virtual box.  But does the daggerfall unity project have any preconfigured IDE setups which should steer me towards kdevelop, eclipse, or something else?

**Comment by Interkarma** [comment]
This sounds like a mod, not an issue in DFU. There is no live door status when panning over the door. It's only possible to perform clicks using Info mode to printout opening hours. Testing this in game, the opening hours are not affected by player looking at door not.

Please contact mod author for support when it comes to mods. For personal support in your game, the best places to start are the forums or the Discord.

https://forums.dfworkshop.net/

https://discord.com/channels/559842137374457876/650507773389307935

**Comment by btietz** [comment]
Confirmed.  I now recall that the GOG cut offered the "world tooltips" mod during installation.  I see now that even when the tooltip text about store hours is out of date, going into activate cursor mode the door is functional immediately after the opening time.  Sorry for the false report.
