### ISSUE TITLE
Inescapable dungeon element

### ISSUE THREAD

**Issue by btietz** [Interkarma/daggerfall-unity#2504]
I have encountered an inescapable recurring dungeon element a few times, in 0.14.5 and previously.  I have attached a screenshot of it, along with a map view and saved game.  There is a lever to the left, which activates the elevator to the right.  The issue is that after activating the lever, by the time it is even possible to get back to the elevator, the elevator has ascended too much to get on top of it.  Everything to the right of that elevator loops back on itself, there is no way out down there.  The elevator in the screenshot is the only way out.  Caveat: you can get out using levitate or climbing, but the presence of that lever suggests that the elevator is intended to be the way out.  I suspect that the elevator's range of motion is supposed to extend somewhat lower, by enough to make it possible to mount the elevator after throwing the lever.

![View](https://user-images.githubusercontent.com/5986764/229306594-c32698c0-31a6-4860-a2c9-82085b452451.jpg)
![Map1](https://user-images.githubusercontent.com/5986764/229306597-c4343e2d-bea4-4d6b-848e-04315de2349f.jpg)
[SAVE55.zip](https://github.com/Interkarma/daggerfall-unity/files/11130213/SAVE55.zip)

**Comment by btietz** [comment]
Addendum: there is another lever just out of view to the right, directly adjacent to the elevator leading up.  That other elevator goes down.  It is possible that the actions of the two levers are swapped.   If so, then the lever adjacent to the elevator up could be activated while standing on the elevator up.

**Comment by petchema** [comment]
That's how it works in classic. And fixing it would require modifying dungeon data, not the DFU engine.
So that's modding domain (maybe Unofficial Block, Location and Model Fixes, if you manage to convince XJDHDR it's a bug)

**Comment by btietz** [comment]
Ah, okay.  I have seen this a number of times and given how prevalent it is (that being a recurring element) I didn't imagine that it could have been a bug in the original DF.
