### ISSUE TITLE
Dungeon element incorrect orientation

### ISSUE THREAD

**Issue by btietz** [Interkarma/daggerfall-unity#2505]
I entered a dungeon, and encountered a familiar recurring dungeon element just past the entrance.  This room has two doors.  One is blocked by a cage.  The room can only be entered from the other door.  Once in the room, activating a chest in the middle of the room causes the cage blocking the other door to begin sliding, allowing access to the other door.  In essence, this is a one-way room: until the player has activated the chest, the other door is unusable.  Once the chest has been activated, both doors can be used.

The issue in the case that I encountered is that from the entrance to the dungeon, the halls form a loop and the only way onward is through that room.  The room orientation is incorrect in that from the dungeon entry loop, the only way onward is through the aforementioned room, but coming at it from the dungeon entry side, the player is at the door which cannot be passed until the chest has been activated, but there's no way to get to the chest because there's no way to get to the other door.

Save game attached.

[SAVE16.zip](https://github.com/Interkarma/daggerfall-unity/files/11130471/SAVE16.zip)

**Comment by petchema** [comment]
There's a secret to move that cage from the other side.

Please use the forums or Discord for individual support.

Forums:
https://forums.dfworkshop.net

Discord:
https://discord.com/channels/559842137374457876

**Comment by btietz** [comment]
Ah, interesting.  The torch.  I tried that before I concluded that it must be a procedural layout bug.  You have to get REALLY close for activation to work on the torch.  And it doesn't show an <interact> prompt to suggest that it's even possible.

**Comment by petchema** [comment]
Dungeons were generated in 1996, there's no on-the-fly generation. And it doesn't have that granularity either, dungeons are made of huge hand-made pieces, randomness only occurs in the selection of which pieces makes each dungeon.
Classic Daggerfall has no "prompt" at all to tell what can be interacted with, it's a mod (World Tooltips)
