### ISSUE TITLE
14.5 wrong NPC sprites/wrong NPC names being used in certain regions

### ISSUE THREAD

**Issue by gekkedaan** [Interkarma/daggerfall-unity#2517]
This issue has already been adressed several times by people, but fruitless as it seems I'm going to give it another shot:

People in the northern parts of Hammerfell and Dragontail Mountains have either incorrect sprites or incorrect names. You appear to have mentioned several times that because this is also present in classic Daggerfall, this doesn't need fixing. From that point of view I don't see the point of implementing any fixes in Unity at all. It is well known that Daggerfall was released as a very buggy game that was rushed unto the market and many inconsistencies have already been fixed by Unity that were present in the vanilla version of the game. I consider this to be one of them and I don't think I am the only one.

The argument being made is that the issue I am presenting isn't a bug, yet in my point of view having parts of Hammerfall being primarily dominated by Bretons, **with Redguard names nonetheless**, should not be considered as a deliberate, well thought-out implementation in the original game.

So either one of two things is the case here:

1. The Breton NPC's in the northern parts of Hammerfell and Dragontail mountains have the wrong names attached to them.
2. The Redguard NPC's in the nothern parts of Hammerfell and Dragontail mountains have the wrong sprites attached to them.

Personally I think it's pretty obvious that point 2. is what's actually the case here, as Hammerfell, in it's entirety, is supposed to be the province of the Redguards. As far as I am aware there is no in-game lore (nor any Elder Scrolls lore as a matter of fact) that supports the notion of there being Breton colonies in Hammerfell. The architecture and NPC names in these locations also contradict this idea. Furthermore there is no in-game reference that supports the notion that Redguards (can) look identical to Bretons. On the contrary, I challenge everyone to go into Daggerfall's character creation screen and make a Breton looking Redguard.

As I respect and love your work, I hope this issue will be addressed in a future release and will thus be treated like all the other inconsistencies within the original game that you have already considered worthy of fixing.

Kind regards,

gekkedaan

**Comment by KABoissonneault** [comment]
If you want, the mod Vanilla Enhanced has a fix for that. It mixes the black skin of "desert" Redguards with the clothing of Bretons, to give "northern" Redguards are more distinct culture. After all, it snows in swamp and rainforest Hammerfell, so it could be silly to just put the desert clothing sprites up there.

![image](https://user-images.githubusercontent.com/5789925/236677731-a4babfc2-f102-44b4-a5de-f6000c09fb6f.png)
![image](https://user-images.githubusercontent.com/5789925/236677756-6422b8e2-51d2-430e-8353-7388ec1323e7.png)

In my opinion, it would be non-trivial for DFU to fix this (due to the new assets required), and should be left to mods.

**Comment by gekkedaan** [comment]
Thank you very much for your reply. I was not aware that this mod addresses the issue, I will check it out immediately. I also wasn't aware that there are some areas in Hammerfell where there is snow and are swamps and rainforests. From that point of view, it indeed seems strange to have bare-chested Redguards walking around in those areas. So thanks again for the tip, I appreciate it!

**Comment by Interkarma** [comment]
The usage of CLIMATE.PAK was the incorrect method for determining these race/name combos. This was later corrected by Ferital after reverse engineering the exact method classic uses. This is now matched to classic and considered the correct process.
