### ISSUE TITLE
0.15.2 TalkManager.GetLocalizedRegionName get regionIndex = -1 for buildings revealed by map_revealbuildings

### ISSUE THREAD

**Issue by petchema** [Interkarma/daggerfall-unity#2519]
**Describe the issue**

The name of buildings first revealed by the use of map_revealbuildings command use the untranslated region name instead of the localized one because TalkManager.GetLocalizedRegionName gets parameter regionIndex = -1 for them.
This is mostly obvious with banks since they're all named like "Bank of <region name>".

**To Reproduce**

1. Start DFU with some regionNames Internal_Strings.csv localization 
2. Enter a large city in a region with translated name
3. Type map_revealbuildings in the console
4. Check on local map that bank names use untranslated region name

**Expected behavior**

Buildings revealed with map_revealbuildings should always have the same name as if they were clicked one by one, or other means to learn their identity.

**Screenshots and Logs**

Name of the bank in front of the character learned from clicking on it; Name of the other bank learned from entering map_revealbuildings afterward:

![Capture d’écran du 2023-05-18 00-33-21](https://github.com/Interkarma/daggerfall-unity/assets/1211431/4b2ca33b-3d93-4f97-bf3d-9dba657f0e54)

**Desktop (please complete the following information):**

 - OS: Linux Mint
 - Version 21.1

**Additional context**

That problem is not created, nor fixed, by the use of refresh_buildingnames.

**Comment by Interkarma** [comment]
Would passing the player's current region to GetLocalizedRegionName() resolve this?

**Comment by petchema** [comment]
I think it would, I'm mostly unsure where it should be injected

**Comment by Interkarma** [comment]
I'll take a look. :)

**Comment by Interkarma** [comment]
The problem was that `ExteriorAutomap.CreateBuildingNameplates()` method was not using localized lookups for `map_revealbuildings`. I'll merge a fix.
