### ISSUE TITLE
[macOS] "Universal" release is an x64 build

### ISSUE THREAD

**Issue by shinra-electric** [Interkarma/daggerfall-unity#2530]
**Describe the issue**

The macOS download is marked as Universal, meaning it should have the x64 and Arm binaries in it. 

However, inspecting the bundle shows only x64 binaries. 

**Screenshots and Logs**

<img width="255" alt="Screenshot 2023-07-03 at 13 52 52" src="https://github.com/Interkarma/daggerfall-unity/assets/50119606/f8dcbb8a-5898-4924-9603-eaa6e2687034">

**Desktop (please complete the following information):**

 - OS: macOS
 - Version: 14

**Comment by Interkarma** [comment]
Hey there. :) This is the output from Mac Universal platform selection in Unity Cloud Build. There is is no ARM binary produced. If you'd like to build for a different platform, the source code is available for everyone.
