### ISSUE TITLE
Backspace key on Linux in map search input

### ISSUE THREAD

**Issue by Onyx47** [Interkarma/daggerfall-unity#2542]
**Describe the issue**

Hitting backspace produces a `?` character when searching for a location on map screen or when editing a save game name. Seems consistent with #1971 and https://forums.dfworkshop.net/viewtopic.php?t=1351 which are both resolved, but it seems it's still present in those particular input fields.

**To Reproduce**

1. Search for a location on the map or try to create a new save game.
2. Hit the <kbd>Backspace</kbd> key

**Desktop**

 - OS: Linux (Debian testing (trixie))
 - Version v0.16.1 RC

**Comment by Interkarma** [comment]
Hey there :) This is a regression in 0.16.1. It is already fixed in master and will be available in 0.16.2.
