### ISSUE TITLE
No versions work for me

### ISSUE THREAD

**Issue by TheAydo26** [Interkarma/daggerfall-unity#2546]
I followed the instructions about 2 years ago, it worked. The 1 year later I tried to start it up again and it just went black for 20 min. Now I am trying 0.16.1, I followed the instructions, it does the unity splash then it freezes. It used to work but it does not anymore. Both times I am on a windows 10 or 11 Lenovo laptop and used the DaggerFallGameFiles.zip to do it but I never got to the part of choosing the destination. I HAVE NO MODS.

**Comment by Jagget** [comment]
Wild guess. Did you try to clean/delete the `\AppData\LocalLow\Daggerfall Workshop\Daggerfall Unity` directory?

**Comment by petchema** [comment]
Also, prefer the forums for support requests:
https://forums.dfworkshop.net/viewforum.php?f=5

**Comment by TheAydo26** [comment]
I deleted every other Daggerfall thing there except for the Daggerfall game files and the steam version.

**Comment by TheAydo26** [comment]
Thank both of you I was able to find the solution. It was just deleting the settings.ini

**Comment by petchema** [comment]
By the way, next release should help with that kind of issue
https://forums.dfworkshop.net/viewtopic.php?p=66552#p66552
