### ISSUE TITLE
It is not possible to select the folder where Daggerfall is installed by default in Steam

### ISSUE THREAD

**Issue by Folko85** [Interkarma/daggerfall-unity#2557]
By default, on Ubuntu and probably other versions of Linux, Steam games are installed in a hidden .steam folder. It is impossible to select it through the interface. In addition, it probably uses an encoding other than UTF, since some folders are displayed with an incorrect name.
Of course, I can solve these problems on my computer, but I would like the Linux version to be more friendly.
![image](https://github.com/Interkarma/daggerfall-unity/assets/1721835/b7cc8105-2b41-493f-819f-8b2cc1bb1629)

**Comment by Interkarma** [comment]
The recommended way to install cross platform is the "DaggerfallGameFiles" method below. I'm happy to hear you were able to workaround in any case.

https://github.com/Interkarma/daggerfall-unity/wiki/Installing-Daggerfall-Unity-Cross-Platform

SDF fonts should use UTF encoding universally. Just to confirm problem, what are those folder names on your platform? If they contain any non-Latin glyphs (e.g. Cyrillic, Kanji, Hangul) then you'll need to install a new font for those characters to be displayed. The default fonts display Latin characters only.
