### ISSUE TITLE
Flatpak Build

### ISSUE THREAD

**Issue by fpiesche** [Interkarma/daggerfall-unity#2559]
This is kind of a re-opening of #1824; however I'm further along the curve: I have, in fact, [created a Flatpak manifest to package up the pre-built DFU executable](https://github.com/fpiesche/flathub/tree/io.github.Interkarma.daggerfall-unity) for easier distribution. This makes it a lot easier to install Daggerfall Unity on e.g. a Steam Deck.

I tried to create a build manifest that would actually set up and build the game from source which is more usually the done thing for Flatpaks; however Unity really does not want to be used in CI type setups, and Unity Personal licenses in particular cannot be used on a headless setup as the license must be activated via Unity Hub or a browser which is a brick wall for creating a Flatpak build from source.

To address a couple of the comments from #1824:
- While this build would basically be "just automatically creating an icon", a Flatpak build will also avoid dependency problems, as any required libraries (eg. GTK) are already included in the underlying Flatpak runtime. This is relevant on limited systems such as the Steam Deck, where adding system packages is very convoluted and unreliable. Currently SteamOS does come with all the dependencies required to run DFU, but I have made Flatpak builds for other game source ports that do not run on the Deck as is (and future SteamOS updates may in fact create dependency issues for DFU e.g. through version updates on system libraries).
- A Flatpak is an honestly much nicer vector for distribution than "here's a zip file with the executable in it, do with this as you will". Most major Linux distributions have Flatpak support and it's easy to install even on systems that don't have it built in, which means users will be able to find DFU by simply browsing their distribution's "app store" type application (eg. the Discover app on KDE/SteamOS). Furthermore, as above the Flatpak distribution will ensure all dependencies aside from the game data are bundled with the game regardless of the user's base system setup.
- There are many precedents for Flatpak builds of game engines not including copyrighted game data and requiring users to add this, such as various Quake or Doom source ports. Furthermore, I haven't tried this yet but should be able to set it up so that DFU will automatically detect and use an already-installed copy of Daggerfall from Steam with no need for users to select it on startup!

I would love to submit my build to Flathub for listing; the distribution would appear there similarly to e.g. my [QuakeSpasm one](http://flathub.org/apps/net.sourceforge.quakespasm.Quakespasm). There are a couple of requirements for this beforehand, though:

- [ ] I'd like to submit metadata files for Linux as a PR here to be used by the Flatpak build - Flathub generally request that these metadata files be submitted upstream rather than as part of the build manifests. The metadata files are a `.desktop` file which works as a "launcher" (so a menu item in the user's application launcher is automatically created for DFU) and an `.appdata.xml` file which contains the metadata used in the Flathub listing. The `.desktop` file would also be usable by anyone wanting a nicer experience with running the regular release distribution on their Linux desktop, as they could simply install it to have a menu item for running DFU.
- [ ] Aside from this, I will need permission from an actual maintainer on the DFU project to submit a PR to Flathub for the Flatpak build - this is a requirement on Flathub's side to prevent unauthorized submissions of applications to Flathub. I'll be happy to maintain the build there to minimise the extra work required from your side.

**Comment by fpiesche** [comment]
> The three desktop platforms I generate builds for are Windows, Linux, Mac. I also ensure these are tested to the best of my ability before release. I cannot personally endorse anything other than releases here that have passed either through my hands or one of the long-term contributors.

As noted, due to the problems with getting a Unity build from source working on Flathub's CI infrastructure (annoyingly, *solely* because activating a Personal Unity license cannot be done headless - the entire rest of the process works and is even documented by Unity) that is in fact what my Flatpak build now uses. The Flathub build I've put together just downloads the latest tagged release executable for Linux from here and wraps it in a Flatpak together with its dependencies. Any new release tagged and published here would kick off a build on Flathub and update the distribution there with the latest executable from here.

Please bear with me as I get a bit rambly about my reasoning for this - I still think just wrapping the existing builds in a Flatpak would be worthwhile because...

> Setting up Daggerfall Unity is already no more complicated than unzipping two archives. If somebody wants to use Linux builds, they can either download the provided zip from here...

... this is in fact not as simple as you may think. It does happen that Daggerfall Unity *does* - at this point in time - work on e.g. a Steam Deck as it is out of the box, but system updates to SteamOS (or any other Linux distribution) may change this at any point by upgrading or removing some of the system dependencies.

As an example, let's assume Valve were to remove GTK 2.x from the default SteamOS installation (or Arch Linux, their upstream distribution, did this) as it's been end-of-life since 2021 and install 3.x instead. Unity 2019 and anything built through it depend on GTK 2.x, so in this scenario users might find the current loose DFU executables suddenly no longer functional after simply updating their operating system.

What's more, on the Steam Deck (and other "immutable" Linux distributions such as Fedora Kinoite/Silverblue), there's no easy way to install anything to the base system that will persist through OS updates - in this situation any Steam Deck users would have to manually reinstall GTK2 after every SteamOS update to be able to run DFU. Even users on Linux systems where system packages can be installed and persist freely would have to install an end-of-life library to their base operating system (which may have just been removed from their distribution entirely, fail to install due to conflicts with other updated packages, or require them to compile from source).

The specific advantage to using Flatpak for distribution over loose executables is that it bundles all the system-level dependencies and sandboxes them (as well as the distributed application) away from each other and the underlying base system. Crucially this means every installation of a Flatpaked application is not only the same build of the application, but also the same build of the underlying system libraries, all installed to the user's home directory so they persist through updates on immutable distributions.

As a minor added bonus, Flatpak has a built-in automatic update notification/installation mechanism, so when a new release of DFU is made here and the Flathub build has run, any users would be informed and can just click "update" to get it.

This is why e.g. on the Steam Deck, aside from Steam itself Flatpak is the recommended way to install software - even by [Valve themselves](https://help.steampowered.com/en/faqs/view/671A-4453-E8D2-323C) and [Microsoft for Xbox Cloud Streaming](https://support.microsoft.com/en-gb/topic/xbox-cloud-gaming-in-microsoft-edge-with-steam-deck-43dd011b-0ce8-4810-8302-965be6d53296).

**Comment by Interkarma** [comment]
Daggerfall Unity targets desktop Windows, Linux, Mac. Installing to any other platform is an exercise for end user or alternate forks of the project not supported by me. Following are the only setup methods I support using my builds.

* [Using Steam Release of Daggerfall with Daggerfall Unity](https://github.com/Interkarma/daggerfall-unity/wiki/Using-Steam-Release-of-Daggerfall-with-Daggerfall-Unity)
* [Installing Daggerfall Unity Cross Platform](https://github.com/Interkarma/daggerfall-unity/wiki/Installing-Daggerfall-Unity-Cross-Platform)

If you want to fork the project and create a flatpak for certain Linux platforms, I don't believe there is anything stopping you from doing so. Please direct support for your flatpak builds towards your own channels and don't represent them as being endorsed by me.

I'm sorry but after the GOG Cut experience, I will not endorse or support any builds not directly maintained by me or a long-term trusted contributor.

**Comment by KABoissonneault** [comment]
Closing for now. New distributions are not currently planned. Do mention if there's something simpler we could do to help
