### ISSUE TITLE
Feature Request: Support Wayland Protocol under Linux

### ISSUE THREAD

**Issue by themaster567** [Interkarma/daggerfall-unity#2615]
**Describe the issue**

Daggerfall Unity does not currently support Wayland as even a launch parameter.

X is slowly being deprecated across various distros and will increasingly rely on things like XWayland in order to be supported, which is not ideal. The Fedora project, for example, will be dropping the X server entirely from its 41 release. which is the _next_ next version. That means, in a years time, this program will not officially function on it at all. This will increasingly become the case as more and more distros move over to Wayland.

**Additional context**

This was spurred by issues caused by XWayland that cause massive amounts of rapid graphical flickering and slow response time in any game rendering GUI elements. I am not reporting that as a bug here, as it is not the fault of the project. It is, however, a warning for what's to come as X becomes further left behind.

**Comment by KABoissonneault** [comment]
From:
https://forum.unity.com/threads/experimental-wayland-support-for-linux-player.1382685/

> Unity is experimenting with the support for the wayland desktop environment for the linux player builds on **Unity 2023.1.x.**

This is a Unity 2019 project, and always will for as long as we have pre-compiled mods to support. It is unfortunately not "just a checkbox" for us, and we don't do the engine maintenance to support this. 

It's good that you put this on record, but I don't see this project doing anything about this. A DFU fork on a modern Unity version could help there.

**Comment by themaster567** [comment]
Apologies about the checkbox remark, I'm going to remove that remark as I figured even when writing it that it probably wouldn't be so simple.

**Comment by KABoissonneault** [comment]
Closing this until this becomes a possibility for us. Issue can still be used as reference
