### ISSUE TITLE
Edit On screen control 

### ISSUE THREAD

**Issue by KyiThatTun** [Interkarma/daggerfall-unity#2663]
Control keys are too small and I missclick alot
Please make on screen control editable like open morrowind

**Comment by KyiThatTun** [comment]
Player controll like attack and cast spell

**Comment by KyiThatTun** [comment]
![Uploading Screenshot_2024_0604_183236_net.dfworkshop.dfu.jpg…]()
Like this

**Comment by KyiThatTun** [comment]
![Uploading Screenshot_2024_0604_183236_net.dfworkshop.dfu.jpg…]()

**Comment by KyiThatTun** [comment]
![Uploading Screenshot_2024_0604_183236_net.dfworkshop.dfu.jpg…]()

**Comment by KyiThatTun** [comment]
![Screenshot_2024_0604_183236_net.dfworkshop.dfu.jpg](https://github.com/Interkarma/daggerfall-unity/assets/145949581/f05ec6ae-aa3f-4cbb-b339-688ef4a63d82)

**Comment by KyiThatTun** [comment]
This one

**Comment by Vwing** [comment]
Hi, @KyiThatTun. You'll want to open this issue on the Android fork, not here.

https://github.com/Vwing/daggerfall-unity-android

**Comment by Vwing** [comment]
@KyiThatTun I've uploaded a new Android release that implements your requested feature. Made the on-screen buttons have customizable positions and scales, you can specify the on-screen control global alpha value, and you can add up to 12 additional buttons (or remove existing buttons)

https://github.com/Vwing/daggerfall-unity-android/releases/tag/v1.1.1.1
