### ISSUE TITLE
Request: add option for mipmaps to startup menu

### ISSUE THREAD

**Issue by fartingporkchop** [Interkarma/daggerfall-unity#2668]
currently there is an option to disable mipmaps in retro mode in the cfg file; however it won't disable mipmaps added from mods.

It would also be useful for enabling/disabling mipmaps outside of retro mode for preference.

**Comment by KABoissonneault** [comment]
I'm going to ask you to add this request to #2611 , as it covers the general idea, and is something we can tackle for v1.2. I'd rather not have a big pile of issues when we can avoid it.

For the mipmap from mods, I'm not sure whether that's a DFU issue, or simply the mod author not respecting the setting. Check with them, and if there's nothing they can do about it, feel free to open an issue about that so we can investigate.
