### ISSUE TITLE
PlayerGPS.GetCourtOfCurrentRegion() returns 0 courts in Mournoth

### ISSUE THREAD

**Issue by drcarademono** [Interkarma/daggerfall-unity#2672]
PlayerGPS.GetCourtOfCurrentRegion() returns 0 courts in Mournoth. I wasn't able to determine why that is. This bug causes Advanced Dialogue to break in Mournoth, because it expects all regions to have a court.

Error msg:
GetCourtOfCurrentRegion() did not find exactly 1 match.
UnityEngine.Debug:LogError (object)
DaggerfallWorkshop.PlayerGPS:GetCourtOfCurrentRegion () (at Assets/Scripts/Internal/PlayerGPS.cs:496)
DaggerfallWorkshop.Game.UserInterface.ADTalkWindow:GetFilterData () (at Assets/Game/Mods/advanced-dialogue/ADTalkWindow.cs:2085)
DaggerfallWorkshop.Game.UserInterface.ADTalkWindow:OnPush () (at Assets/Game/Mods/advanced-dialogue/ADTalkWindow.cs:376)
DaggerfallWorkshop.Game.UserInterface.UserInterfaceManager:AddWindow (DaggerfallWorkshop.Game.UserInterface.IUserInterfaceWindow) (at Assets/Scripts/Game/UserInterface/UserInterfaceManager.cs:182)
DaggerfallWorkshop.Game.UserInterface.UserInterfaceManager:PushWindow (DaggerfallWorkshop.Game.UserInterface.IUserInterfaceWindow) (at Assets/Scripts/Game/UserInterface/UserInterfaceManager.cs:82)
DaggerfallWorkshop.Game.TalkManager:TalkToNpc () (at Assets/Scripts/Game/TalkManager.cs:2634)
DaggerfallWorkshop.Game.TalkManager:TalkToMobileNPC (DaggerfallWorkshop.Game.MobilePersonNPC) (at Assets/Scripts/Game/TalkManager.cs:722)
DaggerfallWorkshop.Game.PlayerActivate:ActivateMobileNPC (UnityEngine.RaycastHit,DaggerfallWorkshop.Game.MobilePersonNPC) (at Assets/Scripts/Game/PlayerActivate.cs:747)
DaggerfallWorkshop.Game.PlayerActivate:Update () (at Assets/Scripts/Game/PlayerActivate.cs:413)

**Comment by KABoissonneault** [comment]
Fixed in [573fbd9](https://github.com/Interkarma/daggerfall-unity/commit/573fbd941b561a3e1a34e4395f31ecba9c316005)
