### ISSUE TITLE
When launching for the first time, after selecting the game file directory the mouse behaves oddly.

### ISSUE THREAD

**Issue by 2DSBrewer** [Interkarma/daggerfall-unity#2693]
It is impossible to select anything because the mouse is constantly moving down, although not smoothly.

**Comment by KABoissonneault** [comment]
Unplug your controller. 

I really don't know why it does that. Seems like an actual issue we should track

**Comment by 2DSBrewer** [comment]
I am using a bluetooth mouse and usb keyboard. No controller.

**Comment by KABoissonneault** [comment]
Can you go into your settings folder, edit settings.ini, and set EnableController to false? You might not have a controller, but your PC might think it does.

![image](https://github.com/user-attachments/assets/91f46022-c207-4e43-915e-f3bf179f513f)

Just wanna make sure

**Comment by 2DSBrewer** [comment]
I cannot find settings.ini, could you tell me where it is? (windows 11)
