### ISSUE TITLE
Data folder not found

### ISSUE THREAD

**Issue by EdenWise** [Interkarma/daggerfall-unity#2696]
With DFU 1.1.1 I get the following error when starting `DaggerfallUnity.exe`:

![Screenshot 2024-09-06 134551](https://github.com/user-attachments/assets/1ce8d221-b297-45ae-a07e-1c821422482b)

My guess is that this has to do with the executable detecting looking for a directory. For my portable install, junctions are being used:

````
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
l----          240906 Fri    12:43                DaggerfallUnity_Data -> C:\Users\...\Progr
                                                  ams\persist\daggerfallunity\DaggerfallUnity_Data
d----          240307 Thu    16:05                MonoBleedingEdge
l----          240906 Fri    12:43                PortableAppdata -> C:\Users\...\Programs\p
                                                  ersist\daggerfallunity\PortableAppdata
-a---          240508 Wed    11:43         650752 DaggerfallUnity.exe
-a---          240905 Thu    12:59             59 install.json
-a---          240710 Wed    14:09           2104 manifest.json
-a---          240905 Thu    12:59              0 Portable.txt
-a---          220608 Wed    14:05        1077896 UnityCrashHandler64.exe
-a---          220608 Wed    14:05       26173064 UnityPlayer.dll
````

Would it be possible to allow these for portable installs?

**Comment by KABoissonneault** [comment]
Am I understanding that you are using DFU's portable install feature (portable.txt), but using symbolic links / junctions to redirect it to an external folder? And you're saying the game does not recognize these?
From the screenshot you're posting, that popup is an engine one, not a game popup, so I don't believe the Unity engine will even let us do this, no matter what. 

Have you tried doing the junction only for the StreamingAssets folder? Also, do symbolic links work any better?
One thing to consider is that our settings.ini let you change the save and screenshot folders, but that's about it. The rest is determined by the engine

**Comment by EdenWise** [comment]
> Have you tried doing the junction only for the StreamingAssets folder? Also, do symbolic links work any better?

It is out of my choice. The program manager makes the links (junctions) so (disregarding any high maintenance) I'm bound to use them.

> Am I understanding that you are using DFU's portable install feature (portable.txt), but using symbolic links / junctions to redirect it to an external folder? And you're saying the game does not recognize these?
From the screenshot you're posting, that popup is an engine one, not a game popup, so I don't believe the Unity engine will even let us do this, no matter what...  The rest is determined by the engine

Thanks KABoissonneault, yeah that sums it up. It looks like I am bound to find Unity's bug report page. Any idea what I can report to them? As in what version of Unity being used...  Otherwise I will guess as good as I can :).

**Comment by KABoissonneault** [comment]
Is there a reason for reopening this?

**Comment by EdenWise** [comment]
Sorry was hoping for the Unity version. I think I found [it](https://thelacus.github.io/daggerfall-unity-docs/api/Global.VersionInfo.html)... Closing.

**Comment by EdenWise** [comment]
I have reported this to the [Unity development crew](https://discussions.unity.com/t/data-folder-not-found-daggerfall-unity/1517839)... so far it has failed to get a response.

**Comment by EdenWise** [comment]
Fixed this by doing as [KABoissonneault](https://github.com/KABoissonneault) suggested and only junctioning the StreamingAssets folder. Thank you for the help!
