### ISSUE TITLE
[FEATURE REQUEST] Quality-of-Life option for a more Morrowind-like fall damage.

### ISSUE THREAD

**Issue by TediusTimmy** [Interkarma/daggerfall-unity#2717]
I'm going to tell a story, rather than get to the point, because I wanted to note a bunch of things about a broken game (as in **_I_** broke the game).

I opened up my save file and started twiddling with my stats (thanks for making them JSON, that made it real easy). I put 200 in all core stats, and then 10000 in all abilities. This makes you fast. You run REAL fast. So fast that, when you run off the side of a mountain, you die on landing. I didn't change my HP because, with stats like that, why should I? I also should note that, with 10000 in jump, you jump kilometers into the air. It's amazing. It's probably the experience that the **Starfield** players feel that they are missing out on. AND, if you land only a tiny distance further down than where you jumped from, you die from fall damage.

That said: a running jump with 10000 in your abilities is amazing. It is absolutely awesome, despite being janky. (I assume that the jankyness is from doing magic with the map, due to the single-precision floats of Unity not being ideal for maintaining collusion detection within the sheer size of the Daggerfall game world. No normal player will ever experience this. It's not a bug, it's an observation.)

Also also: don't put your swim to 10000. You swim VERY VERY fast: you will likely clip through the ground when you reach the shore that you couldn't see, and fly off into the void.

I realize that no normal player in a normal play-through will experience the kind of behavior that compels me to write this issue. However, it may be a nice-to-have option for players. You could also say that that's what mods are for, and I haven't looked for any mods to do this, because I am not using any mods. Anyway, I'll attach some pictures of me doing things that the engine was never intended for.

![SupermanJump](https://github.com/user-attachments/assets/cc30519b-a2a9-4327-a4bf-6458a5e59ecb)
![IfItWerentForThatBayIdBeDead](https://github.com/user-attachments/assets/b4cba8f9-641e-4c96-8430-13c1b1188b25)

**Comment by KABoissonneault** [comment]
There is a Discord for sharing playthrough stories, search for Lysandus' Tomb.

>  You could also say that that's what mods are for

And I will say that. If you need to modify the game, we have a mod system for that. I understand that we've historically had some built-in modifications, like the Advanced Climbing system, or some other basics, but we're much later in development, and this is not a critical feature. Good luck with your search - the Discord server could help again
