### ISSUE TITLE
Accented characters are displayed as '?'

### ISSUE THREAD

**Issue by Berzeger** [Interkarma/daggerfall-unity#68]
For instance, "Nov? slo?ka" is supposed to be "Nová složka".
![image](https://cloud.githubusercontent.com/assets/6607148/14061372/0c4b0f1c-f37f-11e5-8b27-b2ffb91e59b5.png)

**Comment by Interkarma** [comment]
Thank you for bug report. This is a known limitation of the standard Daggerfall 8-bit character set, which does not support all Latin 1 extended ASCII characters, or non-Latin characters. Fortunately this is primarily a font rendering issue. The underlying folder pointer uses the correct path based on system culture and file-system navigation is still possible despite the characters displayed.

I will leave this issue open. Either a workaround will be implemented at some point or setup UI will be overhauled to support this. Proper localisation will be a requirement sometime in future.
