### ISSUE TITLE
GameManager.Instance.IsPlayerInsidePalace no longer evaluates to false after leaving palace

### ISSUE THREAD

**Issue by Nystul-the-Magician** [Interkarma/daggerfall-unity#91]
don't know since when this is bugged, but with one of the last changes this behaves no longer correct:
GameManager.Instance.IsPlayerInsidePalace no longer evaluates to false after leaving palace
this breaks automap and reflection mod

**Comment by Interkarma** [comment]
Flag is only valid when IsPlayerInside == true. Examples:

if (IsPlayerInside && IsPlayerInsideDungeon) // player is in dungeon
if (IsPlayerInside && IsPlayerInsideBuilding) // player is in building
if (IsPlayerInside && IsPlayerInsideDungeonPalace) // player is in dungeon palace block

**Comment by Interkarma** [comment]
Reopen: Or do you mean this fails while still inside dungeon and player has left the palace block?

**Comment by Nystul-the-Magician** [comment]
when going into daggerfall castle, then loading a outdoors quicksave and entering a normal building (tested with the odd blades in daggerfall)
IsPlayerInsideDungeonPalace is evaluating to true - which is not correct.

**Comment by Interkarma** [comment]
Cheers, will fix.

**Comment by Interkarma** [comment]
This should be resolved as of 0.3.x.
