### ISSUE TITLE
Mutiny support?

### ISSUE THREAD

**Issue by neuromancer** [Interkarma/daggerfall-unity#94]
I was wondering if it could be possible to build Daggerfall Unity using the open-source re-implementation of Unity: [Mutiny](http://www.mutiny3d.org).

**Comment by Interkarma** [comment]
An interesting topic, but please use forums or DFTFU subreddit for this kind of discussion. Thank you. :)
http://forums.dfworkshop.net/
https://www.reddit.com/r/dftfu
